"use client";
import {useEffect,useState} from "react";
import {menuTemplates,isMenuTemplate,isMenuColorMode,type MenuTemplate,type MenuColorMode} from "@/lib/restaurant/menu-templates";
import PublicMenu,{type PublicMenuProps} from "@/app/[slug]/public-menu";
import "@/app/[slug]/public-menu.css";
import "./template-editor.css";
const modeLabels={template:"مظهر القالب",light:"نهاري",dark:"ليلي",system:"حسب الجهاز"};
export default function TemplateEditor({tenantId}:{tenantId:string}){
 const [selected,setSelected]=useState<MenuTemplate>("sufra"),[mode,setMode]=useState<MenuColorMode>("template");
 const [saved,setSaved]=useState({template:"sufra",colorMode:"template"}),[preview,setPreview]=useState<PublicMenuProps|null>(null);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[device,setDevice]=useState("mobile"),[expanded,setExpanded]=useState(false);
 useEffect(()=>{let cancelled=false;fetch("/api/restaurant/menu/appearance",{headers:{"x-foon-tenant":tenantId},cache:"no-store"}).then(async r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{if(cancelled)return;if(isMenuTemplate(data.template)&&isMenuColorMode(data.colorMode)){setSelected(data.template);setMode(data.colorMode);setSaved({template:data.template,colorMode:data.colorMode})}setPreview(data.preview);setLoading(false)}).catch(()=>{if(!cancelled){setMessage("تعذر تحميل القالب الحالي. حدّث الصفحة وحاول مجددًا.");setLoading(false)}});return()=>{cancelled=true}},[tenantId]);
 async function save(){if(busy||loading)return;setBusy(true);setMessage("");try{const r=await fetch("/api/restaurant/menu/appearance",{method:"PUT",headers:{"content-type":"application/json","x-foon-tenant":tenantId},body:JSON.stringify({template:selected,colorMode:mode})});if(!r.ok)throw Error();setSaved({template:selected,colorMode:mode});setMessage("تم حفظ القالب والمظهر. يظهر التغيير في منيو مطعمك مباشرة.")}catch{setMessage("تعذر حفظ القالب. حاول مجددًا.")}finally{setBusy(false)}}
 return <section className="restaurantPanel menuTemplateEditor"><header><div><span className="menuEditorEyebrow">MENU STUDIO</span><h2>قوالب المنيو</h2><p>أربعة تخطيطات مختلفة، بهوية أحدث وتجربة مريحة على الجوال.</p></div><span className="menuEditorCount">04 / قوالب</span></header><div className="menuTemplateChoices" role="radiogroup" aria-label="قالب المنيو">{menuTemplates.map(t=><label key={t.id} className={"menuTemplateChoice menuMini-"+t.id} data-selected={selected===t.id}><input type="radio" name={"menu-template-"+tenantId} aria-label={t.name} value={t.id} checked={selected===t.id} disabled={loading||busy} onChange={()=>{setSelected(t.id);setMessage("")}}/><div className="menuMini" aria-hidden="true"><div className="menuMiniTop"><i/><b/><span/></div><div className="menuMiniHero"><i/><span/><b/></div><div className="menuMiniCategories"><i/><i/><i/><i/></div><div className="menuMiniCards">{[1,2,3,4].map(n=><div key={n}><i/><span><b/><small/><em/></span></div>)}</div></div><div className="menuTemplateCaption"><strong>{t.name}</strong><small>0{t.reference}</small><p>{t.description}</p></div></label>)}</div><div className="menuAppearanceBar"><label>مظهر المنيو<select aria-label="مظهر المنيو" value={mode} disabled={loading||busy} onChange={e=>{if(isMenuColorMode(e.target.value)){setMode(e.target.value);setMessage("")}}}>{Object.entries(modeLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><div className="menuEditorActions"><button className="restaurantOutline" type="button" disabled={!preview} aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?"إغلاق المعاينة":"معاينة القالب"}</button><button className="restaurantPrimary" type="button" disabled={busy||loading||!preview||selected===saved.template&&mode===saved.colorMode} onClick={()=>void save()}>{busy?"جارٍ الحفظ…":"حفظ القالب"}</button></div></div>{message&&<p className="restaurantNotice" role="status">{message}</p>}{expanded&&preview&&<div className="menuTemplatePreview"><header><div><b>معاينة منيو {preview.name}</b><p>بيانات مطعمك الفعلية · تغيير المعاينة لا يحفظ الإعدادات</p></div><div role="group" aria-label="حجم المعاينة"><button aria-pressed={device==="mobile"} onClick={()=>setDevice("mobile")}>جوال</button><button aria-pressed={device==="desktop"} onClick={()=>setDevice("desktop")}>كمبيوتر</button></div></header><div className="menuPreviewCanvas"><div className={"menuPreviewViewport "+(device==="mobile"?"is-mobile":"is-desktop")}><PublicMenu key={selected+"-"+mode+"-"+device} {...preview} preview branding={{...preview.branding,menuTheme:selected,colorMode:mode}}/></div></div></div>}</section>;
}
