export type MessageLanguage="ar"|"en"|"fr";
export type MessageTone="success"|"error"|"warning"|"info";
type Entry={tone:MessageTone;title:Record<MessageLanguage,string>;detail:Record<MessageLanguage,string>;action?:Record<MessageLanguage,string>};
export const systemMessages:Record<string,Entry>={
 REGISTER_SUCCESS:{tone:"success",title:{ar:"تم إنشاء حسابك بنجاح",en:"Your account is ready",fr:"Votre compte est prêt"},detail:{ar:"تم إنشاء نشاطك وتفعيل الباقة المجانية. يمكنك الآن إعداد واجهتك وإضافة خدماتك.",en:"Your business was created and the free plan activated. You can now set up your storefront and services.",fr:"Votre activité est créée et l’offre gratuite activée. Configurez maintenant votre vitrine et vos services."}},
 EMAIL_EXISTS:{tone:"warning",title:{ar:"البريد الإلكتروني مستخدم",en:"Email already registered",fr:"Adresse e-mail déjà utilisée"},detail:{ar:"يوجد حساب مرتبط بهذا البريد. سجّل الدخول أو استعد كلمة المرور بدل إنشاء حساب آخر.",en:"An account already uses this email. Sign in or reset your password instead.",fr:"Un compte utilise déjà cette adresse. Connectez-vous ou réinitialisez votre mot de passe."},action:{ar:"تسجيل الدخول",en:"Sign in",fr:"Connexion"}},
 SLUG_EXISTS:{tone:"warning",title:{ar:"رابط النشاط غير متاح",en:"Business URL unavailable",fr:"Adresse de l’activité indisponible"},detail:{ar:"الرابط المختار مستخدم بالفعل. اختر رابطًا مختلفًا ثم أعد المحاولة.",en:"This URL is already taken. Choose another and try again.",fr:"Cette adresse est déjà utilisée. Choisissez-en une autre."}},
 ACTIVITY_REQUIRED:{tone:"warning",title:{ar:"حدد نوع النشاط",en:"Choose a business activity",fr:"Choisissez une activité"},detail:{ar:"اختر النشاط المناسب حتى نجهّز لوحة التحكم والقالب الملائمين.",en:"Select your activity so we can prepare the appropriate workspace and template.",fr:"Sélectionnez votre activité pour préparer l’espace et le modèle adaptés."}},
 INVALID_LOCALE:{tone:"warning",title:{ar:"راجع الدولة وإعدادات الضريبة",en:"Check regional settings",fr:"Vérifiez les paramètres régionaux"},detail:{ar:"تأكد من الدولة والعملة ونسبة الضريبة المدخلة، ثم حاول مجددًا.",en:"Check the country, currency and tax rate, then try again.",fr:"Vérifiez le pays, la devise et le taux de taxe, puis réessayez."}},
 INVALID_INPUT:{tone:"warning",title:{ar:"بعض البيانات تحتاج تصحيحًا",en:"Please review your details",fr:"Vérifiez vos informations"},detail:{ar:"راجع الحقول المطلوبة والبريد وكلمة المرور ورابط النشاط قبل المتابعة.",en:"Review required fields, email, password and business URL.",fr:"Vérifiez les champs obligatoires, l’e-mail, le mot de passe et l’adresse de l’activité."}},
 REGISTER_UNAVAILABLE:{tone:"error",title:{ar:"تعذر إكمال التسجيل حاليًا",en:"Registration is temporarily unavailable",fr:"Inscription temporairement indisponible"},detail:{ar:"لم نتمكن من تأكيد إنشاء الحساب. لا تكرر المحاولة بسرعة؛ تحقق من وجود حسابك ثم أعد المحاولة لاحقًا.",en:"We couldn't confirm account creation. Check whether your account exists before trying again later.",fr:"Nous n’avons pas pu confirmer la création du compte. Vérifiez son existence avant de réessayer."}},
 NETWORK_ERROR:{tone:"error",title:{ar:"تعذر الاتصال بالخادم",en:"Connection failed",fr:"Échec de connexion"},detail:{ar:"تحقق من اتصال الإنترنت ثم أعد المحاولة. لم نتلقَّ تأكيدًا بنجاح العملية.",en:"Check your internet connection and try again. We have not confirmed that the action succeeded.",fr:"Vérifiez votre connexion puis réessayez. L’opération n’a pas été confirmée."}},
 LOGIN_INVALID:{tone:"warning",title:{ar:"تعذر تسجيل الدخول",en:"Sign-in unsuccessful",fr:"Connexion impossible"},detail:{ar:"البريد الإلكتروني أو كلمة المرور غير صحيحة. راجع البيانات أو استخدم استعادة كلمة المرور.",en:"Email or password is incorrect. Check your details or reset your password.",fr:"L’adresse e-mail ou le mot de passe est incorrect. Vérifiez-les ou réinitialisez le mot de passe."}},
 LOGIN_RATE_LIMIT:{tone:"warning",title:{ar:"تم تقييد المحاولات مؤقتًا",en:"Too many attempts",fr:"Trop de tentatives"},detail:{ar:"لحماية الحساب، انتظر قليلًا قبل المحاولة مجددًا.",en:"For account security, please wait before trying again.",fr:"Pour protéger votre compte, patientez avant de réessayer."}},
 ACTION_FAILED:{tone:"error",title:{ar:"لم تكتمل العملية",en:"Action not completed",fr:"Opération non terminée"},detail:{ar:"لم يؤكد النظام نجاح الإجراء. راجع البيانات وحاول مجددًا؛ وإذا استمرت المشكلة شارك رمز الخطأ مع الدعم.",en:"The action was not confirmed. Review the details and retry; share the error code with support if it persists.",fr:"L’opération n’a pas été confirmée. Vérifiez les données puis réessayez ; transmettez le code d’erreur au support si nécessaire."}}
};
export function getSystemMessage(code:string,language:MessageLanguage){const entry=systemMessages[code]??systemMessages.ACTION_FAILED;return {code,tone:entry.tone,title:entry.title[language],detail:entry.detail[language],action:entry.action?.[language]};}
