"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {operationApi} from './resource-manager';
import type {StoredResource} from '@/lib/restaurant/operations';
type Batch={key:number;id:string;name:string;start:number;count:number;capacity:number;waiterId:string;supervisorId:string};
const row=(key:number):Batch=>({key,id:'',name:'',start:1,count:10,capacity:4,waiterId:'',supervisorId:''});
export default function DiningBatch({tenantId,branch,branches,onChanged}:{tenantId:string;branch:string;branches:{id:string;name:string}[];onChanged:()=>void}){
 const [selectedBranch,setBranch]=useState(branch||branches[0]?.id||''),[rows,setRows]=useState([row(1)]),[sections,setSections]=useState<StoredResource[]>([]),[staff,setStaff]=useState<StoredResource[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;Promise.all([operationApi(tenantId,'sections','GET',undefined,selectedBranch),operationApi(tenantId,'team','GET',undefined,selectedBranch)]).then(([s,t])=>{if(alive){setSections(s.resources);setStaff(t.resources);}}).catch(e=>{if(alive)setMessage(e.message)});return()=>{alive=false}},[tenantId,selectedBranch]);
 const change=(key:number,value:Partial<Batch>)=>setRows(rows=>rows.map(r=>r.key===key?{...r,...value}:r));
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{const result=await operationApi(tenantId,'sections','POST',{branchId:selectedBranch,sections:rows.map(({key,...r})=>{void key;return {...r,id:r.id||undefined}})});setMessage('تم إنشاء '+result.count+' طاولة، وحُفظت أقسامها في عملية واحدة.');setRows([row(1)]);setSections((await operationApi(tenantId,'sections','GET',undefined,selectedBranch)).resources);onChanged();}catch(e){setMessage(e instanceof Error?e.message:'تعذر الحفظ')}finally{setBusy(false)}}
 return <section className="restaurantPanel diningBatch"><header><div><h3>إضافة أقسام وطاولات دفعة واحدة</h3><p>رقم الطاولة فريد داخل القسم. إذا تكرر رقم، تُلغى الدفعة كاملة دون إضافة جزئية.</p></div><strong>{rows.reduce((n,r)=>n+r.count,0)} طاولة</strong></header>{message&&<p role="status" className="restaurantNotice">{message}</p>}<form onSubmit={submit}><label>الفرع<select required value={selectedBranch} onChange={e=>{setBranch(e.target.value);setRows([row(1)])}}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{rows.map((r,i)=><fieldset key={r.key}><legend>المجموعة {i+1}</legend><div className="diningBatchFields"><label>القسم<select value={r.id} onChange={e=>change(r.key,{id:e.target.value,name:sections.find(s=>s.id===e.target.value)?.name||''})}><option value="">إنشاء قسم جديد</option>{sections.filter(s=>s.status==='active').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{!r.id&&<><label>اسم القسم<input required maxLength={180} value={r.name} onChange={e=>change(r.key,{name:e.target.value})} placeholder="مثال: العائلات"/></label>{(['waiterId','supervisorId'] as const).map(key=><label key={key}>{key==='waiterId'?'نادل القسم':'مشرف القسم'}<select value={r[key]} onChange={e=>change(r.key,{[key]:e.target.value})}><option value="">تعيين لاحقًا</option>{staff.filter(s=>s.status==='active'&&s.data.role===(key==='waiterId'?'waiter':'manager')).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>)}</>}<label>يبدأ من رقم<input required type="number" min={1} max={100000} value={r.start} onChange={e=>change(r.key,{start:Number(e.target.value)})}/></label><label>عدد الطاولات<input required type="number" min={1} max={100} value={r.count} onChange={e=>change(r.key,{count:Number(e.target.value)})}/></label><label>مقاعد كل طاولة<input required type="number" min={1} max={100} value={r.capacity} onChange={e=>change(r.key,{capacity:Number(e.target.value)})}/></label></div><footer><span>{r.name||'القسم الجديد'} · من {r.start} إلى {r.start+r.count-1} · {r.capacity} مقاعد</span>{rows.length>1&&<button type="button" onClick={()=>setRows(rows.filter(s=>s.key!==r.key))}>حذف المجموعة</button>}</footer></fieldset>)}<div className="restaurantFormActions"><button type="button" className="restaurantOutline" disabled={rows.length>=20} onClick={()=>setRows([...rows,row(Math.max(...rows.map(r=>r.key))+1)])}>إضافة قسم آخر +</button><button className="restaurantPrimary" disabled={busy||rows.reduce((n,r)=>n+r.count,0)>200}>{busy?'جارٍ الحفظ…':'إنشاء الدفعة'}</button></div><p className="restaurantFinePrint">حتى 200 طاولة في الدفعة. اختر النادل من الموظفين بدور «نادل»، والمشرف من الموظفين بدور «مدير». يمكن استكمال التعيين من أقسام الصالة.</p></form></section>;
}
