"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";

type Branch={id:string;name:string;slug:string;enabled:boolean};
type Feature={key:string;name:string;enabled:boolean;limit:number|null};
export type MerchantData={tenantId:string;name:string;slug:string;role:string;adminAccess:boolean;date:string;branches:Branch[];features:Feature[];subscription:{name:string;status:string;endsAt:string|null}|null;customerCount:number|null};
type Section="overview"|"branches"|"orders"|"pos"|"kds"|"menu"|"tables"|"inventory"|"team"|"marketing"|"reservations"|"subscription";
const modules:{key:Section;label:string;icon:string;feature?:string;roles:string[]}[]=[
 {key:"overview",label:"نظرة عامة",icon:"dashboard",roles:["owner","manager","cashier","waiter","kitchen","driver","accountant"]},
 {key:"branches",label:"الفروع والإعدادات",icon:"store",roles:["owner","manager"]},
 {key:"orders",label:"الطلبات",icon:"bag",feature:"orders",roles:["owner","manager","cashier","waiter","kitchen","driver"]},
 {key:"pos",label:"نقطة البيع",icon:"wallet",feature:"pos",roles:["owner","manager","cashier"]},
 {key:"kds",label:"شاشة المطبخ",icon:"chef",feature:"kds",roles:["owner","manager","kitchen"]},
 {key:"menu",label:"المنيو والأصناف",icon:"menu",feature:"digital_menu",roles:["owner","manager"]},
 {key:"tables",label:"الطاولات",icon:"table",feature:"tables",roles:["owner","manager","waiter"]},
 {key:"inventory",label:"المخزون والمشتريات",icon:"box",feature:"inventory",roles:["owner","manager","accountant"]},
 {key:"team",label:"الموظفون والحضور",icon:"users",feature:"employees",roles:["owner","manager"]},
 {key:"marketing",label:"التسويق والحملات",icon:"trend",feature:"campaigns",roles:["owner","manager"]},
 {key:"reservations",label:"الحجوزات والانتظار",icon:"clock",feature:"reservations",roles:["owner","manager","waiter"]},
 {key:"subscription",label:"الباقة والمميزات",icon:"shield",roles:["owner","manager"]},
];
const roles:Record<string,string>={owner:"مالك النشاط",manager:"مدير المطعم",cashier:"الكاشير",waiter:"النادل",kitchen:"المطبخ",driver:"التوصيل",accountant:"المحاسب"};
const statuses:Record<string,string>={active:"نشط",pending:"معلق",expired:"منتهي",cancelled:"ملغي"};
export function MerchantIcon({name}:{name:string}){
 const paths:Record<string,React.ReactNode>={
  dashboard:<><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>,
  store:<><path d="M3 10V5h18v5M3 10c0 4 6 4 6 0 0 4 6 4 6 0 0 4 6 4 6 0M5 14v7h14v-7M10 21v-6h4v6"/></>,
  bag:<><rect x="4" y="7" width="16" height="14" rx="2"/><path d="M8 7V5a4 4 0 0 1 8 0v2"/></>,
  wallet:<><rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 9h18M15 14h3"/></>,
  chef:<><path d="M6 13a5 5 0 0 1-1-10 5 5 0 0 1 7 0 5 5 0 0 1 7 0 5 5 0 0 1-1 10v7H6zM6 17h12"/></>,
  menu:<><path d="M4 3v7a3 3 0 0 0 6 0V3M7 3v18M20 21V3c-5 0-5 11 0 11"/></>,
  table:<><rect x="3" y="5" width="18" height="9" rx="2"/><path d="M6 14v7M18 14v7"/></>,
  box:<><path d="m12 3 9 5-9 5-9-5zM3 8v9l9 5 9-5V8M12 13v9M7 5l9 5"/></>,
  users:<><circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 4a3 3 0 0 1 0 6M18 15a5 5 0 0 1 3 5"/></>,
  trend:<><path d="m3 17 6-6 4 4 8-10M15 5h6v6"/></>,
  clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
  shield:<><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6"/></>,
  search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></>,
  bell:<><path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5zM10 21h4"/></>,
  arrow:<path d="m14 7-5 5 5 5"/>,
  plus:<path d="M12 5v14M5 12h14"/>,
 };
 return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.dashboard}</svg>;
}
function EmptyOperations({title,body}:{title:string;body:string}){return <div className="restaurantEmpty"><MerchantIcon name="bag"/><h3>{title}</h3><p>{body}</p></div>;}
export default function MerchantDashboard({data}:{data:MerchantData}){
 const router=useRouter(),searchRef=useRef<HTMLInputElement>(null);
 const [active,setActive]=useState<Section>("overview"),[branch,setBranch]=useState(""),[drawer,setDrawer]=useState(false),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState(""),[notifications,setNotifications]=useState(false),[profile,setProfile]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const canManage=["owner","manager"].includes(data.role),canPayments=["owner","manager","accountant"].includes(data.role);
 const visible=modules.filter(m=>m.roles.includes(data.role));
 const granted=(key?:string)=>!key||data.features.some(f=>f.key===key&&f.enabled);
 const selected=visible.find(m=>m.key===active)??visible[0];
 const shownBranches=data.branches.filter(b=>!branch||b.id===branch);
 const route="/restaurant?tenant="+encodeURIComponent(data.tenantId),paymentRoute="/restaurant/payments?tenant="+encodeURIComponent(data.tenantId);
 function navigate(section:Section){setActive(section);setDrawer(false);setSearchOpen(false);setQuery("");setMessage("");}
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setSearchOpen(true);}if(event.key==="Escape"){setSearchOpen(false);setDrawer(false);setNotifications(false);setProfile(false);}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler);},[]);
 useEffect(()=>{if(searchOpen)searchRef.current?.focus();},[searchOpen]);
 async function logout(){setBusy(true);try{const r=await fetch("/api/auth/logout",{method:"POST"});if(!r.ok)throw Error();router.replace("/login");router.refresh();}catch{setMessage("تعذر تسجيل الخروج. حاول مجدداً.");}finally{setBusy(false);}}
 async function createBranch(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const form=event.currentTarget,f=new FormData(form);setBusy(true);setMessage("");try{const r=await fetch("/api/restaurant/branches",{method:"POST",headers:{"content-type":"application/json","x-foon-tenant":data.tenantId},body:JSON.stringify({name:f.get("name"),slug:f.get("slug")})});const result=await r.json();if(!r.ok){setMessage(result.code==="PLAN_FEATURE_REQUIRED"?"تعدد الفروع غير متاح في الباقة الحالية.":result.code==="BRANCH_SLUG_EXISTS"?"رابط الفرع مستخدم مسبقاً.":"تعذر إنشاء الفرع. راجع البيانات وحاول مجدداً.");return;}form.reset();setMessage("تم إنشاء الفرع.");router.refresh();}catch{setMessage("تعذر الاتصال بالخادم.");}finally{setBusy(false);}}
 const navigation=<><div className="restaurantSideBrand"><span><MerchantIcon name="menu"/></span><div><b>FOON</b><small>نظام تشغيل المطاعم</small></div></div><p className="restaurantNavLabel">مساحة العمل</p><nav aria-label="أقسام المطعم">{visible.map(m=><button key={m.key} type="button" aria-current={active===m.key?"page":undefined} onClick={()=>navigate(m.key)}><MerchantIcon name={m.icon}/><span>{m.label}</span>{m.feature&&!granted(m.feature)&&<small title="غير مشمول في الباقة">مقفل</small>}</button>)}</nav><div className="restaurantSideFooter">{canManage&&<button className="restaurantPlanShortcut" type="button" onClick={()=>navigate("subscription")}><MerchantIcon name="shield"/><span><small>الاشتراك الحالي</small><b>{data.subscription?.name??"لم تعيّن باقة"}</b></span><MerchantIcon name="arrow"/></button>}<Link href={data.adminAccess?"/admin/tenants":"/account"}>{data.adminAccess?"العودة إلى إدارة المنصة":"حسابي"}<MerchantIcon name="arrow"/></Link></div></>;
 const branchList=<div className="restaurantBranchList">{shownBranches.length?shownBranches.map(b=><div key={b.id}><i data-enabled={b.enabled}/><span><b>{b.name}</b><small>{b.slug==="main"?"الفرع الرئيسي":b.slug}</small></span><em>{b.enabled?"مفعّل":"معطّل"}</em></div>):<p>لا توجد فروع ضمن الاختيار الحالي.</p>}</div>;
 return <div className="restaurantApp" dir="rtl">
  <aside className="restaurantSidebar">{navigation}</aside>
  {drawer&&<div className="restaurantDrawer"><button className="restaurantBackdrop" aria-label="إغلاق القائمة" onClick={()=>setDrawer(false)}/><aside><button className="restaurantClose" onClick={()=>setDrawer(false)} aria-label="إغلاق القائمة">×</button>{navigation}</aside></div>}
  <main className="restaurantMain"><header className="restaurantTopbar"><button className="restaurantMobileTrigger restaurantIconButton" aria-label="فتح قائمة المطعم" aria-expanded={drawer} onClick={()=>setDrawer(true)}><MerchantIcon name="dashboard"/></button><div className="restaurantBreadcrumb"><small>مساحة العمل / {data.name}</small><h1>{selected?.label??"نظرة عامة"}</h1></div><div className="restaurantTopActions"><label className="restaurantBranchSelector"><MerchantIcon name="store"/><span className="sr-only">اختيار الفرع</span><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">كل الفروع</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="restaurantSearchButton" onClick={()=>setSearchOpen(true)}><MerchantIcon name="search"/><span>بحث في الأقسام</span><kbd>Ctrl K</kbd></button><div className="restaurantPopoverAnchor"><button className="restaurantIconButton" aria-label="الإشعارات" aria-expanded={notifications} onClick={()=>{setNotifications(!notifications);setProfile(false);}}><MerchantIcon name="bell"/></button>{notifications&&<div className="restaurantPopover"><b>الإشعارات</b><p>ستظهر إشعارات المطعم هنا عند تفعيل خدمة الإشعارات.</p></div>}</div><div className="restaurantPopoverAnchor"><button className="restaurantAvatar" aria-label="قائمة الحساب" aria-expanded={profile} onClick={()=>{setProfile(!profile);setNotifications(false);}}>{data.name.slice(0,1)}</button>{profile&&<div className="restaurantPopover"><b>{data.name}</b><p>{roles[data.role]??data.role}</p><Link href="/account">حسابي</Link><button disabled={busy} onClick={()=>void logout()}>تسجيل الخروج</button></div>}</div></div></header>
  <div className="restaurantContent"><div className="restaurantPageHeading"><div><p>{data.date}</p><h2>{active==="overview"?"مركز إدارة "+data.name:selected?.label}</h2></div><span className="restaurantRoleBadge">{data.adminAccess?"دخول المشرف الأعلى":roles[data.role]??data.role}</span></div>{message&&<p className="restaurantNotice" role="status">{message}</p>}
  {active==="overview"?<>
   <section className="restaurantHero"><div className="restaurantHeroTop"><div><small>مساحة المطعم التشغيلية</small><h2>مرحباً بفريق {data.name}</h2><p>تابع مطعمك وفروعك وإعداداته من مساحة واحدة واضحة.</p></div><div className="restaurantHeroActions"><span>{data.subscription?.status==="active"?"الاشتراك نشط":"مساحة العمل"}</span><Link className="restaurantPrimary" href={"/"+encodeURIComponent(data.slug)}><MerchantIcon name="menu"/>فتح واجهة المطعم</Link></div></div><div className="restaurantHeroStats">{[["طلبات تحتاج متابعة","تظهر عند تفعيل الطلبات"],["قيد التحضير","تظهر عند ربط المطبخ"],["جاهزة للتسليم","تظهر عند تفعيل التشغيل"]].map(([title,note])=><div key={title}><p>{title}</p><strong>—</strong><small>{note}</small></div>)}</div></section>
   <section className="restaurantMetrics" aria-label="ملخص اليوم">{[["مبيعات اليوم","wallet","orange"],["طلبات اليوم","bag","blue"],["متوسط قيمة الطلب","trend","violet"],["الطاولات المشغولة","table","teal"]].map(([title,icon,tone])=><article key={title}><span className={"restaurantMetricIcon "+tone}><MerchantIcon name={icon}/></span><small>بانتظار بيانات التشغيل</small><p>{title}</p><strong>—</strong></article>)}</section>
   <div className="restaurantOverviewGrid"><section className="restaurantPanel"><header><div><h3>أداء المبيعات</h3><p>مبيعات المطعم اليومية</p></div><span className="restaurantPeriod">اليوم</span></header><EmptyOperations title="لا تتوفر بيانات مبيعات بعد" body="سيظهر الرسم بعد تفعيل الطلبات وربط بيانات المبيعات."/><footer><span>إجمالي المبيعات</span><b>—</b></footer></section><section className="restaurantPanel"><header><div><h3>الفروع النشطة</h3><p>الفروع المحفوظة للمطعم</p></div><MerchantIcon name="store"/></header>{branchList}{canManage&&<button className="restaurantOutline" onClick={()=>navigate("branches")}>إدارة الفروع<MerchantIcon name="arrow"/></button>}</section></div>
   <section className="restaurantPanel restaurantOrders"><header><div><h3>الطلبات الحالية</h3><p>متابعة الطلبات والتحضير والتسليم</p></div><span className="restaurantPeriod">قيد التجهيز</span></header><div className="restaurantOrderHead"><span>رقم الطلب</span><span>الطاولة / القناة</span><span>الأصناف</span><span>الإجمالي</span><span>الحالة</span></div><EmptyOperations title="خدمة الطلبات لم تُفعّل بعد" body="ستظهر طلبات مطعمك هنا عند تشغيل خدمة الطلبات."/></section>
   <section className="restaurantQuickActions" aria-label="الوصول السريع">{canManage&&<button onClick={()=>navigate("branches")}><span className="restaurantMetricIcon teal"><MerchantIcon name="store"/></span><span><b>إدارة الفروع</b><small>{data.branches.length} فروع محفوظة</small></span><MerchantIcon name="arrow"/></button>}{canPayments&&<Link href={paymentRoute}><span className="restaurantMetricIcon orange"><MerchantIcon name="wallet"/></span><span><b>إعدادات الدفع</b><small>وسائل دفع المنشأة</small></span><MerchantIcon name="arrow"/></Link>}{canManage&&<button onClick={()=>navigate("subscription")}><span className="restaurantMetricIcon violet"><MerchantIcon name="shield"/></span><span><b>الباقة والمميزات</b><small>{data.subscription?.name??"تفاصيل الاشتراك"}</small></span><MerchantIcon name="arrow"/></button>}</section>
  </>:active==="branches"?<section className="restaurantPanel"><header><div><h3>فروع المطعم</h3><p>إدارة الفروع المحفوظة في حسابك</p></div><MerchantIcon name="store"/></header>{branchList}{canManage&&<form className="restaurantBranchForm" onSubmit={createBranch}><h3>إضافة فرع</h3><label>اسم الفرع<input name="name" required minLength={2} maxLength={180}/></label><label>رابط الفرع<input name="slug" required minLength={3} maxLength={120} pattern="[a-z0-9][a-z0-9-]{1,118}[a-z0-9]" dir="ltr"/></label><button className="restaurantPrimary" disabled={busy||data.branches.length>=1&&!granted("multi_branch")}>{busy?"جارٍ الحفظ…":"إضافة الفرع"}</button>{data.branches.length>=1&&!granted("multi_branch")&&<p>إضافة أكثر من فرع تتطلب باقة تشمل تعدد الفروع.</p>}</form>}</section>:active==="subscription"?<section className="restaurantPanel"><header><div><h3>اشتراك المطعم</h3><p>تفاصيل الباقة الحالية</p></div><MerchantIcon name="shield"/></header><div className="restaurantSubscriptionSummary"><strong>{data.subscription?.name??"لا توجد باقة"}</strong><span>{statuses[data.subscription?.status??""]??"لا يوجد اشتراك"}</span>{data.subscription?.endsAt&&<p>نهاية الاشتراك: {data.subscription.endsAt}</p>}</div><div className="restaurantFeatureList">{data.features.map(f=><div key={f.key}><b>{f.name}</b><span data-enabled={f.enabled}>{f.enabled?"مشمولة":"غير مشمولة"}</span>{f.limit!==null&&<small>الحد: {f.limit}</small>}</div>)}</div><p className="restaurantFinePrint">المميزات المشمولة تحدد صلاحيات الباقة. توفرها في الباقة لا يعني اكتمال الخدمة التشغيلية.</p></section>:<section className="restaurantPanel"><header><div><h3>{selected?.label}</h3><p>{granted(selected?.feature)?"مشمولة في الباقة الحالية":"غير مشمولة في الباقة الحالية"}</p></div><MerchantIcon name={selected?.icon??"dashboard"}/></header><EmptyOperations title="هذه الخدمة قيد التجهيز" body="يمكنك الآن إدارة الفروع وإعدادات الدفع ومراجعة اشتراك المطعم."/><button className="restaurantOutline" onClick={()=>navigate("overview")}>العودة إلى نظرة عامة<MerchantIcon name="arrow"/></button></section>}
  {active==="overview"&&data.customerCount!==null&&<p className="restaurantFinePrint">العملاء المسجلون من واجهة المطعم: <b>{data.customerCount}</b></p>}
  <footer className="restaurantPageFooter"><span>FOON · {data.name}</span><Link href={route}>تحديث بيانات المطعم</Link></footer></div></main>
  {searchOpen&&<div className="restaurantSearchOverlay" role="dialog" aria-modal="true" aria-label="بحث في أقسام المطعم"><button className="restaurantBackdrop" aria-label="إغلاق البحث" onClick={()=>setSearchOpen(false)}/><div className="restaurantSearchDialog"><header><MerchantIcon name="search"/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} aria-label="ابحث عن قسم" placeholder="ابحث عن قسم في المطعم…"/><button onClick={()=>setSearchOpen(false)} aria-label="إغلاق البحث">×</button></header><nav>{visible.filter(m=>m.label.includes(query.trim())).map(m=><button key={m.key} onClick={()=>navigate(m.key)}><MerchantIcon name={m.icon}/>{m.label}<MerchantIcon name="arrow"/></button>)}</nav>{!visible.some(m=>m.label.includes(query.trim()))&&<p>لا توجد أقسام مطابقة.</p>}</div></div>}
 </div>;
}
