"use client";
import {useEffect,useRef,useState,type FormEvent,type KeyboardEvent as ReactKeyboardEvent} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {MerchantIcon} from "./merchant-icon";
import ServiceWorkspace,{UtilityWorkspace} from "./service-workspace";
import ResourceManager,{operationApi} from "./resource-manager";
import OrderWorkspace from "./order-workspace";
import PaymentEditor from "./payments/payment-editor";
import ReportsWorkspace from "./reports-workspace";

type Branch={id:string;name:string;slug:string;enabled:boolean;version:string};
type Feature={key:string;name:string;enabled:boolean;limit:number|null};
export type MerchantData={tenantId:string;name:string;slug:string;role:string;adminAccess:boolean;date:string;reportDay:string;branches:Branch[];features:Feature[];subscription:{name:string;status:string;endsAt:string|null}|null;customerCount:number|null;tenantChoices:{id:string;name:string}[]};
type Section="overview"|"branches"|"orders"|"pos"|"kds"|"menu"|"tables"|"inventory"|"team"|"marketing"|"reservations"|"subscription"|"customers"|"storefront"|"remote"|"security"|"health"|"payments"|"reports";
const modules:{key:Section;label:string;icon:string;feature?:string;roles:string[]}[]=[
 {key:"overview",label:"نظرة عامة",icon:"dashboard",roles:["owner","manager","cashier","waiter","kitchen","driver","accountant"]},
 {key:"branches",label:"الفروع والإعدادات",icon:"store",roles:["owner","manager"]},
 {key:"orders",label:"الطلبات",icon:"bag",feature:"orders",roles:["owner","manager","cashier","waiter","kitchen","driver"]},
 {key:"pos",label:"نقطة البيع",icon:"wallet",feature:"pos",roles:["owner","manager","cashier"]},
 {key:"kds",label:"شاشة المطبخ",icon:"chef",feature:"kds",roles:["owner","manager","kitchen"]},
 {key:"menu",label:"المنيو والأصناف",icon:"menu",feature:"digital_menu",roles:["owner","manager"]},
 {key:"tables",label:"الطاولات",icon:"table",feature:"tables",roles:["owner","manager","waiter"]},
 {key:"inventory",label:"المخزون والمشتريات",icon:"box",feature:"inventory",roles:["owner","manager","accountant"]},
 {key:"team",label:"الموظفون والحضور",icon:"users",feature:"employees",roles:["owner","manager"]},
 {key:"marketing",label:"التسويق والحملات",icon:"trend",feature:"campaigns",roles:["owner","manager"]},
 {key:"reservations",label:"الحجوزات والانتظار",icon:"clock",feature:"reservations",roles:["owner","manager","waiter"]},
 {key:"reports",label:"التقارير",icon:"trend",feature:"analytics",roles:["owner","manager","accountant"]},
 {key:"customers",label:"العملاء",icon:"users",feature:"customers",roles:["owner","manager"]},
 {key:"storefront",label:"هوية واجهة المطعم",icon:"store",feature:"branding.colors",roles:["owner","manager"]},
 {key:"remote",label:"التوظيف عن بُعد",icon:"users",feature:"employees",roles:["owner","manager"]},
 {key:"payments",label:"إعدادات الدفع",icon:"wallet",roles:["owner","manager","accountant"]},
 {key:"security",label:"أمان الحساب والجلسات",icon:"shield",roles:["owner","manager","cashier","waiter","kitchen","driver","accountant"]},
 {key:"health",label:"صحة النظام",icon:"dashboard",roles:["owner","manager"]},
 {key:"subscription",label:"الباقة والمميزات",icon:"shield",roles:["owner","manager"]},
];
const roles:Record<string,string>={owner:"مالك النشاط",manager:"مدير المطعم",cashier:"الكاشير",waiter:"النادل",kitchen:"المطبخ",driver:"التوصيل",accountant:"المحاسب"};
const statuses:Record<string,string>={active:"نشط",pending:"معلق",expired:"منتهي",cancelled:"ملغي"};
type LiveOrder={id:string;order_number:number;channel:string;status:string;payment_status:string;total:number|null;items:{name:string;quantity:number}[]};
type LiveOverview={summary:{sales:number|null;orders:number;average:number|null;newOrders:number;preparing:number;ready:number;tables:number;waiterCalls:number;reservations:number};series:{day:string;total:number}[];orders:LiveOrder[]};
function EmptyOperations({title,body}:{title:string;body:string}){return <div className="restaurantEmpty"><MerchantIcon name="bag"/><h3>{title}</h3><p>{body}</p></div>;}
function trapFocus(event:ReactKeyboardEvent<HTMLElement>){if(event.key!=="Tab")return;const items=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not([disabled]):not([tabindex="-1"]),input,a[href],select,textarea'));if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
export default function MerchantDashboard({data}:{data:MerchantData}){
 const router=useRouter(),searchRef=useRef<HTMLInputElement>(null),drawerCloseRef=useRef<HTMLButtonElement>(null);
 const [active,setActive]=useState<Section>("overview"),[branch,setBranch]=useState(""),[drawer,setDrawer]=useState(false),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState(""),[notifications,setNotifications]=useState(false),[profile,setProfile]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [editingBranch,setEditingBranch]=useState<Branch|null>(null);
 const [live,setLive]=useState<LiveOverview|null>(null),[revision,setRevision]=useState(0),[liveError,setLiveError]=useState("");
 useEffect(()=>{let alive=true;const load=()=>operationApi(data.tenantId,"overview","GET",undefined,branch).then(result=>{if(alive){setLive(result);setLiveError("");}}).catch(error=>{if(alive)setLiveError(String(error.message));});void load();const timer=setInterval(()=>void load(),15000);return()=>{alive=false;clearInterval(timer);};},[data.tenantId,branch,revision]);
 function changed(){setRevision(v=>v+1);router.refresh();}
 const canManage=["owner","manager"].includes(data.role),canPayments=["owner","manager","accountant"].includes(data.role);
 const visible=modules.filter(m=>m.roles.includes(data.role));
 const granted=(key?:string)=>!key||data.features.some(f=>f.key===key&&f.enabled);
 const selected=visible.find(m=>m.key===active)??visible[0];
 const shownBranches=data.branches.filter(b=>!branch||b.id===branch);
 const route="/restaurant?tenant="+encodeURIComponent(data.tenantId),paymentRoute="/restaurant/payments?tenant="+encodeURIComponent(data.tenantId);
 function navigate(section:Section){if(!modules.some(m=>m.key===section&&m.roles.includes(data.role)))return;setActive(section);setDrawer(false);setSearchOpen(false);setQuery("");setMessage("");}
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setSearchOpen(true);}if(event.key==="Escape"){setSearchOpen(false);setDrawer(false);setNotifications(false);setProfile(false);}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler);},[]);
 useEffect(()=>{if(searchOpen)searchRef.current?.focus();},[searchOpen]);
 useEffect(()=>{if(drawer)drawerCloseRef.current?.focus();},[drawer]);
 async function logout(){setBusy(true);try{const r=await fetch("/api/auth/logout",{method:"POST"});if(!r.ok)throw Error();router.replace("/login");router.refresh();}catch{setMessage("تعذر تسجيل الخروج. حاول مجدداً.");}finally{setBusy(false);}}
 async function createBranch(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const form=event.currentTarget,f=new FormData(form);setBusy(true);setMessage("");try{const r=await fetch("/api/restaurant/branches",{method:editingBranch?"PATCH":"POST",headers:{"content-type":"application/json","x-foon-tenant":data.tenantId},body:JSON.stringify({...(editingBranch?{id:editingBranch.id,version:editingBranch.version}:{}),name:f.get("name"),slug:f.get("slug")})});const result=await r.json();if(!r.ok){setMessage(result.code==="PLAN_FEATURE_REQUIRED"?"تعدد الفروع غير متاح في الباقة الحالية.":result.code==="BRANCH_SLUG_EXISTS"?"رابط الفرع مستخدم مسبقاً.":result.code==="CONFLICT"?"تغيّرت بيانات الفرع. حدّث الصفحة وأعد المحاولة.":"تعذر حفظ الفرع. راجع البيانات وحاول مجدداً.");return;}form.reset();setMessage(editingBranch?"تم تحديث الفرع.":"تم إنشاء الفرع.");setEditingBranch(null);changed();}catch{setMessage("تعذر الاتصال بالخادم.");}finally{setBusy(false);}}
 async function toggleBranch(value:Branch){if(busy)return;setBusy(true);try{const response=await fetch("/api/restaurant/branches",{method:"PATCH",headers:{"content-type":"application/json","x-foon-tenant":data.tenantId},body:JSON.stringify({id:value.id,version:value.version,enabled:!value.enabled})});const body=await response.json();if(!response.ok){setMessage(body.code==="BRANCH_HAS_OPEN_ORDERS"?"أكمل الطلبات المفتوحة قبل إيقاف الفرع.":"تعذر تحديث الفرع. حدّث البيانات وحاول مجدداً.");return;}setMessage("تم تحديث حالة الفرع.");changed();}catch{setMessage("تعذر الاتصال بالخادم.");}finally{setBusy(false);}}
 const navigation=<><div className="restaurantSideBrand"><span><MerchantIcon name="menu"/></span><div><b>FOON</b><small>نظام تشغيل المطاعم</small></div></div><p className="restaurantNavLabel">مساحة العمل</p><nav aria-label="أقسام المطعم">{visible.map(m=><button key={m.key} type="button" aria-current={active===m.key?"page":undefined} onClick={()=>navigate(m.key)}><MerchantIcon name={m.icon}/><span>{m.label}</span>{m.feature&&!granted(m.feature)&&<small title="غير مشمول في الباقة">مقفل</small>}</button>)}</nav><div className="restaurantSideFooter">{canManage&&<button className="restaurantPlanShortcut" type="button" onClick={()=>navigate("subscription")}><MerchantIcon name="shield"/><span><small>الاشتراك الحالي</small><b>{data.subscription?.name??"لم تعيّن باقة"}</b></span><MerchantIcon name="arrow"/></button>}<Link href={data.adminAccess?"/admin/tenants":"/account"}>{data.adminAccess?"العودة إلى إدارة المنصة":"حسابي"}<MerchantIcon name="arrow"/></Link></div></>;
 const branchList=<div className="restaurantBranchList">{shownBranches.length?shownBranches.map(b=><div key={b.id}><i data-enabled={b.enabled}/><span><b>{b.name}</b><small>{b.slug==="main"?"الفرع الرئيسي":b.slug}</small></span><em>{b.enabled?"مفعّل":"معطّل"}</em>{active==="branches"&&canManage&&<div className="restaurantBranchActions"><button disabled={busy} onClick={()=>setEditingBranch(b)}>تعديل</button><button disabled={busy} onClick={()=>void toggleBranch(b)}>{b.enabled?"إيقاف":"تفعيل"}</button></div>}</div>):<p>لا توجد فروع ضمن الاختيار الحالي.</p>}</div>;
 return <div className="restaurantApp" dir="rtl">
  <aside className="restaurantSidebar">{navigation}</aside>
  {drawer&&<div className="restaurantDrawer" role="dialog" aria-modal="true" aria-label="قائمة المطعم" onKeyDown={trapFocus}><button className="restaurantBackdrop" tabIndex={-1} aria-label="إغلاق القائمة" onClick={()=>setDrawer(false)}/><aside><button ref={drawerCloseRef} className="restaurantClose" onClick={()=>setDrawer(false)} aria-label="إغلاق القائمة">×</button>{navigation}</aside></div>}
  <main className="restaurantMain"><header className="restaurantTopbar"><button className="restaurantMobileTrigger restaurantIconButton" aria-label="فتح قائمة المطعم" aria-expanded={drawer} onClick={()=>setDrawer(true)}><MerchantIcon name="dashboard"/></button><div className="restaurantBreadcrumb"><small>مساحة العمل / {data.name}</small><h1>{selected?.label??"نظرة عامة"}</h1></div><div className="restaurantTopActions"><label className="restaurantTenantSelector"><span className="sr-only">اختيار المطعم</span><select aria-label="اختيار المطعم" value={data.tenantId} onChange={e=>router.push("/restaurant?tenant="+encodeURIComponent(e.target.value))}>{!data.tenantChoices.some(t=>t.id===data.tenantId)&&<option value={data.tenantId}>{data.name}</option>}{data.tenantChoices.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="restaurantBranchSelector"><MerchantIcon name="store"/><span className="sr-only">اختيار الفرع</span><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">كل الفروع</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="restaurantSearchButton" onClick={()=>setSearchOpen(true)}><MerchantIcon name="search"/><span>بحث في الأقسام</span><kbd>Ctrl K</kbd></button><div className="restaurantPopoverAnchor"><button className="restaurantIconButton" aria-label="الإشعارات" aria-expanded={notifications} onClick={()=>{setNotifications(!notifications);setProfile(false);}}><MerchantIcon name="bell"/>{(live?.summary.waiterCalls??0)+(live?.summary.reservations??0)>0&&<span className="restaurantServiceBadge" aria-label="طلبات خدمة جديدة">{(live?.summary.waiterCalls??0)+(live?.summary.reservations??0)}</span>}</button>{notifications&&<div className="restaurantPopover"><b>الإشعارات</b>{!!live?.summary.waiterCalls&&<button onClick={()=>{navigate("tables");setNotifications(false)}}>نداءات النادل: {live.summary.waiterCalls}</button>}{!!live?.summary.reservations&&<button onClick={()=>{navigate("reservations");setNotifications(false)}}>حجوزات تنتظر التأكيد: {live.summary.reservations}</button>}<p>{live?.summary.newOrders?live.summary.newOrders+" طلبات جديدة تحتاج متابعة.":"لا توجد طلبات جديدة تحتاج متابعة."}</p></div>}</div><div className="restaurantPopoverAnchor"><button className="restaurantAvatar" aria-label="قائمة الحساب" aria-expanded={profile} onClick={()=>{setProfile(!profile);setNotifications(false);}}>{data.name.slice(0,1)}</button>{profile&&<div className="restaurantPopover"><b>{data.name}</b><p>{roles[data.role]??data.role}</p><Link href="/account">حسابي</Link><Link href="/account/library">مكتبة صوري</Link><button disabled={busy} onClick={()=>void logout()}>تسجيل الخروج</button></div>}</div></div></header>
  <div className="restaurantContent"><div className="restaurantPageHeading"><div><p>{data.date}</p><h2>{active==="overview"?"مركز إدارة "+data.name:selected?.label}</h2></div><span className="restaurantRoleBadge">{data.adminAccess?"دخول المشرف الأعلى":roles[data.role]??data.role}</span></div>{message&&<p className="restaurantNotice" role="status">{message}</p>}{liveError&&active==="overview"&&<p className="restaurantNotice" role="alert">{liveError}</p>}
  {active==="overview"?<>
   <section className="restaurantHero"><div className="restaurantHeroTop"><div><small>مساحة المطعم التشغيلية</small><h2>مرحباً بفريق {data.name}</h2><p>تابع مطعمك وفروعك وإعداداته من مساحة واحدة واضحة.</p></div><div className="restaurantHeroActions"><span>{data.subscription?.status==="active"?"الاشتراك نشط":data.subscription?"الاشتراك "+(statuses[data.subscription.status]??data.subscription.status):"مساحة العمل"}</span><Link className="restaurantPrimary" href={"/"+encodeURIComponent(data.slug)}><MerchantIcon name="menu"/>فتح واجهة المطعم</Link></div></div><div className="restaurantHeroStats">{[["طلبات تحتاج متابعة",live?.summary.newOrders,"طلبات جديدة"],["قيد التحضير",live?.summary.preparing,"متابعة فريق المطبخ"],["جاهزة للتسليم",live?.summary.ready,"بانتظار التسليم"]].map(([title,count,note])=><div key={String(title)}><p>{title}</p><strong>{count??"—"}</strong><small>{note}</small></div>)}</div></section>
   <section className="restaurantMetrics" aria-label="ملخص اليوم">{[{title:"مبيعات اليوم",value:live?.summary.sales==null?"—":live.summary.sales.toFixed(2)+" ر.س",icon:"wallet",tone:"orange"},{title:"طلبات اليوم",value:live?.summary.orders??"—",icon:"bag",tone:"blue"},{title:"متوسط قيمة الطلب",value:live?.summary.average==null?"—":live.summary.average.toFixed(2)+" ر.س",icon:"trend",tone:"violet"},{title:"الطاولات المشغولة",value:live?.summary.tables??"—",icon:"table",tone:"teal"}].map(m=><article key={m.title}><span className={"restaurantMetricIcon "+m.tone}><MerchantIcon name={m.icon}/></span><small>{live?"من بيانات المطعم":"جارٍ التحقق…"}</small><p>{m.title}</p><strong>{m.value}</strong></article>)}</section>
   <div className="restaurantOverviewGrid"><section className="restaurantPanel"><header><div><h3>أداء المبيعات</h3><p>مبيعات المطعم اليومية</p></div><span className="restaurantPeriod">اليوم</span></header>{live?.series.length?<div className="restaurantSalesChart"><svg viewBox="0 0 600 180" role="img" aria-label="أداء المبيعات من الطلبات المدفوعة"><line x1="10" x2="590" y1="165" y2="165" stroke="#e2e8f0"/>{live.series.map((s,i)=><rect key={s.day} x={20+i*(560/live.series.length)} y={165-Math.max(2,s.total/Math.max(...live.series.map(x=>x.total),1)*145)} width={Math.min(54,400/live.series.length)} height={Math.max(2,s.total/Math.max(...live.series.map(x=>x.total),1)*145)} rx="6" fill="#e76f3c"/>)}</svg><div>{live.series.map(s=><span key={s.day}>{s.day.slice(5)}<b>{s.total.toFixed(2)}</b></span>)}</div></div>:<EmptyOperations title="لا توجد مبيعات مدفوعة بعد" body="ستظهر المبيعات تلقائياً بعد إنشاء الطلبات وتسجيل الدفع."/>}<footer><span>إجمالي مبيعات اليوم</span><b>{live?.summary.sales==null?"—":live.summary.sales.toFixed(2)+" ر.س"}</b></footer></section><section className="restaurantPanel"><header><div><h3>الفروع النشطة</h3><p>الفروع المحفوظة للمطعم</p></div><MerchantIcon name="store"/></header>{branchList}{canManage&&<button className="restaurantOutline" onClick={()=>navigate("branches")}>إدارة الفروع<MerchantIcon name="arrow"/></button>}</section></div>
   <section className="restaurantPanel restaurantOrders"><header><div><h3>الطلبات الحالية</h3><p>متابعة الطلبات والتحضير والتسليم</p></div><button className="restaurantOutline" onClick={()=>navigate("orders")}>كل الطلبات<MerchantIcon name="arrow"/></button></header><div className="restaurantOrderHead"><span>رقم الطلب</span><span>الطاولة / القناة</span><span>الأصناف</span><span>الإجمالي</span><span>الحالة</span></div>{live?.orders.length?<div className="restaurantLiveOrders">{live.orders.slice(0,6).map(o=><button key={o.id} onClick={()=>navigate("orders")}><b>#{o.order_number}</b><span>{o.channel==="dine_in"?"داخل المطعم":o.channel==="takeaway"?"سفري":"توصيل"}</span><span>{o.items.map(i=>i.quantity+" × "+i.name).join("، ")}</span><strong>{o.total==null?"—":o.total.toFixed(2)+" ر.س"}</strong><em>{({new:"جديد",preparing:"تحضير",ready:"جاهز",completed:"مكتمل",cancelled:"ملغي"} as Record<string,string>)[o.status]}</em></button>)}</div>:<EmptyOperations title="لا توجد طلبات محفوظة بعد" body="ابدأ بإنشاء أول طلب من نقطة البيع."/>}</section>
   <section className="restaurantQuickActions" aria-label="الوصول السريع">{canManage&&<button onClick={()=>navigate("branches")}><span className="restaurantMetricIcon teal"><MerchantIcon name="store"/></span><span><b>إدارة الفروع</b><small>{data.branches.length} فروع محفوظة</small></span><MerchantIcon name="arrow"/></button>}{canPayments&&<Link href={paymentRoute}><span className="restaurantMetricIcon orange"><MerchantIcon name="wallet"/></span><span><b>إعدادات الدفع</b><small>وسائل دفع المنشأة</small></span><MerchantIcon name="arrow"/></Link>}{canManage&&<button onClick={()=>navigate("subscription")}><span className="restaurantMetricIcon violet"><MerchantIcon name="shield"/></span><span><b>الباقة والمميزات</b><small>{data.subscription?.name??"تفاصيل الاشتراك"}</small></span><MerchantIcon name="arrow"/></button>}</section>
  </>:active==="branches"?<section className="restaurantPanel"><header><div><h3>فروع المطعم</h3><p>إدارة الفروع المحفوظة في حسابك</p></div><MerchantIcon name="store"/></header>{branchList}{canManage&&<form key={editingBranch?.id??"new"} className="restaurantBranchForm" onSubmit={createBranch}><h3>{editingBranch?"تعديل الفرع":"إضافة فرع"}</h3><label>اسم الفرع<input name="name" required minLength={2} maxLength={180} defaultValue={editingBranch?.name??""}/></label><label>رابط الفرع<input name="slug" required minLength={3} maxLength={120} pattern="[a-z0-9][a-z0-9-]{1,118}[a-z0-9]" dir="ltr" defaultValue={editingBranch?.slug??""}/></label><button className="restaurantPrimary" disabled={busy||!editingBranch&&data.branches.length>=1&&!granted("multi_branch")}>{busy?"جارٍ الحفظ…":editingBranch?"حفظ الفرع":"إضافة الفرع"}</button>{editingBranch&&<button type="button" className="restaurantOutline" onClick={()=>setEditingBranch(null)}>إلغاء التعديل</button>}{!editingBranch&&data.branches.length>=1&&!granted("multi_branch")&&<p>إضافة أكثر من فرع تتطلب باقة تشمل تعدد الفروع.</p>}</form>}<ResourceManager key={"settings-"+branch} tenantId={data.tenantId} module="settings" branch={branch} branches={data.branches.filter(b=>b.enabled)} onChanged={changed}/></section>:active==="subscription"?<section className="restaurantPanel"><header><div><h3>اشتراك المطعم</h3><p>تفاصيل الباقة الحالية</p></div><MerchantIcon name="shield"/></header><div className="restaurantSubscriptionSummary"><strong>{data.subscription?.name??"لا توجد باقة"}</strong><span>{statuses[data.subscription?.status??""]??"لا يوجد اشتراك"}</span>{data.subscription?.endsAt&&<p>نهاية الاشتراك: {data.subscription.endsAt}</p>}</div><div className="restaurantFeatureList">{data.features.map(f=><div key={f.key}><b>{f.name}</b><span data-enabled={f.enabled}>{f.enabled?"مشمولة":"غير مشمولة"}</span>{f.limit!==null&&<small>الحد: {f.limit}</small>}</div>)}</div><p className="restaurantFinePrint">المميزات المشمولة تحدد صلاحيات الباقة. توفرها في الباقة لا يعني اكتمال الخدمة التشغيلية.</p></section>:["orders","pos","kds"].includes(active)?<OrderWorkspace key={active+"-"+branch} tenantId={data.tenantId} module={active} branch={branch} branches={data.branches.filter(b=>b.enabled)} role={data.role} onChanged={changed}/>:["security","customers","health"].includes(active)?<UtilityWorkspace key={active} tenantId={data.tenantId} section={active}/>:active==="reports"?<ReportsWorkspace key={branch} tenantId={data.tenantId} branch={branch} today={data.reportDay}/>:active==="payments"?<PaymentEditor tenantId={data.tenantId} branches={data.branches.filter(b=>b.enabled)} canEdit={data.role!=="accountant"}/>:<ServiceWorkspace key={active+"-"+branch} tenantId={data.tenantId} section={active} branch={branch} branches={data.branches.filter(b=>b.enabled)} onChanged={changed}/>}
  {active==="overview"&&data.customerCount!==null&&<p className="restaurantFinePrint">العملاء المسجلون من واجهة المطعم: <b>{data.customerCount}</b></p>}
  <footer className="restaurantPageFooter"><span>FOON · {data.name}</span><Link href={route}>تحديث بيانات المطعم</Link></footer></div></main>
  {searchOpen&&<div className="restaurantSearchOverlay" role="dialog" aria-modal="true" aria-label="بحث في أقسام المطعم" onKeyDown={trapFocus}><button className="restaurantBackdrop" tabIndex={-1} aria-label="إغلاق البحث" onClick={()=>setSearchOpen(false)}/><div className="restaurantSearchDialog"><header><MerchantIcon name="search"/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} aria-label="ابحث عن قسم" placeholder="ابحث عن قسم في المطعم…"/><button onClick={()=>setSearchOpen(false)} aria-label="إغلاق البحث">×</button></header><nav>{visible.filter(m=>m.label.includes(query.trim())).map(m=><button key={m.key} onClick={()=>navigate(m.key)}><MerchantIcon name={m.icon}/>{m.label}<MerchantIcon name="arrow"/></button>)}</nav>{!visible.some(m=>m.label.includes(query.trim()))&&<p>لا توجد أقسام مطابقة.</p>}</div></div>}
 </div>;
}
