"use client";
import {useEffect,useState} from "react";
import {operationApi} from "./resource-manager";
import {MerchantIcon} from "./merchant-icon";
import PosTerminal from "./pos-terminal";
type Order={id:string;order_number:number;branch_id:string;status:string;payment_status:string;total:number|null;version:number;channel:string;dining_section_id:string|null;party_size:number|null;dining_snapshot:{name:string;sectionName:string}|null;customer_name:string|null;customer_email:string|null;customer_phone:string|null;created_at:string;items:{name:string;quantity:number}[]};
const statuses:Record<string,string>={new:"جديد",preparing:"قيد التحضير",ready:"جاهز",completed:"مكتمل",cancelled:"ملغي"};
const payments:Record<string,string>={paid:"مدفوع",unpaid:"غير مدفوع",refunded:"تم رد المبلغ"};
export default function OrderWorkspace({tenantId,actorId,name,module,branch,branches,role,onChanged}:{tenantId:string;actorId:string;name:string;module:string;branch:string;branches:{id:string;name:string}[];role:string;onChanged:()=>void}){
 const [orders,setOrders]=useState<Order[]>([]),[filter,setFilter]=useState("all"),[sectionFilter,setSectionFilter]=useState(""),[search,setSearch]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function refresh(){const data=await operationApi(tenantId,module,"GET",undefined,branch);setOrders(data.orders)}
 useEffect(()=>{let alive=true;const load=()=>operationApi(tenantId,module,"GET",undefined,branch).then(data=>{if(alive){setOrders(data.orders);setLoading(false)}}).catch(error=>{if(alive){setLoading(false);setMessage(String(error.message))}});void load();const timer=setInterval(()=>void load(),15000);return()=>{alive=false;clearInterval(timer)}},[tenantId,module,branch]);
 async function update(order:Order,change:{status?:string;paymentStatus?:string}){if(busy)return;setBusy(true);try{await operationApi(tenantId,module,"PATCH",{id:order.id,version:order.version,...change});await refresh();onChanged();setMessage("تم تحديث الطلب.")}catch(error){setMessage(error instanceof Error?error.message:"تعذر التحديث.")}finally{setBusy(false)}}
 function actions(order:Order){const next:Record<string,string>={new:"preparing",preparing:"ready",ready:"completed"};const canAdvance=["owner","manager","cashier"].includes(role)||role==="kitchen"&&["new","preparing"].includes(order.status)||["waiter","driver"].includes(role)&&order.status==="ready";
 return <div className="restaurantOrderActions">{canAdvance&&next[order.status]&&<button className="restaurantOrderAdvance" disabled={busy} onClick={()=>void update(order,{status:next[order.status]})}>نقل إلى {statuses[next[order.status]]}</button>}{["owner","manager","cashier"].includes(role)&&order.status!=="cancelled"&&<>{order.payment_status==="unpaid"?<button disabled={busy} onClick={()=>void update(order,{paymentStatus:"paid"})}>تسجيل دفع يدوي</button>:order.payment_status==="paid"?<button className="restaurantOrderRefund" disabled={busy} onClick={()=>void update(order,{paymentStatus:"refunded"})}>تسجيل رد المبلغ</button>:null}{["new","preparing","ready"].includes(order.status)&&order.payment_status!=="paid"&&<button className="restaurantOrderCancel" disabled={busy} onClick={()=>void update(order,{status:"cancelled"})}>إلغاء الطلب</button>}</>}</div>}
 const scoped=orders.filter(o=>!sectionFilter||o.dining_section_id===sectionFilter),selected=scoped.filter(o=>(filter==="all"||o.status===filter)&&[o.order_number,o.customer_name,o.customer_email,o.customer_phone,...o.items.map(i=>i.name)].join(' ').toLowerCase().includes(search.toLowerCase().trim()));
 return <section className="restaurantPanel restaurantOrderWorkspace" data-module={module}><header><div><h3>{module==="pos"?"نقطة البيع":module==="kds"?"شاشة المطبخ":"إدارة الطلبات"}</h3><p>تحديث تلقائي كل 15 ثانية · الأسعار والحالات من النظام</p></div><MerchantIcon name={module==="kds"?"chef":"bag"}/></header>{message&&<p className="restaurantNotice" role="status">{message}</p>}{module==="pos"&&<PosTerminal tenantId={tenantId} actorId={actorId} name={name} branch={branch} branches={branches} onCreated={()=>{void refresh();onChanged()}}/>}
 <div className="restaurantOrderPulse" aria-label="ملخص الطلبات المعروضة">{[['new','طلبات جديدة'],['preparing','قيد التحضير'],['ready','جاهزة للتسليم'],['unpaid','بانتظار الدفع']].map(([key,label])=><div key={key} data-status={key}><span>{label}</span><strong>{scoped.filter(o=>key==='unpaid'?o.payment_status==='unpaid'&&o.status!=='cancelled':o.status===key).length}</strong></div>)}</div>
 <div className="restaurantOrderToolbar"><label>البحث في الطلبات<input type="search" aria-label="البحث في الطلبات" placeholder="رقم الطلب، الاسم، البريد أو الصنف" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>قسم الصالة<select aria-label="قسم طلبات الصالة" value={sectionFilter} onChange={e=>setSectionFilter(e.target.value)}><option value="">كل الأقسام والقنوات</option>{[...new Map(orders.filter(o=>o.dining_section_id).map(o=>[o.dining_section_id!,o.dining_snapshot?.sectionName||"قسم الصالة"])).entries()].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><div className="restaurantStatusFilters">{["all","new","preparing","ready","completed","cancelled"].map(status=><button key={status} aria-label={status==='all'?'الكل':statuses[status]} aria-pressed={filter===status} onClick={()=>setFilter(status)}>{status==="all"?"الكل":statuses[status]} <small aria-hidden="true">{scoped.filter(o=>status==='all'||o.status===status).length}</small></button>)}</div>
 {loading?<p>جارٍ تحميل الطلبات…</p>:selected.length?<div className="restaurantOrderCards">{selected.map(order=><article key={order.id} data-status={order.status}><header><div className="restaurantOrderIdentity"><span className="restaurantOrderSymbol"><MerchantIcon name="bag"/></span><div><small>طلب المطعم</small><b>#{order.order_number}</b></div></div><span className="restaurantStateBadge" data-status={order.status}>{statuses[order.status]}</span></header><div className="restaurantOrderGuest"><strong>{order.customer_name||"ضيف"}</strong><span>{order.channel==="dine_in"?"داخل المطعم":order.channel==="takeaway"?"سفري":"توصيل"}</span></div><time className="restaurantOrderTime" dateTime={order.created_at}>{new Date(order.created_at).toLocaleString("ar-SA",{timeZone:"Asia/Riyadh",calendar:"gregory",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}</time><address className="restaurantGuestContact">{order.customer_email&&<a href={"mailto:"+order.customer_email} dir="ltr">{order.customer_email}</a>}{order.customer_phone&&<span dir="ltr">{order.customer_phone}</span>}{!order.customer_email&&role!=="kitchen"&&<small>البريد لم يُضف للطلب</small>}</address>{order.channel==="dine_in"&&<p className="restaurantOrderDining">{order.dining_snapshot?.sectionName} · {order.dining_snapshot?.name||"طاولة غير محددة"} · {order.party_size||"—"} أشخاص</p>}<ul>{order.items.map((item,i)=><li key={i}><span className="restaurantItemQuantity">{item.quantity} ×</span><span>{item.name}</span></li>)}</ul><footer><span className="restaurantPaymentBadge" data-status={order.payment_status}>{payments[order.payment_status]}</span>{order.total!==null&&<strong>{order.total.toFixed(2)} <small>ر.س</small></strong>}</footer>{actions(order)}</article>)}</div>:<p className="restaurantEmptyMessage">لا توجد طلبات مطابقة.</p>}
 </section>;
}