"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {operationApi} from "./resource-manager";
import {MerchantIcon} from "./merchant-icon";
import type {MenuGroup} from "@/lib/restaurant/menu";
import MenuChoices,{cartKey,choicePrice,choicesValid,type CartLine} from "./menu-choices";
type Order={id:string;order_number:number;branch_id:string;status:string;payment_status:string;total:number|null;version:number;channel:string;customer_name:string|null;created_at:string;items:{name:string;quantity:number}[]};
const statuses:Record<string,string>={new:"جديد",preparing:"قيد التحضير",ready:"جاهز",completed:"مكتمل",cancelled:"ملغي"};
const payments:Record<string,string>={paid:"مدفوع",unpaid:"غير مدفوع",refunded:"تم رد المبلغ"};
export default function OrderWorkspace({tenantId,module,branch,branches,role,onChanged}:{tenantId:string;module:string;branch:string;branches:{id:string;name:string}[];role:string;onChanged:()=>void}){
 const [orders,setOrders]=useState<Order[]>([]),[menu,setMenu]=useState<{id:string;name:string;status:string;data:{price:number}}[]>([]),[tables,setTables]=useState<{id:string;name:string;status:string}[]>([]),[cart,setCart]=useState<Record<string,CartLine>>({}),[filter,setFilter]=useState("all"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[orderBranch,setOrderBranch]=useState(branch||branches[0]?.id||"");
 const [options,setOptions]=useState<Record<string,MenuGroup[]>>({});
 const scope=module==="pos"?orderBranch:branch;
 const requestRef=useRef<{payload:string;key:string}|null>(null);
 const [selectedOptions,setSelectedOptions]=useState<Record<string,string[]>>({});
 async function refresh(){const data=await operationApi(tenantId,module,"GET",undefined,scope);setOrders(data.orders);setMenu(data.menu??[]);setTables(data.tables??[]);setOptions(data.options??{});}
 useEffect(()=>{let alive=true;const load=()=>operationApi(tenantId,module,"GET",undefined,scope).then(data=>{if(alive){setOrders(data.orders);setMenu(data.menu??[]);setTables(data.tables??[]);setOptions(data.options??{});setLoading(false);}}).catch(error=>{if(alive){setLoading(false);setMessage(String(error.message));}});void load();const timer=setInterval(()=>void load(),15000);return()=>{alive=false;clearInterval(timer);};},[tenantId,module,scope]);
 async function update(order:Order,change:{status?:string;paymentStatus?:string}){if(busy)return;setBusy(true);try{await operationApi(tenantId,module,"PATCH",{id:order.id,version:order.version,...change});await refresh();onChanged();setMessage("تم تحديث الطلب.");}catch(error){setMessage(error instanceof Error?error.message:"تعذر التحديث.");}finally{setBusy(false);}}
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const f=new FormData(event.currentTarget);setBusy(true);try{const payload={branchId:f.get("branchId"),channel:f.get("channel"),tableId:f.get("tableId")||null,customerName:f.get("customerName"),customerPhone:f.get("customerPhone"),couponCode:f.get("couponCode")||null,items:Object.values(cart).filter(line=>line.quantity>0).map(line=>({id:line.itemId,quantity:line.quantity,options:line.options}))};const encoded=JSON.stringify(payload);if(requestRef.current?.payload!==encoded)requestRef.current={payload:encoded,key:crypto.randomUUID()};await operationApi(tenantId,"pos","POST",{...payload,requestKey:requestRef.current.key});requestRef.current=null;setCart({});await refresh();onChanged();setMessage("تم إنشاء الطلب. الأسعار والإجمالي حُسبت من المنيو المحفوظ.");}catch(error){setMessage(error instanceof Error?error.message:"تعذر إنشاء الطلب.");}finally{setBusy(false);}}
 function actions(order:Order){
  const next:Record<string,string>={new:"preparing",preparing:"ready",ready:"completed"};
  const canAdvance=["owner","manager","cashier"].includes(role)||role==="kitchen"&&["new","preparing"].includes(order.status)||["waiter","driver"].includes(role)&&order.status==="ready";
  return <div className="restaurantOrderActions">{canAdvance&&next[order.status]&&<button disabled={busy} onClick={()=>void update(order,{status:next[order.status]})}>نقل إلى {statuses[next[order.status]]}</button>}{["owner","manager","cashier"].includes(role)&&order.status!=="cancelled"&&<>{order.payment_status==="unpaid"?<button disabled={busy} onClick={()=>void update(order,{paymentStatus:"paid"})}>تسجيل دفع يدوي</button>:order.payment_status==="paid"?<button disabled={busy} onClick={()=>void update(order,{paymentStatus:"refunded"})}>تسجيل رد المبلغ</button>:null}{["new","preparing","ready"].includes(order.status)&&order.payment_status!=="paid"&&<button disabled={busy} onClick={()=>void update(order,{status:"cancelled"})}>إلغاء الطلب</button>}</>}</div>;
 }
 const selected=orders.filter(o=>filter==="all"||o.status===filter),sum=Object.values(cart).reduce((total,line)=>total+line.quantity*(Number(menu.find(item=>item.id===line.itemId)?.data.price??0)+choicePrice(options[line.itemId]??[],line.options)),0);
 return <section className="restaurantPanel"><header><div><h3>{module==="pos"?"نقطة البيع":module==="kds"?"شاشة المطبخ":"إدارة الطلبات"}</h3><p>طلبات المطعم من قاعدة البيانات · تحديث تلقائي كل 15 ثانية</p></div><MerchantIcon name={module==="kds"?"chef":"bag"}/></header>{message&&<p className="restaurantNotice" role="status">{message}</p>}
 {module==="pos"&&<form className="restaurantPos" onSubmit={create}><div><h3>الأصناف المتاحة</h3><div className="restaurantPosMenu">{menu.filter(item=>item.status==="active"&&Number(item.data.price)>=0).map(item=><article key={item.id}><b>{item.name}</b><span>{Number(item.data.price).toFixed(2)} ر.س</span><MenuChoices groups={options[item.id]??[]} selected={selectedOptions[item.id]??[]} onChange={ids=>setSelectedOptions(values=>({...values,[item.id]:ids}))}/><button type="button" disabled={!choicesValid(options[item.id]??[],selectedOptions[item.id]??[])} onClick={()=>{const selected=selectedOptions[item.id]??[],key=cartKey(item.id,selected);setCart(v=>({...v,[key]:{itemId:item.id,options:selected,quantity:(v[key]?.quantity??0)+1}}));}}>إضافة إلى الطلب +</button></article>)}</div>{!menu.length&&<p className="restaurantEmptyMessage">أضف أصناف المنيو أولاً لتبدأ البيع.</p>}</div><div className="restaurantResourceForm"><label>الفرع<select name="branchId" required value={orderBranch} onChange={e=>{setOrderBranch(e.target.value);setCart({});}}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>نوع الطلب<select name="channel"><option value="dine_in">داخل المطعم</option><option value="takeaway">سفري</option><option value="delivery">توصيل</option></select></label><label>الطاولة<select name="tableId"><option value="">بدون طاولة</option>{tables.filter(t=>t.status!=="inactive").map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>اسم العميل<input name="customerName" maxLength={180}/></label><label>هاتف العميل<input name="customerPhone" maxLength={40}/></label><label>كود الخصم<input name="couponCode" maxLength={40}/></label><div className="restaurantCart">{Object.entries(cart).filter(([,line])=>line.quantity>0).map(([key,line])=><label key={key}>{menu.find(i=>i.id===line.itemId)?.name}{line.options.length>0&&<small>{(options[line.itemId]??[]).flatMap(g=>g.values).filter(v=>line.options.includes(v.id)).map(v=>v.name).join("، ")}</small>}<input type="number" value={line.quantity} min={0} max={1000} onChange={e=>setCart(v=>({...v,[key]:{...line,quantity:Number(e.target.value)}}))}/></label>)}<strong>الإجمالي قبل الخصم: {sum.toFixed(2)} ر.س</strong></div><button className="restaurantPrimary" disabled={busy||!Object.values(cart).some(line=>line.quantity>0)}>{busy?"جارٍ الحفظ…":"إنشاء الطلب"}</button><p className="restaurantFinePrint">تسجيل الدفع أو رده هنا يوثّق الدفع اليدوي؛ لا ينفّذ عملية على بوابة إلكترونية.</p></div></form>}
 <div className="restaurantStatusFilters">{["all","new","preparing","ready","completed","cancelled"].map(status=><button key={status} aria-pressed={filter===status} onClick={()=>setFilter(status)}>{status==="all"?"الكل":statuses[status]}</button>)}</div>
 {loading?<p>جارٍ تحميل الطلبات…</p>:selected.length?<div className="restaurantOrderCards">{selected.map(order=><article key={order.id}><header><b>#{order.order_number}</b><span>{statuses[order.status]}</span></header><p>{order.customer_name||"ضيف"} · {order.channel==="dine_in"?"داخل المطعم":order.channel==="takeaway"?"سفري":"توصيل"}</p><ul>{order.items.map((item,i)=><li key={i}>{item.quantity} × {item.name}</li>)}</ul><footer><span>{payments[order.payment_status]}</span>{order.total!==null&&<strong>{order.total.toFixed(2)} ر.س</strong>}</footer>{actions(order)}</article>)}</div>:<p className="restaurantEmptyMessage">لا توجد طلبات مطابقة.</p>}
 </section>;
}
