"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- Full-document navigation is required for service-worker offline fallbacks. */
import {useEffect,useRef,useState,type FormEvent} from 'react';

import Image from 'next/image';
import {MerchantIcon} from './merchant-icon';
import MenuChoices,{cartKey,choicePrice,choicesValid} from './menu-choices';
import {operationApi} from './resource-manager';
import {useNetworkStatus} from '../pwa-support';
import {posKey,usePosCart,readSnapshot,saveCart,saveSnapshot,type PosSnapshot,type PosItem,type PosTable} from './pos-storage';
import type {MenuGroup} from '@/lib/restaurant/menu';
import './pos-terminal.css';

export default function PosTerminal({tenantId,actorId,name,branch,branches,onCreated,offlineSnapshot}:{tenantId:string;actorId:string;name:string;branch:string;branches:{id:string;name:string}[];onCreated:()=>void;offlineSnapshot?:PosSnapshot}){
 const connected=useNetworkStatus(),online=connected&&!offlineSnapshot;
 const [chosenBranch,setChosenBranch]=useState(branch||branches[0]?.id||''),[menu,setMenu]=useState<PosItem[]>(offlineSnapshot?.menu||[]),[tables,setTables]=useState<PosTable[]>(offlineSnapshot?.tables||[]),[options,setOptions]=useState<Record<string,MenuGroup[]>>(offlineSnapshot?.options||{}),[categories,setCategories]=useState<{id:string;name:string}[]>(offlineSnapshot?.categories||[]);
 const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[channel,setChannel]=useState('takeaway'),[table,setTable]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(!offlineSnapshot),[message,setMessage]=useState(''),[savedAt,setSavedAt]=useState(offlineSnapshot?.savedAt||'');
 const [editing,setEditing]=useState<PosItem|null>(null),[selection,setSelection]=useState<string[]>([]);
 const choiceDialog=useRef<HTMLDialogElement>(null),searchInput=useRef<HTMLInputElement>(null),request=useRef<{payload:string;key:string}|null>(null);
 const key=posKey(actorId,tenantId,chosenBranch);
 const [cart,setCart]=usePosCart(key);
 
 useEffect(()=>{if(offlineSnapshot)return;let alive=true;const cached=readSnapshot(key);void Promise.resolve(cached).then(value=>{if(!alive)return;setLoading(online);if(value){setMenu(value.menu);setTables(value.tables);setOptions(value.options);setCategories(value.categories);setSavedAt(value.savedAt)}})
  if(!online)return()=>{alive=false};
  void operationApi(tenantId,'pos','GET',undefined,chosenBranch).then(data=>{if(!alive)return;setMenu(data.menu||[]);setTables(data.tables||[]);setOptions(data.options||{});setCategories(data.categories||[]);setLoading(false);const at=new Date().toISOString();setSavedAt(at);saveSnapshot(key,{actorId,tenantId,name,branch:chosenBranch,branches,menu:(data.menu||[]).map((i:PosItem)=>({id:i.id,name:i.name,status:i.status,data:{price:i.data.price,categoryId:i.data.categoryId,imageUrl:i.data.imageUrl}})),tables:data.tables||[],options:data.options||{},categories:data.categories||[],savedAt:at})}).catch(e=>{if(alive){setLoading(false);setMessage(cached?'تعذر تحديث الكتالوج. تُعرض آخر نسخة محفوظة؛ يُراجع النظام الأسعار عند تسجيل الطلب.':String(e.message))}});return()=>{alive=false};
 },[tenantId,actorId,name,chosenBranch,key,online,offlineSnapshot,branches]);
 useEffect(()=>{const el=choiceDialog.current;if(editing&&!el?.open)el?.showModal();if(!editing&&el?.open)el.close()},[editing]);
 useEffect(()=>{const shortcut=(e:KeyboardEvent)=>{if(e.key==='F2'){e.preventDefault();searchInput.current?.focus()}};addEventListener('keydown',shortcut);return()=>removeEventListener('keydown',shortcut)},[]);
 const visible=menu.filter(i=>i.status==='active'&&(!category||i.data.categoryId===category)&&i.name.toLowerCase().includes(search.toLowerCase().trim()));
 const lines=Object.entries(cart).filter(([,line])=>line.quantity>0),count=lines.reduce((n,[,line])=>n+line.quantity,0),total=lines.reduce((n,[,line])=>n+line.quantity*(Number(menu.find(i=>i.id===line.itemId)?.data.price||0)+choicePrice(options[line.itemId]||[],line.options)),0);
 function add(item:PosItem,chosen:string[]=[]){const id=cartKey(item.id,chosen);setCart(v=>({...v,[id]:{itemId:item.id,options:chosen,quantity:Math.min(1000,(v[id]?.quantity||0)+1)}}))}
 function quantity(id:string,value:number){setCart(v=>{const next={...v};if(value<=0)delete next[id];else next[id]={...next[id],quantity:Math.min(1000,value)};return next})}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy||!count)return;if(!online){setMessage(saveCart(key,cart)?'المسودة محفوظة على الجهاز. افتح لوحة المطعم عند عودة الاتصال لمراجعتها وتسجيلها.':'تعذر حفظ المسودة محليًا.');return}const f=new FormData(event.currentTarget);const payload={branchId:chosenBranch,channel,tableId:channel==='dine_in'?table:null,partySize:channel==='dine_in'?Number(f.get('partySize')):null,customerName:f.get('customerName'),customerPhone:f.get('customerPhone'),customerEmail:f.get('customerEmail'),couponCode:f.get('couponCode')||null,items:lines.map(([,line])=>({id:line.itemId,quantity:line.quantity,options:line.options}))};const encoded=JSON.stringify(payload);if(request.current?.payload!==encoded)request.current={payload:encoded,key:crypto.randomUUID()};setBusy(true);try{await operationApi(tenantId,'pos','POST',{...payload,requestKey:request.current.key});request.current=null;setCart({});setMessage('تم إنشاء الطلب. الأسعار والإجمالي حُسبت من المنيو المحفوظ.');onCreated()}catch(e){setMessage(e instanceof Error?e.message:'تعذر تسجيل الطلب. سلتك محفوظة؛ أعد المحاولة.')}finally{setBusy(false)}}
 return <div className="posTerminal" data-online={online}><div className="posSessionBar"><div><span className="posConnection" data-online={online}>{online?'متصل · نقطة البيع':'دون اتصال · مسودة محلية'}</span><small>{savedAt?'آخر مزامنة للكتالوج: '+new Date(savedAt).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'}):'يُحفظ الكتالوج بعد الاتصال بالنظام'}</small></div>{offlineSnapshot?<a href={'/restaurant?tenant='+encodeURIComponent(tenantId)}>مراجعة وإرسال من لوحة المطعم ←</a>:<a href="/offline">فتح نقطة البيع دون اتصال ←</a>}</div>{message&&<p className="restaurantNotice" role="status">{message}</p>}{!online&&<p className="posOfflineNotice">يمكنك تجهيز السلة وحفظ المسودة دون اتصال. أسعار الكتالوج والطاولات من آخر مزامنة؛ لا يُسجّل الطلب أو الدفع في الخادم حتى تعود للشبكة.</p>}
 <div className="posTerminalLayout"><section className="posCatalog"><div className="posCatalogTools"><label className="posSearch"><MerchantIcon name="search"/><input ref={searchInput} type="search" aria-label="البحث في أصناف نقطة البيع" placeholder="ابحث عن صنف… F2" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="posBranch">الفرع<select aria-label="فرع نقطة البيع" value={chosenBranch} disabled={Boolean(offlineSnapshot)||busy} onChange={e=>{setChosenBranch(e.target.value);setTable('');setCategory('');setMenu([]);setTables([]);setOptions({});setCategories([]);request.current=null}}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><nav className="posCategories" aria-label="تصنيفات نقطة البيع"><button type="button" aria-pressed={!category} onClick={()=>setCategory('')}>الكل <small>{menu.filter(i=>i.status==='active').length}</small></button>{categories.map(c=><button type="button" key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</nav><div className="posCatalogHeading"><strong>الأصناف المتاحة</strong><span>{visible.length} صنف</span></div>{loading&&!menu.length?<p>جارٍ تحميل المنيو…</p>:visible.length?<div className="restaurantPosMenu posProductGrid">{visible.map(item=><article key={item.id}><div className="posProductImage">{online&&item.data.imageUrl?<Image src={item.data.imageUrl} alt="" fill unoptimized sizes="(max-width:700px) 45vw,220px"/>:<MerchantIcon name="menu"/>}{cart&&Object.values(cart).some(l=>l.itemId===item.id)&&<span className="posProductCount">{Object.values(cart).filter(l=>l.itemId===item.id).reduce((n,l)=>n+l.quantity,0)}</span>}</div><b>{item.name}</b><footer><span>{Number(item.data.price).toFixed(2)} <small>ر.س</small></span><button type="button" aria-label={'إضافة '+item.name+' إلى الطلب'} disabled={busy} onClick={()=>{if(options[item.id]?.length){setSelection([]);setEditing(item)}else add(item)}}>+</button></footer></article>)}</div>:<div className="posEmptyCatalog"><MerchantIcon name="search"/><strong>{search||category?'لا توجد أصناف مطابقة':'لا يوجد كتالوج محفوظ'}</strong><p>{search||category?'جرّب اسمًا آخر أو اختر جميع التصنيفات.':'اتصل بالنظام مرة واحدة لتهيئة نقطة البيع دون اتصال.'}</p></div>}</section>
 <form className="posTicket" onSubmit={submit}><header><span><small>الطلب الحالي</small><h3>سلة نقطة البيع</h3></span><b>{count} صنف</b></header><div className="posChannels" aria-label="نوع طلب نقطة البيع">{[['takeaway','سفري'],['dine_in','داخل المطعم'],['delivery','توصيل']].map(([id,label])=><button key={id} type="button" aria-pressed={channel===id} disabled={busy} onClick={()=>setChannel(id)}>{label}</button>)}</div>{channel==='dine_in'&&<div className="posDiningFields"><label>الطاولة<select aria-label="طاولة نقطة البيع" required value={table} disabled={busy} onChange={e=>setTable(e.target.value)}><option value="">اختر طاولة مضافة</option>{tables.filter(t=>t.status!=='inactive').map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>عدد الأشخاص<input name="partySize" aria-label="عدد أشخاص نقطة البيع" type="number" required min={1} max={tables.find(t=>t.id===table)?.data.capacity||100} defaultValue={1}/></label></div>}
 {lines.length?<div className="posTicketLines">{lines.map(([id,line])=><div className="posTicketLine" key={id}><div><strong>{menu.find(i=>i.id===line.itemId)?.name||'صنف يحتاج مراجعة'}</strong>{line.options.length>0&&<small>{(options[line.itemId]||[]).flatMap(g=>g.values).filter(v=>line.options.includes(v.id)).map(v=>v.name).join('، ')}</small>}<span>{(line.quantity*(Number(menu.find(i=>i.id===line.itemId)?.data.price||0)+choicePrice(options[line.itemId]||[],line.options))).toFixed(2)} ر.س</span></div><div className="posQuantity"><button type="button" aria-label={'تقليل كمية '+(menu.find(i=>i.id===line.itemId)?.name||'الصنف')} disabled={busy} onClick={()=>quantity(id,line.quantity-1)}>−</button><b>{line.quantity}</b><button type="button" aria-label={'زيادة كمية '+(menu.find(i=>i.id===line.itemId)?.name||'الصنف')} disabled={busy||line.quantity>=1000} onClick={()=>quantity(id,line.quantity+1)}>+</button></div></div>)}</div>:<div className="posEmptyTicket"><MerchantIcon name="bag"/><strong>ابدأ بإضافة الأصناف</strong><p>تظهر هنا الكميات والخيارات وإجمالي الطلب.</p></div>}
 <details className="posGuestFields"><summary>بيانات العميل وكوبون الخصم <span>اختياري</span></summary><label>اسم العميل<input name="customerName" maxLength={180}/></label><label>هاتف العميل<input name="customerPhone" type="tel" dir="ltr" maxLength={40}/></label><label>بريد العميل<input name="customerEmail" type="email" dir="ltr" maxLength={254}/></label><label>كود الخصم<input name="couponCode" maxLength={40}/></label><small>بيانات الاتصال تُرسل مع الطلب عند الاتصال؛ لا تُحفظ في المسودة المحلية.</small></details><footer><div className="posTicketTotal"><span>{online?'الإجمالي قبل الخصم':'الإجمالي التقديري'}</span><strong>{total.toFixed(2)} <small>ر.س</small></strong></div><button className="restaurantPrimary" disabled={busy||!count||!chosenBranch||online&&loading}>{busy?'جارٍ تسجيل الطلب…':online?'إنشاء الطلب':'حفظ المسودة محليًا'}</button><small>{online?'يحسب الخادم الأسعار والخصم عند تسجيل الطلب.':'مسودة محفوظة على هذا الجهاز، وليست طلبًا مؤكدًا.'}</small></footer></form></div>
 <dialog className="posOptionsDialog" ref={choiceDialog} aria-label="خيارات صنف نقطة البيع" onCancel={()=>setEditing(null)}><header><h3>{editing?.name}</h3><button type="button" aria-label="إغلاق خيارات الصنف" onClick={()=>setEditing(null)}>×</button></header>{editing&&<><MenuChoices groups={options[editing.id]||[]} selected={selection} onChange={setSelection}/><footer><strong>{(Number(editing.data.price)+choicePrice(options[editing.id]||[],selection)).toFixed(2)} ر.س</strong><button type="button" className="restaurantPrimary" disabled={!choicesValid(options[editing.id]||[],selection)} onClick={()=>{add(editing,selection);setEditing(null)}}>إضافة إلى الطلب</button></footer></>}</dialog></div>;
}
