"use client";
import {useEffect,useState} from "react";
import {operationApi} from "./resource-manager";
type Reports={daily:{day:string;orders:number;sales:number}[];branches:{name:string;orders:number;sales:number}[];products:{item_name:string;quantity:number;amount:number}[]};
export default function ReportsWorkspace({tenantId,branch,today}:{tenantId:string;branch:string;today:string}){
 const [from,setFrom]=useState(()=>new Date(Date.parse(today+"T00:00:00Z")-6*86400000).toISOString().slice(0,10)),[to,setTo]=useState(today),[data,setData]=useState<Reports|null>(null),[error,setError]=useState("");
 useEffect(()=>{let alive=true;operationApi(tenantId,"reports","GET",undefined,branch,{from,to}).then(result=>{if(alive){setData(result);setError("");}}).catch(e=>{if(alive)setError(String(e.message));});return()=>{alive=false;};},[tenantId,branch,from,to]);
 return <section className="restaurantPanel"><header><div><h3>تقارير المطعم</h3><p>المبيعات المسجّلة وأداء الفروع والأصناف</p></div></header><div className="restaurantResourceForm"><label>من تاريخ<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>إلى تاريخ<input type="date" value={to} min={from} max={today} onChange={e=>setTo(e.target.value)}/></label></div>{error&&<p className="restaurantNotice" role="alert">{error}</p>}{data&&<><div className="restaurantReportSummary"><strong>{data.daily.reduce((sum,d)=>sum+d.sales,0).toFixed(2)} ر.س</strong><span>مبيعات مدفوعة مسجّلة خلال الفترة</span><b>{data.daily.reduce((sum,d)=>sum+Number(d.orders),0)} طلب</b></div><h3>المبيعات اليومية</h3><div className="restaurantResourceList">{data.daily.length?data.daily.map(d=><article key={d.day}><header><b>{d.day}</b><span>{d.orders} طلب</span></header><strong>{d.sales.toFixed(2)} ر.س</strong></article>):<p className="restaurantEmptyMessage">لا توجد طلبات في الفترة المختارة.</p>}</div><h3 className="restaurantReportHeading">أداء الفروع</h3><div className="restaurantResourceList">{data.branches.map(b=><article key={b.name}><header><b>{b.name}</b><span>{b.orders} طلب</span></header><strong>{b.sales.toFixed(2)} ر.س</strong></article>)}</div><h3 className="restaurantReportHeading">الأصناف الأكثر مبيعاً</h3><p className="restaurantFinePrint">قيمة الأصناف قبل خصم الكوبونات.</p><div className="restaurantResourceList">{data.products.map(p=><article key={p.item_name}><header><b>{p.item_name}</b><span>{p.quantity} وحدة</span></header><strong>{p.amount.toFixed(2)} ر.س</strong></article>)}</div></>}</section>;
}
