"use client";
import ReservationSummary from "./reservation-summary";
import {useEffect,useState,type FormEvent} from "react";
import {resourceModules,fieldLabels,type ResourceField} from "@/scripts/restaurant-resource-schema.mjs";
import type {StoredResource} from "@/lib/restaurant/operations";

const resourceActions:Record<string,{add:string;name:string;help:string}>={sections:{add:"إضافة قسم صالة",name:"اسم قسم الصالة",help:"كل قسم يضم طاولاته وله نادل ومشرف، وترتبط به الحجوزات والنداءات والطلبات."},waiterCalls:{add:"تسجيل نداء",name:"اسم الضيف",help:"نداءات الضيوف من المنيو. افتح النداء وحدّث حالته بعد خدمة الطاولة."},categories:{add:"إضافة قسم جديد",name:"اسم القسم",help:"نظّم المنيو إلى أقسام واضحة يسهل على العميل تصفحها."},menu:{add:"إضافة صنف جديد",name:"اسم الصنف",help:"أضف اسم الصنف والسعر والصورة والوصف ليظهر في المنيو."},menuGroups:{add:"إضافة مجموعة خيارات",name:"اسم مجموعة الخيارات",help:"حدّد خيارات الصنف مثل الحجم والإضافات."},menuValues:{add:"إضافة خيار للصنف",name:"اسم الخيار",help:"أضف اختيارًا واضحًا مع فرق السعر إن وجد."},menuImages:{add:"إضافة صورة للصنف",name:"وصف الصورة",help:"اربط صورة بالصنف المناسب في المنيو."},tables:{add:"إضافة طاولة",name:"رقم الطاولة أو اسمها",help:"حدّد الطاولة وسعتها لتظهر في إدارة الصالة."},inventory:{add:"إضافة مادة للمخزون",name:"اسم المادة",help:"تابع الكمية وحد التنبيه لكل مادة."},suppliers:{add:"إضافة مورد",name:"اسم المورد",help:"احفظ بيانات المورد للرجوع إليها عند الشراء."},purchases:{add:"تسجيل عملية شراء",name:"مرجع عملية الشراء",help:"سجّل المادة والمورد والكمية والتكلفة."},team:{add:"إضافة موظف",name:"اسم الموظف",help:"اربط الموظف بحسابه وحدّد صلاحياته."},attendance:{add:"تسجيل الحضور",name:"عنوان سجل الحضور",help:"سجّل حضور الموظف ووقت الانصراف."},coupons:{add:"إنشاء كوبون خصم",name:"اسم العرض",help:"حدّد رمز الخصم وقيمته وفترة صلاحيته."},marketing:{add:"إنشاء حملة تسويقية",name:"اسم الحملة",help:"جهّز رسالة الحملة وقناة الإرسال."},reservations:{add:"إضافة حجز",name:"اسم الضيف",help:"حدّد موعد الحجز وعدد الضيوف والطاولة."},waitlist:{add:"إضافة ضيف للانتظار",name:"اسم الضيف",help:"أضف الضيف وعدد المرافقين إلى قائمة الانتظار."},remote:{add:"إضافة مهمة",name:"عنوان المهمة",help:"حدّد المطلوب والموعد والمسؤول."},remoteWorkers:{add:"إضافة عامل عن بُعد",name:"اسم العامل",help:"اربط العامل بملفه وحدّد مهاراته."},remoteMessages:{add:"إرسال رسالة للمهمة",name:"عنوان الرسالة",help:"أضف رسالة مرتبطة بالمهمة."},remoteDeliveries:{add:"تسجيل تسليم مهمة",name:"عنوان التسليم",help:"وثّق نتيجة المهمة وملاحظات التسليم."},settings:{add:"إضافة إعدادات فرع",name:"اسم الفرع",help:"حدّد مواعيد العمل وبيانات التواصل."}};
export const operationLabels:Record<string,string>={TABLE_NUMBER_EXISTS:"رقم الطاولة موجود في هذا القسم. اختر رقمًا آخر.",BOOKING_CONFLICT:"الطاولة محجوزة في هذا الوقت. اختر طاولة أو موعدًا آخر.",SECTION_TABLE_MISMATCH:"الطاولة لا تتبع القسم المختار.",INVALID_SECTION_STAFF:"اختر نادلًا نشطًا ومشرفًا بدور مدير من موظفي الفرع.",TABLE_CAPACITY_EXCEEDED:"عدد الأشخاص يتجاوز سعة الطاولة.",DINING_DETAILS_REQUIRED:"اختر طاولة موجودة وحدد عدد الأشخاص للطلب داخل المطعم.",SECTION_IN_USE:"القسم أو الطاولة مرتبط بسجلات نشطة. انقلها أو أكملها قبل الأرشفة.",PLAN_FEATURE_REQUIRED:"هذا القسم غير مشمول في الباقة الحالية.",PLAN_LIMIT_REACHED:"وصلت إلى الحد المسموح في الباقة.",FORBIDDEN:"لا تملك صلاحية هذا الإجراء.",CONFLICT:"تغيّرت البيانات. حدّث القائمة ثم أعد المحاولة.",DUPLICATE_RESOURCE:"الرمز أو الحساب مسجّل مسبقاً.",EMPLOYEE_ACCOUNT_NOT_FOUND:"يجب أن يكون الموظف مسجلاً بحساب نشط على FOON.",EMPLOYEE_ACCOUNT_IMMUTABLE:"لا يمكن تغيير الحساب المرتبط بملف الموظف.",REFERENCE_NOT_FOUND:"العنصر المرتبط غير متاح في هذا المطعم أو الفرع.",RECEIVED_PURCHASE_IMMUTABLE:"المشتريات المستلمة محفوظة كسجل ثابت ولا يمكن تعديل كمياتها.",REFUND_REQUIRED:"سجّل رد المبلغ قبل إلغاء طلب مدفوع."};
export async function operationApi(tenantId:string,module:string,method="GET",body?:unknown,branch?:string,extra?:Record<string,string>){
 const query=new URLSearchParams({...extra,...(branch?{branch}:{})}).toString();
 const response=await fetch("/api/restaurant/operations/"+module+(query?"?"+query:""),{method,headers:{"content-type":"application/json","x-foon-tenant":tenantId},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const result=await response.json().catch(()=>({}));
 if(!response.ok)throw Error(operationLabels[result.code]??"تعذر إتمام العملية. راجع البيانات وحاول مجدداً.");
 return result;
}
const allergenChoices=[["banana","موز","Banana","Banane"],["milk","حليب","Milk","Lait"],["cheese","جبن","Cheese","Fromage"],["eggs","بيض","Eggs","Œufs"],["peanuts","فول سوداني","Peanuts","Arachides"],["tree_nuts","مكسرات","Tree nuts","Fruits à coque"],["wheat","قمح / جلوتين","Wheat / gluten","Blé / gluten"],["soy","صويا","Soy","Soja"],["sesame","سمسم","Sesame","Sésame"],["fish","سمك","Fish","Poisson"],["shellfish","محار وقشريات","Shellfish","Crustacés"]] as const;
function displayValue(value:unknown){if(value===null||value===undefined||value==="")return "—";return fieldLabels[String(value)]??String(value);}
export default function ResourceManager({tenantId,module,branch,branches,onChanged,initialResource,initialDate,onlyForm=false}:{tenantId:string;module:string;branch:string;branches:{id:string;name:string}[];onChanged?:()=>void;initialResource?:StoredResource;initialDate?:string;onlyForm?:boolean}){
 const config=resourceModules[module];
 const action=resourceActions[module]??{add:"إضافة "+config.label,name:"الاسم",help:"أدخل البيانات المطلوبة ثم احفظ التغييرات."};
 const [rows,setRows]=useState<StoredResource[]>([]),[refs,setRefs]=useState<Record<string,StoredResource[]>>({}),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState<StoredResource|null>(null),[showForm,setShowForm]=useState(false),[filter,setFilter]=useState("");
 const [sectionFilter,setSectionFilter]=useState(""),[formSection,setFormSection]=useState(String(initialResource?.data.sectionId||""));
 const [uploads,setUploads]=useState<Record<string,string>>({});
 async function upload(key:string,file?:File){if(!file)return;if(file.size>2*1024*1024){setMessage("الحد الأقصى للصورة 2 ميجابايت.");return;}setBusy(true);setMessage("");try{const form=new FormData();form.set("file",file);const r=await fetch("/api/restaurant/assets",{method:"POST",headers:{"x-foon-tenant":tenantId},body:form});const result=await r.json();if(!r.ok)throw Error();setUploads(values=>({...values,[key]:result.url}));setMessage("تم رفع الصورة بنجاح. اضغط حفظ التغييرات لنشر الشعار أو الغلاف في المنيو.");}catch{setMessage("تعذر رفع الصورة. استخدم PNG أو JPEG أو WebP بحجم أقل من 2 ميجابايت.");}finally{setBusy(false);}}
 async function refresh(){const result=await operationApi(tenantId,module,"GET",undefined,branch);setRows(result.resources);setRefs(result.references??{});}
 useEffect(()=>{if(!['waiterCalls','reservations'].includes(module))return;let alive=true;const timer=setInterval(()=>{operationApi(tenantId,module,'GET',undefined,branch).then(result=>{if(alive){setRows(result.resources);setRefs(result.references??{});}}).catch(()=>{});},15000);return()=>{alive=false;clearInterval(timer);};},[tenantId,module,branch]);
 useEffect(()=>{let alive=true;operationApi(tenantId,module,"GET",undefined,branch).then(result=>{if(alive){setRows(result.resources);setRefs(result.references??{});setMessage("");setLoading(false);setShowForm(Boolean(initialResource||initialDate));setEditing(initialResource??null);}}).catch(error=>{if(alive){setMessage(String(error.message));setLoading(false);}});return()=>{alive=false;};},[tenantId,module,branch,initialResource,initialDate]);
 async function save(event:FormEvent<HTMLFormElement>){
  event.preventDefault();if(busy)return;const form=new FormData(event.currentTarget),data:Record<string,unknown>={};
  for(const f of config.fields){const value=String(form.get(f.key)??"").trim();data[f.key]=value===""?null:f.type==="number"?Number(value):f.type==="datetime"?new Date(value).toISOString():value;}
  if(module==="menu")data.allergens=allergenChoices.filter(([key])=>form.getAll("allergenChoice").includes(key)).map(([key])=>key).join(",");
  setBusy(true);setMessage("");
  try{await operationApi(tenantId,module,editing?"PATCH":"POST",{...(editing?{id:editing.id,version:editing.version}:{}),name:form.get("name"),status:form.get("status"),branchId:form.get("branchId")||null,data});await refresh();setShowForm(false);setEditing(null);setMessage("تم حفظ التغييرات بنجاح، ويمكنك مراجعتها في القائمة أدناه.");onChanged?.();}
  catch(error){setMessage(error instanceof Error?error.message:"تعذر الحفظ.");}finally{setBusy(false);}
 }
 async function archive(row:StoredResource){if(busy)return;setBusy(true);setMessage("");try{await operationApi(tenantId,module,"DELETE",{id:row.id,version:row.version});await refresh();setMessage("تمت أرشفة العنصر بنجاح.");onChanged?.();}catch(error){setMessage(error instanceof Error?error.message:"تعذر الحفظ.");}finally{setBusy(false);}}
 function input(f:ResourceField){if(module==="menu"&&f.key==="allergens"){const selected=String(editing?.data.allergens??"").split(",").map(v=>v.trim());return <div role="group" aria-label="مسببات الحساسية" style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,180px),1fr))",gap:8}}>{allergenChoices.map(([key,ar,en,fr])=><label key={key} style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" name="allergenChoice" value={key} defaultChecked={selected.includes(key)||selected.includes(ar)}/><span>{ar} <small style={{display:"block"}}>{en} · {fr}</small></span></label>)}</div>;} const value=uploads[f.key]??editing?.data[f.key]??(f.key==="scheduledAt"?initialDate:f.key==="durationMinutes"?90:null),defaultValue=value==null?"":f.type==="datetime"?new Date(String(value)).toLocaleString("sv-SE").replace(" ","T").slice(0,16):String(value);
  if(f.type==="ref")return <select key={f.key==="tableId"?formSection:f.key} onChange={f.key==="sectionId"?e=>setFormSection(e.target.value):undefined} aria-label={f.label} name={f.key} required={f.required||f.key==="sectionId"&&["tables","reservations","waiterCalls","waitlist"].includes(module)&&Boolean(refs.sections?.length)} defaultValue={defaultValue}><option value="">اختر {f.label}</option>{(refs[f.ref!]??[]).filter(row=>f.key==="waiterId"?row.status==="active"&&row.data.role==="waiter":f.key==="supervisorId"?row.status==="active"&&row.data.role==="manager":f.key==="tableId"?row.status!=="inactive"&&(!formSection||row.data.sectionId===formSection):true).map(row=><option key={row.id} value={row.id}>{f.key==="tableId"?(refs.sections?.find(s=>s.id===row.data.sectionId)?.name||"الصالة الرئيسية")+" · ":""}{row.name}</option>)}</select>;
  if(f.type==="select")return <select aria-label={f.label} name={f.key} required={f.required} defaultValue={defaultValue||f.options?.[0]}>{f.options?.map(value=><option key={value} value={value}>{fieldLabels[value]??value}</option>)}</select>;
  if(f.type==="textarea")return <textarea name={f.key} required={f.required} maxLength={f.maxLength??3000} defaultValue={defaultValue}/>;
  const control=<input key={f.key+"-"+(uploads[f.key]??"")} name={f.key} type={f.type==="datetime"?"datetime-local":f.type==="color"?"color":f.type==="url"?"text":f.type} required={f.required||module==="tables"&&f.key==="number"} min={f.min} max={f.max} step={f.type==="number"?(f.integer?1:"any"):undefined} maxLength={f.maxLength??500} defaultValue={f.type==="color"?defaultValue||"#e76f3c":defaultValue}/>;
  return f.type==="url"?<>{control}<span className="restaurantImageUpload"><input aria-label={"رفع "+f.label} type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>void upload(f.key,e.target.files?.[0])}/><small>PNG أو JPEG أو WebP · حتى 2 ميجابايت · احفظ التغييرات بعد الرفع</small>{defaultValue.startsWith("/api/restaurant/assets/")&&<img src={defaultValue} alt={"معاينة "+f.label} style={{display:"block",width:f.key==="logoUrl"?88:160,height:f.key==="logoUrl"?88:110,objectFit:"contain",borderRadius:10,marginTop:8}}/>}</span></>:control;
 }
 const visible=rows.filter(row=>(!sectionFilter||row.data.sectionId===sectionFilter)&&(row.name+" "+JSON.stringify(row.data)).toLowerCase().includes(filter.toLowerCase()));
 return <section className="restaurantPanel" data-module={module}>{!onlyForm&&<header><div><h3>{config.label}</h3><p>{action.help} · {rows.length} عنصر</p></div><button className="restaurantPrimary" onClick={()=>{setUploads({});setEditing(config.singleton?rows[0]??null:null);setFormSection("");setShowForm(true);setMessage("");}}>{config.singleton?(rows.length?"تعديل الهوية":"إعداد الهوية") :action.add}</button></header>}
 {module==="marketing"&&<p className="restaurantNotice">يمكن حفظ الحملات وجدولتها. الإرسال الخارجي ينتظر ربط مزود القناة وتشغيل عامل الإرسال.</p>}
 {module==="remote"&&<p className="restaurantNotice">ميزانية المهمة للتخطيط فقط. تسجيل المهمة لا ينفّذ تحويلاً مالياً.</p>}
 {module==="team"&&<p className="restaurantFinePrint">ربط الموظف يتطلب بريداً مسجلاً في FOON. الدور المختار يحدد صلاحياته داخل هذا المطعم.</p>}
 {message&&<p role="status" className="restaurantNotice">{message}</p>}
 {showForm&&<form key={module+"-"+(editing?.id??"new")} className="restaurantResourceForm" onSubmit={save}><h3>{editing?"تعديل "+config.label:action.add}</h3><label>{action.name}<input name="name" required maxLength={180} defaultValue={editing?.name??(config.singleton?"هوية المطعم":"")}/></label><label>الحالة<select aria-label="الحالة" name="status" defaultValue={editing?.status??config.statuses[0]}>{config.statuses.map(status=><option key={status} value={status}>{fieldLabels[status]??status}</option>)}</select></label><label>الفرع<select name="branchId" defaultValue={editing?.branch_id??branch}><option value="">المطعم بالكامل</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{["categories","menu","menuGroups","menuValues"].includes(module)?<><fieldset className="restaurantMenuLanguageFields" style={{border:"1px solid var(--border, #d5d5d5)",borderRadius:12,padding:14,display:"grid",gap:12,minWidth:0}}><legend style={{padding:"0 8px",fontWeight:700}}>اللغات · العربية / English / Français</legend><p className="restaurantFinePrint">العربية هي اللغة الأساسية. أدخل ترجمة الإنجليزية والفرنسية لكل اسم ووصف؛ عند ترك الترجمة فارغة يُعرض النص العربي.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,230px),1fr))",gap:12}}>{config.fields.filter(f=>["nameEn","nameFr","descriptionEn","descriptionFr","nutritionEn","nutritionFr"].includes(f.key)).map(f=><label key={f.key} style={{minWidth:0}}>{f.label}{input(f)}</label>)}</div></fieldset>{config.fields.filter(f=>!["nameEn","nameFr","descriptionEn","descriptionFr","nutritionEn","nutritionFr"].includes(f.key)).map(f=><label key={f.key}>{f.label}{input(f)}</label>)}</>:config.fields.map(f=><label key={f.key}>{f.label}{input(f)}</label>)}<div className="restaurantFormActions"><button className="restaurantPrimary" disabled={busy}>{busy?"جارٍ الحفظ…":"حفظ البيانات"}</button><button className="restaurantOutline" type="button" onClick={()=>setShowForm(false)}>إلغاء</button></div></form>}
 {!onlyForm&&<><div className="restaurantListTools">{refs.sections?.length>0&&<label>قسم الصالة<select value={sectionFilter} onChange={e=>setSectionFilter(e.target.value)}><option value="">كل الأقسام</option>{refs.sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label>بحث<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="ابحث في السجلات"/></label><button className="restaurantOutline" onClick={()=>void refresh().catch(error=>setMessage(String(error.message)))}>تحديث</button></div>
 {loading?<p className="restaurantFinePrint">جارٍ تحميل البيانات…</p>:visible.length?<div className="restaurantResourceList">{visible.map(row=><article key={row.id} data-status={row.status}><header><div><b>{row.name}</b><span className="restaurantStateBadge" data-status={row.status}>{fieldLabels[row.status]??row.status}</span></div><div><button disabled={module==="purchases"&&row.status==="received"} onClick={()=>{setUploads({});setEditing(row);setFormSection(String(row.data.sectionId||""));setShowForm(true);setMessage("");}}>تعديل</button><button disabled={busy} onClick={()=>void archive(row)}>أرشفة</button></div></header>{["menu","menuImages","menuValues","categories"].includes(module)&&<div style={{display:"flex",gap:12,alignItems:"flex-start",flexWrap:"wrap",marginBlock:12}}>{[String(row.data.imageUrl||""),...(module==="menu"?(refs.menuImages??[]).filter(im=>im.data.itemId===row.id).map(im=>String(im.data.imageUrl||"")):[])].filter(Boolean).filter((url,index,arr)=>arr.indexOf(url)===index).slice(0,8).map((url,index)=><img key={url} src={url} alt={"صورة "+(index+1)+" لـ "+row.name} loading="lazy" style={{width:88,height:88,objectFit:"cover",borderRadius:10,border:"1px solid #ddd"}}/>)}<div style={{flex:"1 1 220px",minWidth:0}}><strong>تفاصيل العنصر</strong><dl style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:8}}>{config.fields.filter(f=>!["imageUrl"].includes(f.key)).map(f=><div key={f.key}><dt>{f.label}</dt><dd style={{overflowWrap:"anywhere"}}>{f.type==="ref"?(refs[f.ref!]?.find(x=>x.id===row.data[f.key])?.name??"—"):displayValue(row.data[f.key])}</dd></div>)}</dl></div></div>}{module==="reservations"&&<ReservationSummary row={row} references={refs}/>}{!["menu","menuImages","menuValues","categories","reservations"].includes(module)&&<dl>{config.fields.slice(0,4).map(f=><div key={f.key}><dt>{f.label}</dt><dd>{f.type==="ref"?(refs[f.ref!]?.find(r=>r.id===row.data[f.key])?.name??"—"):f.type==="datetime"&&row.data[f.key]?new Date(String(row.data[f.key])).toLocaleString("ar-SA",{timeZone:"Asia/Riyadh"}):displayValue(row.data[f.key])}</dd></div>)}</dl>}</article>)}</div>:<p className="restaurantEmptyMessage">لا توجد سجلات مطابقة. ابدأ بإضافة أول سجل.</p>}
 </>}
 </section>;
}
