"use client";
import {useEffect,useState,type FormEvent} from "react";
type Key="site_name_ar"|"site_name_en"|"site_name_fr"|"support_email"|"contact_phone"|"default_locale";
type Settings=Record<Key,string>;
type SmtpInfo={configured:boolean;host:string;port:number;secure:boolean;user:string;from:string;fromName:string;passwordSet:boolean;source:string};
const initial:Settings={site_name_ar:"",site_name_en:"",site_name_fr:"",support_email:"",contact_phone:"",default_locale:"ar"};
const fields:[Key,string][]=[["site_name_ar","اسم المنصة بالعربية"],["site_name_en","اسم المنصة بالإنجليزية"],["site_name_fr","اسم المنصة بالفرنسية"],["support_email","بريد الدعم"],["contact_phone","رقم التواصل"]];
export default function SettingsEditor({canEdit}:{canEdit:boolean}){
 const [values,setValues]=useState<Settings>(initial),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const [smtp,setSmtp]=useState<SmtpInfo|null>(null),[smtpError,setSmtpError]=useState("");
 useEffect(()=>{let active=true;fetch("/api/admin/smtp").then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.code||r.status);if(active)setSmtp(j)}).catch(e=>{if(active)setSmtpError(String(e))});return()=>{active=false}},[]);
 useEffect(()=>{let active=true;fetch("/api/admin/settings").then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.code);if(active)setValues({...initial,...j.settings});}).catch(e=>{if(active)setMessage("تعذر التحميل: "+String(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");try{const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(values)});const j=await r.json();if(!r.ok)throw Error(j.code);setMessage("تم حفظ إعدادات المنصة وتسجيل العملية.");}catch(e){setMessage("تعذر الحفظ: "+String(e));}finally{setSaving(false);}}
 return <><section className="adminPanel adminOperationsPanel"><h2>الهوية والتواصل</h2><p className="adminOpsLead">الإعدادات محفوظة في قاعدة البيانات، ولا تُنشر تلقائيًا على الواجهة العامة حتى ربطها.</p>{loading?<p>جارٍ تحميل الإعدادات…</p>:<form className="adminOpsForm" onSubmit={submit}>{fields.map(([key,label])=><label key={key}>{label}<input dir={key==="site_name_ar"?"rtl":"ltr"} type={key==="support_email"?"email":"text"} value={values[key]} maxLength={200} readOnly={!canEdit} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>)}<label>اللغة الافتراضية<select disabled={!canEdit} value={values.default_locale} onChange={e=>setValues(v=>({...v,default_locale:e.target.value}))}><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option></select></label>{canEdit&&<button className="adminOpsSubmit" disabled={saving}>{saving?"جارٍ الحفظ…":"حفظ الإعدادات"}</button>}</form>}{message&&<p role="status" className="adminOpsMessage">{message}</p>}</section><section className="adminPanel adminOperationsPanel" aria-label="إعدادات البريد SMTP"><h2>إعدادات البريد الإلكتروني SMTP</h2><p className="adminOpsLead">إعدادات الاتصال تُقرأ بأمان من متغيرات خادم Hostinger. لا توجد وظيفة اختبار أو إرسال رسالة تجريبية.</p>{smtpError?<p className="adminOpsMessage" role="alert">تعذر قراءة إعدادات البريد: {smtpError}</p>:!smtp?<p>جارٍ تحميل حالة البريد…</p>:<><p role="status" className="adminOpsMessage">{smtp.configured?"كلمة مرور SMTP مهيأة في الخادم (الاتصال والتسليم غير مفحوصين).":"البريد غير مهيأ: أضف SMTP_PASSWORD في متغيرات بيئة Hostinger."}</p><div className="adminOpsForm"><label>خادم SMTP<input readOnly dir="ltr" value={smtp.host}/></label><label>المنفذ<input readOnly dir="ltr" value={smtp.port}/></label><label>نوع الاتصال<input readOnly dir="ltr" value={smtp.secure?"SSL/TLS":"غير مشفر"}/></label><label>اسم مستخدم البريد<input readOnly dir="ltr" value={smtp.user}/></label><label>بريد المرسل<input readOnly dir="ltr" value={smtp.from}/></label><label>اسم المرسل<input readOnly value={smtp.fromName}/></label><label>كلمة مرور SMTP<input readOnly type="text" value={smtp.passwordSet?"•••••••• (محفوظة على الخادم)":"غير مهيأة"}/></label></div><p className="adminOpsLead">للتعديل: افتح Hostinger ← إعدادات تطبيق Node.js ← متغيرات البيئة، واضبط SMTP_HOST وSMTP_USER وSMTP_FROM وSMTP_FROM_NAME وSMTP_PASSWORD، ثم أعد تشغيل التطبيق. لا تُدخل كلمة المرور في حقول الموقع العامة.</p></>}</section></>;
}
