"use client";
import {useEffect,useState} from "react";
type Setting={account_type:string;max_files:number;max_storage_mb:number;max_file_mb:number;enabled:number};
const labels:Record<string,string>={customer:"العملاء",owner:"أصحاب الأنشطة",manager:"مديرو الأنشطة",staff:"الموظفون",admin:"إدارة المنصة"};
export default function MediaSettings(){const [rows,setRows]=useState<Setting[]>([]),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/admin/media-settings").then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setRows(d.settings)).catch(()=>setMessage("تعذر تحميل إعدادات مكتبة الصور. تحقق من ترحيل القاعدة."))},[]);
 function change(type:string,key:keyof Setting,value:number|string){setRows(old=>old.map(row=>row.account_type===type?{...row,[key]:value}:row))}
 async function save(row:Setting){setBusy(row.account_type);setMessage("");try{const r=await fetch("/api/admin/media-settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({accountType:row.account_type,maxFiles:Number(row.max_files),maxStorageMb:Number(row.max_storage_mb),maxFileMb:Number(row.max_file_mb),enabled:Boolean(row.enabled)})});if(!r.ok)throw Error();setMessage("تم حفظ إعدادات "+labels[row.account_type])}catch{setMessage("تعذر حفظ الإعدادات. راجع القيم وحاول مجددًا.")}finally{setBusy("")}}
 return <section className="adminPanel"><p>يمكن تعديل الحدود لكل فئة دون التأثير في ملفات المستخدمين المحفوظة.</p>{message&&<p role="status">{message}</p>}<div style={{display:"grid",gap:14}}>{rows.map(row=><form key={row.account_type} onSubmit={e=>{e.preventDefault();void save(row)}} style={{display:"grid",gap:12,padding:16,border:"1px solid #d8c9aa",borderRadius:14}}><h2>{labels[row.account_type]??row.account_type}</h2><label>عدد الصور المسموح<input type="number" min={1} max={10000} required value={row.max_files} onChange={e=>change(row.account_type,"max_files",Number(e.target.value))}/></label><label>المساحة الإجمالية (ميجابايت)<input type="number" min={1} max={10000} required value={row.max_storage_mb} onChange={e=>change(row.account_type,"max_storage_mb",Number(e.target.value))}/></label><label>أقصى حجم للصورة (ميجابايت)<input type="number" min={1} max={10} required value={row.max_file_mb} onChange={e=>change(row.account_type,"max_file_mb",Number(e.target.value))}/></label><label><input type="checkbox" checked={Boolean(row.enabled)} onChange={e=>change(row.account_type,"enabled",e.target.checked?1:0)}/> تفعيل المكتبة</label><button className="restaurantPrimary" disabled={!!busy}>{busy===row.account_type?"جارٍ الحفظ…":"حفظ إعدادات الفئة"}</button></form>)}</div></section>}
