"use client";
import {useEffect,useState} from "react";
type Setting={branch_id:string|null;provider:string;enabled:number|boolean;currency:string;merchant_reference:string|null;public_key:string|null};
const providers=[["manual","كاش / دفع نقدي (اختبار)"],["moyasar","Moyasar"],["tap","Tap"],["hyperpay","HyperPay"],["stripe","Stripe"],["custom","مزود آخر"]];
export default function PaymentEditor({tenantId,canEdit,branches}:{tenantId:string;canEdit:boolean;branches:{id:string;name:string}[]}){
 const [scope,setScope]=useState(""),[all,setAll]=useState<Setting[]>([]),[provider,setProvider]=useState("manual"),[enabled,setEnabled]=useState(true),[currency,setCurrency]=useState("SAR"),[reference,setReference]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;fetch("/api/restaurant/payments/settings",{headers:{"x-foon-tenant":tenantId}}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.code);if(active){setAll(j.settings??[]);const found=(j.settings as Setting[] | undefined ?? []).find((s:Setting)=>s.branch_id===null);setProvider(found?.provider??"manual");setEnabled(Boolean(found?.enabled??true));setCurrency(found?.currency??"SAR");setReference(found?.merchant_reference??"CASH");}}).catch(e=>{if(active)setMessage("تعذر تحميل الإعدادات: "+String(e));});return()=>{active=false;};},[tenantId]);
 function changeScope(v:string,items=all){setScope(v);const found=items.find(s=>(s.branch_id??"")===v);setProvider(found?.provider??"manual");setEnabled(Boolean(found?.enabled));setCurrency(found?.currency??"SAR");setReference(found?.merchant_reference??"");}
 async function save(){setBusy(true);setMessage("");try{const r=await fetch("/api/restaurant/payments/settings",{method:"PUT",headers:{"content-type":"application/json","x-foon-tenant":tenantId},body:JSON.stringify({branch_id:scope||null,provider,enabled,currency,merchant_reference:reference,public_key:""})});const j=await r.json();if(!r.ok)throw Error(j.code);const q=await fetch("/api/restaurant/payments/settings",{headers:{"x-foon-tenant":tenantId}});const data=await q.json();if(!q.ok)throw Error(data.code);setAll(data.settings??[]);setMessage("حُفظت إعدادات المنشأة بنجاح.");}catch(e){setMessage("تعذر الحفظ: "+String(e));}finally{setBusy(false);}}
 return <section className="adminPanel merchantPaymentEditor"><h2>الدفع النقدي التجريبي</h2><p>إعدادات عامة للمنشأة أو إعداد مستقل لفرع محدد. لا تُستخدم مفاتيح منشأة أخرى.</p><label>نطاق الإعداد<select value={scope} onChange={e=>changeScope(e.target.value)}><option value="">المنشأة بالكامل</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>مزود الدفع<select value={provider} disabled={!canEdit} onChange={e=>{setProvider(e.target.value);setEnabled(false);}}>{providers.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>العملة<input value={currency} maxLength={3} disabled={!canEdit} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label><label>مرجع وسيلة الدفع (مثال CASH)<input value={reference} maxLength={120} disabled={!canEdit} onChange={e=>setReference(e.target.value)}/></label><label className="merchantPaymentCheck"><input type="checkbox" checked={enabled} disabled={!canEdit||provider!=="manual"} onChange={e=>setEnabled(e.target.checked)}/> تفعيل الدفع النقدي (يُسجل الطلب غير مدفوع حتى تأكيد الاستلام)</label>{provider!=="manual"&&<p role="note">المزود الإلكتروني غير متصل بعد. لا تدخل مفاتيح سرية هنا، ولا يمكن تفعيله قبل الربط الآمن.</p>}{canEdit&&<button type="button" disabled={busy} onClick={save}>{busy?"جارٍ الحفظ…":"حفظ إعدادات الدفع"}</button>}{message&&<p role="status">{message}</p>}</section>;
}
