"use client";
import {useEffect,useState,type FormEvent} from "react";
type Template={template_key:string;subject_template:string;body_template:string};
const labels:Record<string,string>={subscription_renewal:"تجديد الاشتراك",payment_receipt:"إيصال الدفع",email_verification:"تأكيد البريد",password_reset:"استعادة كلمة المرور"};
export default function EmailTemplates({canEdit}:{canEdit:boolean}){
 const [templates,setTemplates]=useState<Template[]>([]),[key,setKey]=useState("subscription_renewal"),[draft,setDraft]=useState<Template|null>(null),[mail,setMail]=useState<{configured:boolean;from:string;name:string}|null>(null),[ready,setReady]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;fetch("/api/admin/email-templates").then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.code);if(active){setTemplates(j.templates);setDraft(j.templates[0]??null);setKey(j.templates[0]?.template_key??"subscription_renewal");setMail(j.mail);setReady(j.storageReady);}}).catch(()=>{if(active)setMessage("تعذر تحميل إعدادات البريد والقوالب.");});return()=>{active=false;};},[]);
 function choose(value:string){setKey(value);setDraft(templates.find(t=>t.template_key===value)??null);setMessage("");}
 async function save(e:FormEvent){e.preventDefault();if(!draft)return;setBusy(true);setMessage("");try{const r=await fetch("/api/admin/email-templates",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});if(!r.ok)throw Error();setTemplates(v=>v.map(t=>t.template_key===key?draft:t));setMessage("تم حفظ القالب المركزي لجميع المتاجر.");}catch{setMessage("تعذر حفظ القالب. راجع الحقول والمتغيرات.");}finally{setBusy(false);}}
 async function verify(){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/email-templates",{method:"POST"});const j=await r.json();setMessage(r.ok?"اتصال البريد وتسجيل الدخول ناجحان. لم تُرسل رسالة.":j.code==="SMTP_AUTH_FAILED"?"تعذر تسجيل الدخول إلى البريد. راجع كلمة مرور الصندوق.":"تعذر اتصال البريد. راجع إعداداته على Hostinger.");}catch{setMessage("تعذر التحقق من اتصال البريد.");}finally{setBusy(false);}}
 const preview=draft?.body_template.replace(/{{\s*([^}]+?)\s*}}/g,(_,variable)=>({tenant_name:"متجر مثال",message:"تفاصيل العملية الخاصة بهذا المتجر",subject:"رسالة FOON"} as Record<string,string>)[variable]??"");
 return <section className="adminPanel adminOperationsPanel"><h2>البريد المركزي وقوالب الرسائل</h2><p>مرسل واحد لجميع المتاجر: {mail?.name??"FOON"} · <span dir="ltr">{mail?.from??"info@nfoodz.com"}</span></p><p>{mail?.configured?"بيانات اتصال البريد موجودة.":"تحتاج كلمة مرور البريد في إعدادات الموقع."}</p>{canEdit&&<button type="button" disabled={busy} onClick={verify}>التحقق من الاتصال دون إرسال</button>}{!ready&&<p role="status">تخزين القوالب غير جاهز بعد.</p>}{draft&&<form className="adminOpsForm" onSubmit={save}><label>نوع الرسالة<select value={key} onChange={e=>choose(e.target.value)}>{templates.map(t=><option key={t.template_key} value={t.template_key}>{labels[t.template_key]??t.template_key}</option>)}</select></label><label>عنوان الرسالة<input maxLength={250} required readOnly={!canEdit} value={draft.subject_template} onChange={e=>setDraft({...draft,subject_template:e.target.value})}/></label><label>نص الرسالة<textarea rows={8} maxLength={10000} required readOnly={!canEdit} value={draft.body_template} onChange={e=>setDraft({...draft,body_template:e.target.value})}/></label><p>اسم المتجر: {"{{tenant_name}}"} · تفاصيل العملية: {"{{message}}"} · العنوان الأصلي: {"{{subject}}"}</p>{canEdit&&<button disabled={busy||!ready}>حفظ القالب لجميع المتاجر</button>}</form>}<h3>معاينة النص</h3><div style={{whiteSpace:"pre-line"}}>{preview}</div><p>قوالب التحقق واستعادة كلمة المرور جاهزة للربط بمسارات الحسابات. تشغيل إرسال الطابور يحتاج عامل بريد مجدول.</p>{message&&<p role="status">{message}</p>}</section>;
}
