"use client";
import {useEffect,useState} from "react";
type Rule={event_key:string;enabled:boolean;in_app_enabled:boolean;email_enabled:boolean;sound_enabled:boolean};
const labels:Record<string,string>={order_received:"طلب جديد",order_confirmed:"تأكيد طلب",order_ready:"طلب جاهز",order_cancelled:"إلغاء طلب",reservation_created:"حجز جديد",reservation_cancelled:"إلغاء حجز",waitlist_joined:"دخول قائمة الانتظار",waiter_called:"نداء النادل",subscription_renewal:"تجديد الاشتراك"};
export default function NotificationEditor({canEdit}:{canEdit:boolean}){
 const [rules,setRules]=useState<Rule[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{let live=true;fetch("/api/admin/notifications").then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.code);if(live)setRules(j.events.map((key:string)=>({event_key:key,enabled:true,in_app_enabled:true,email_enabled:false,sound_enabled:true,...j.rules.find((x:Rule)=>x.event_key===key)})));}).catch(e=>{if(live)setMessage("تعذر تحميل القواعد: "+String(e));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 function change(key:string,field:keyof Rule,value:boolean){setRules(v=>v.map(r=>r.event_key===key?{...r,[field]:value}:r));}
 async function save(rule:Rule){setBusy(rule.event_key);setMessage("");try{const r=await fetch("/api/admin/notifications",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(rule)});const j=await r.json();if(!r.ok)throw Error(j.code);setMessage("تم حفظ إعدادات "+(labels[rule.event_key]??rule.event_key));}catch(e){setMessage("تعذر الحفظ: "+String(e));}finally{setBusy("");}}
 return <section className="adminPanel adminOperationsPanel"><h2>قواعد الأحداث وقنوات الإشعار</h2><p>حفظ تفضيلات القنوات فقط. تسليم البريد والإشعارات الفعلية يتطلب ربط مرسل الأحداث وخدمات الإرسال.</p>{loading?<p>جارٍ التحميل…</p>:<div className="adminNotificationGrid">{rules.map(rule=><article className="adminNotificationRule" key={rule.event_key}><strong>{labels[rule.event_key]??rule.event_key}</strong><small dir="ltr">{rule.event_key}</small><div className="adminNotificationToggles">{([["enabled","تفعيل الحدث"],["in_app_enabled","داخل النظام"],["email_enabled","بريد إلكتروني"],["sound_enabled","صوت"]] as const).map(([key,label])=><label key={key}><input type="checkbox" disabled={!canEdit} checked={Boolean(rule[key])} onChange={e=>change(rule.event_key,key,e.target.checked)}/>{label}</label>)}</div>{canEdit&&<button type="button" disabled={!!busy} onClick={()=>save(rule)}>{busy===rule.event_key?"جارٍ الحفظ…":"حفظ إعدادات الحدث"}</button>}</article>)}</div>}{message&&<p role="status">{message}</p>}</section>;
}
