CREATE TABLE IF NOT EXISTS platform_configuration (
 config_key VARCHAR(100) NOT NULL PRIMARY KEY,
 config_value TEXT NOT NULL,
 updated_by VARCHAR(36) NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_platform_config_actor FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
