CREATE TABLE IF NOT EXISTS platform_content_pages (
 id VARCHAR(36) NOT NULL PRIMARY KEY,
 slug VARCHAR(120) NOT NULL UNIQUE,
 title_ar VARCHAR(180) NOT NULL,
 title_en VARCHAR(180) NOT NULL,
 title_fr VARCHAR(180) NOT NULL,
 body_ar MEDIUMTEXT NOT NULL,
 body_en MEDIUMTEXT NOT NULL,
 body_fr MEDIUMTEXT NOT NULL,
 status ENUM('draft','published') NOT NULL DEFAULT 'draft',
 updated_by VARCHAR(36) NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_platform_page_editor FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
