CREATE TABLE IF NOT EXISTS tenant_business_profiles (
 tenant_id VARCHAR(36) NOT NULL PRIMARY KEY,
 activity_code VARCHAR(40) NOT NULL,
 country_code CHAR(2) NOT NULL,
 currency CHAR(3) NOT NULL,
 tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_tenant_business_profiles_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
