CREATE TABLE IF NOT EXISTS user_profiles (
 user_id VARCHAR(36) NOT NULL PRIMARY KEY,
 avatar_image LONGBLOB NULL,
 avatar_mime VARCHAR(32) NULL,
 logo_image LONGBLOB NULL,
 logo_mime VARCHAR(32) NULL,
 cover_image LONGBLOB NULL,
 cover_mime VARCHAR(32) NULL,
 phone VARCHAR(32) NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
