-- Shared multilingual catalog for every tenant activity. Additive; existing restaurant menus stay intact.
CREATE TABLE IF NOT EXISTS catalog_categories (
 id VARCHAR(36) PRIMARY KEY,
 tenant_id VARCHAR(36) NOT NULL,
 parent_id VARCHAR(36) NULL,
 branch_id VARCHAR(36) NULL,
 name_ar VARCHAR(180) NOT NULL,
 name_en VARCHAR(180) NULL,
 name_fr VARCHAR(180) NULL,
 description_ar TEXT NULL,
 description_en TEXT NULL,
 description_fr TEXT NULL,
 image_url VARCHAR(1024) NULL,
 sort_order INT NOT NULL DEFAULT 0,
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 KEY ix_catalog_categories_tenant (tenant_id,enabled,sort_order),
 CONSTRAINT fk_catalog_categories_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
 CONSTRAINT fk_catalog_categories_parent FOREIGN KEY (parent_id) REFERENCES catalog_categories(id) ON DELETE SET NULL,
 CONSTRAINT fk_catalog_categories_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS catalog_products (
 id VARCHAR(36) PRIMARY KEY,
 tenant_id VARCHAR(36) NOT NULL,
 category_id VARCHAR(36) NOT NULL,
 branch_id VARCHAR(36) NULL,
 product_type ENUM('physical','food','service','digital') NOT NULL DEFAULT 'physical',
 sku VARCHAR(100) NULL,
 name_ar VARCHAR(180) NOT NULL,
 name_en VARCHAR(180) NULL,
 name_fr VARCHAR(180) NULL,
 description_ar TEXT NULL,
 description_en TEXT NULL,
 description_fr TEXT NULL,
 price DECIMAL(12,2) NOT NULL DEFAULT 0,
 compare_at_price DECIMAL(12,2) NULL,
 currency CHAR(3) NOT NULL DEFAULT 'SAR',
 stock_quantity DECIMAL(12,3) NULL,
 attributes JSON NULL,
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 sort_order INT NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_catalog_products_sku (tenant_id,sku),
 KEY ix_catalog_products_category (tenant_id,category_id,enabled,sort_order),
 CONSTRAINT fk_catalog_products_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
 CONSTRAINT fk_catalog_products_category FOREIGN KEY (category_id) REFERENCES catalog_categories(id) ON DELETE RESTRICT,
 CONSTRAINT fk_catalog_products_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
 CONSTRAINT ck_catalog_products_price CHECK (price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS catalog_images (
 id VARCHAR(36) PRIMARY KEY,
 tenant_id VARCHAR(36) NOT NULL,
 product_id VARCHAR(36) NOT NULL,
 image_url VARCHAR(1024) NOT NULL,
 alt_ar VARCHAR(250) NULL,
 alt_en VARCHAR(250) NULL,
 alt_fr VARCHAR(250) NULL,
 sort_order INT NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY ix_catalog_images_product (tenant_id,product_id,sort_order),
 CONSTRAINT fk_catalog_images_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
 CONSTRAINT fk_catalog_images_product FOREIGN KEY (product_id) REFERENCES catalog_products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS catalog_option_groups (
 id VARCHAR(36) PRIMARY KEY,
 tenant_id VARCHAR(36) NOT NULL,
 product_id VARCHAR(36) NOT NULL,
 name_ar VARCHAR(180) NOT NULL,
 name_en VARCHAR(180) NULL,
 name_fr VARCHAR(180) NULL,
 selection_type ENUM('single','multiple') NOT NULL DEFAULT 'single',
 required BOOLEAN NOT NULL DEFAULT FALSE,
 min_select INT NOT NULL DEFAULT 0,
 max_select INT NOT NULL DEFAULT 1,
 sort_order INT NOT NULL DEFAULT 0,
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 CONSTRAINT fk_catalog_option_groups_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
 CONSTRAINT fk_catalog_option_groups_product FOREIGN KEY (product_id) REFERENCES catalog_products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS catalog_option_values (
 id VARCHAR(36) PRIMARY KEY,
 tenant_id VARCHAR(36) NOT NULL,
 group_id VARCHAR(36) NOT NULL,
 name_ar VARCHAR(180) NOT NULL,
 name_en VARCHAR(180) NULL,
 name_fr VARCHAR(180) NULL,
 price_delta DECIMAL(12,2) NOT NULL DEFAULT 0,
 image_url VARCHAR(1024) NULL,
 sku VARCHAR(100) NULL,
 stock_quantity DECIMAL(12,3) NULL,
 sort_order INT NOT NULL DEFAULT 0,
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 CONSTRAINT fk_catalog_option_values_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
 CONSTRAINT fk_catalog_option_values_group FOREIGN KEY (group_id) REFERENCES catalog_option_groups(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS catalog_import_jobs (
 id VARCHAR(36) PRIMARY KEY,
 tenant_id VARCHAR(36) NOT NULL,
 actor_user_id VARCHAR(36) NULL,
 source_filename VARCHAR(255) NOT NULL,
 status ENUM('pending','validating','running','completed','failed') NOT NULL DEFAULT 'pending',
 total_rows INT NOT NULL DEFAULT 0,
 processed_rows INT NOT NULL DEFAULT 0,
 created_rows INT NOT NULL DEFAULT 0,
 updated_rows INT NOT NULL DEFAULT 0,
 errors JSON NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 KEY ix_catalog_import_jobs_tenant (tenant_id,created_at),
 CONSTRAINT fk_catalog_import_jobs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
