export type PrintLocale="ar"|"en"|"fr";
export const printLocales={
 ar:{brand:"المطعم",ticket:"تذكرة تحضير",receipt:"إيصال دفع نهائي",orderType:"نوع الطلب",table:"طاولة",orderNumber:"رقم الطلب",orderStatus:"حالة الطلب",payment:"الدفع",date:"التاريخ",section:"القسم",guests:"الضيوف",customer:"العميل",items:"الأصناف",paidAmount:"المبلغ المدفوع",print:"طباعة",notTaxInvoice:"إيصال دفع وليس فاتورة ضريبية معتمدة.",kitchenNote:"تذكرة تشغيلية وليست فاتورة ضريبية.",unknownTable:"غير محددة",new:"جديد",preparing:"قيد التحضير",ready:"جاهز",completed:"مكتمل",cancelled:"ملغي",paid:"مدفوع",unpaid:"غير مدفوع",refunded:"تم رد المبلغ",dine_in:"داخل المطعم",takeaway:"سفري",delivery:"توصيل",pickup:"نقطة استلام",room_service:"خدمة الغرف",hotel_service:"خدمة الفندق",reservation:"حجز مع طلب",preorder:"طلب مسبق"},
 en:{brand:"Restaurant",ticket:"Kitchen ticket",receipt:"Final payment receipt",orderType:"Order type",table:"Table",orderNumber:"Order number",orderStatus:"Order status",payment:"Payment",date:"Date",section:"Section",guests:"Guests",customer:"Customer",items:"Items",paidAmount:"Amount paid",print:"Print",notTaxInvoice:"Payment receipt, not a certified tax invoice.",kitchenNote:"Operational ticket, not a tax invoice.",unknownTable:"Unassigned",new:"New",preparing:"Preparing",ready:"Ready",completed:"Completed",cancelled:"Cancelled",paid:"Paid",unpaid:"Unpaid",refunded:"Refunded",dine_in:"Dine-in",takeaway:"Takeaway",delivery:"Delivery",pickup:"Pickup point",room_service:"Room service",hotel_service:"Hotel service",reservation:"Reservation with order",preorder:"Preorder"},
 fr:{brand:"Restaurant",ticket:"Bon de préparation",receipt:"Reçu de paiement final",orderType:"Type de commande",table:"Table",orderNumber:"Numéro de commande",orderStatus:"Statut de commande",payment:"Paiement",date:"Date",section:"Section",guests:"Convives",customer:"Client",items:"Articles",paidAmount:"Montant payé",print:"Imprimer",notTaxInvoice:"Reçu de paiement, pas une facture fiscale certifiée.",kitchenNote:"Bon opérationnel, pas une facture fiscale.",unknownTable:"Non attribuée",new:"Nouvelle",preparing:"En préparation",ready:"Prête",completed:"Terminée",cancelled:"Annulée",paid:"Payé",unpaid:"Non payé",refunded:"Remboursé",dine_in:"Sur place",takeaway:"À emporter",delivery:"Livraison",pickup:"Point de retrait",room_service:"Service en chambre",hotel_service:"Service hôtelier",reservation:"Réservation avec commande",preorder:"Précommande"}
} as const;
export function resolvePrintLocale(value:string|undefined|null):PrintLocale{
 const normalized=(value??"").toLowerCase().split("-")[0];
 return normalized==="en"||normalized==="fr"?normalized:"ar";
}
