"use client";
import {useSavedPreference} from "@/lib/ui/saved-preference";
import Link from "next/link";
import {useEffect} from "react";
type Language="ar"|"en"|"fr";
type Theme="light"|"dark";
type PageLink={slug:string;title:string};
type Plan={code:string;nameAr:string;nameEn:string;prices:{cycle:string;currency:string;price:number}[]};
const copy={
 ar:{market:"استكشف السوق",nav:"المميزات",how:"كيف تعمل",login:"دخول",start:"ابدأ مجانًا",badge:"منصة FOON للأعمال",title:"كل أعمالك في مكان واحد.",lead:"من واجهة متجرك إلى إدارة الطلبات والفروع وتجربة العملاء — أدوات مترابطة مصممة للنمو.",explore:"اكتشف المميزات",features:"منصة واحدة. إمكانيات أكثر.",featuresText:"نظام مرن للمطاعم والمتاجر والخدمات، يجمع ما تحتاجه في مساحة واضحة.",cards:[["إدارة متكاملة","إدارة الفروع والفريق والتشغيل من لوحة واحدة."],["تجربة عملاء أسرع","واجهات مريحة للجوال لتصفح الخدمات والطلب."],["مرونة وأمان","صلاحيات مستقلة وإدارة منظمة لكل نشاط."]],stepsTitle:"من التسجيل إلى التشغيل",steps:[["أنشئ حسابك","سجل حسابك وابدأ إعداد نشاطك."],["جهّز متجرك","أضف معلومات النشاط والخدمات والفريق."],["انطلق","شارك واجهتك وابدأ استقبال العملاء."]],footer:"منصة تشغيل حديثة للأعمال",customer:"حساب العميل",language:"اللغة",theme:"تبديل المظهر"},
 en:{market:"Explore marketplace",nav:"Features",how:"How it works",login:"Sign in",start:"Get started free",badge:"FOON business platform",title:"Your business. One connected place.",lead:"From your storefront to orders, branches and customer experiences — connected tools designed for growth.",explore:"Explore features",features:"One platform. More possibilities.",featuresText:"A flexible workspace for restaurants, retailers and service businesses.",cards:[["Unified operations","Manage locations, teams and operations in one workspace."],["Faster customer journeys","Mobile-friendly experiences for discovery and ordering."],["Flexible and secure","Organized access and permissions for each business."]],stepsTitle:"From signup to launch",steps:[["Create an account","Sign up and begin setting up your business."],["Set up your store","Add your business details, services and team."],["Go live","Share your storefront and welcome customers."]],footer:"A modern business operating platform",customer:"Customer account",language:"Language",theme:"Toggle appearance"},
 fr:{market:"Explorer le marché",nav:"Fonctionnalités",how:"Comment ça marche",login:"Connexion",start:"Commencer gratuitement",badge:"Plateforme FOON",title:"Votre activité. Un seul espace.",lead:"De votre vitrine aux commandes, établissements et expériences clients — des outils connectés pour grandir.",explore:"Découvrir les fonctions",features:"Une plateforme. Plus de possibilités.",featuresText:"Un espace flexible pour les restaurants, commerces et services.",cards:[["Gestion unifiée","Gérez établissements, équipes et opérations au même endroit."],["Parcours client rapide","Une expérience mobile fluide pour découvrir et commander."],["Souplesse et sécurité","Des accès et autorisations organisés pour chaque activité."]],stepsTitle:"De l'inscription au lancement",steps:[["Créer un compte","Inscrivez-vous et configurez votre activité."],["Préparer votre boutique","Ajoutez vos informations, services et équipe."],["Démarrer","Partagez votre vitrine et accueillez vos clients."]],footer:"Une plateforme moderne pour les entreprises",customer:"Espace client",language:"Langue",theme:"Changer l’apparence"}
} as const;
export default function PublicLanding({pages,plans=[]}:{pages:PageLink[];plans?:Plan[]}){
 const [lang,setLang]=useSavedPreference<Language>("foon-public-lang",["ar","en","fr"],"ar");
 const [theme,setTheme]=useSavedPreference<Theme>("foon-public-theme",["light","dark"],"light",true);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";return()=>{document.documentElement.lang="ar";document.documentElement.dir="rtl"}},[lang]);
 const t=copy[lang];
 const changeLanguage=(next:Language)=>{setLang(next);localStorage.setItem("foon-public-lang",next)};
 const toggleTheme=()=>{const next=theme==="light"?"dark":"light";setTheme(next);localStorage.setItem("foon-public-theme",next)};
 return <main className="foonPublic" data-theme={theme} dir={lang==="ar"?"rtl":"ltr"}>
  <header className="foonPublicHeader"><Link className="foonPublicBrand" href="/" aria-label="FOON home"><span className="foonBrandMark">F</span><span>FOON<small>PLATFORM</small></span></Link><nav aria-label="Main navigation"><Link href="/market">{t.market}</Link><a href="#features">{t.nav}</a>{plans.length>0&&<a href="#plans">{lang==="ar"?"الباقات":lang==="en"?"Plans":"Offres"}</a>}<a href="#how">{t.how}</a></nav><div className="foonPublicControls"><label className="foonLanguageControl"><span className="sr-only">{t.language}</span><select value={lang} onChange={e=>changeLanguage(e.target.value as Language)} aria-label={t.language}><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option></select></label><button className="foonThemeControl" type="button" onClick={toggleTheme} aria-label={t.theme} aria-pressed={theme==="dark"}>{theme==="light"?"☾":"☀"}</button><Link className="foonLogin" href="/login">{t.login}</Link><Link className="foonHeaderCta" href="/register">{t.start}</Link></div></header>
  <section className="foonPublicHero"><div className="foonHeroCopy"><span className="foonEyebrow"><span aria-hidden="true">✦</span> {t.badge}</span><h1>{t.title}</h1><p>{t.lead}</p><div className="foonHeroActions"><Link href="/register" className="foonButtonPrimary">{t.start} <span aria-hidden="true">↗</span></Link><Link href="/market" className="foonButtonOutline">{t.market}</Link><a href="#features" className="foonButtonOutline">{t.explore}</a></div><div className="foonHeroTags"><span>01 / FOON</span><span>✦</span><span>02 / PLATFORM</span></div></div><div className="foonHeroArt" aria-hidden="true"><div className="foonArtOrbit foonArtOrbitOne"/><div className="foonArtOrbit foonArtOrbitTwo"/><div className="foonArtCenter"><span>F</span><small>FOON</small></div><div className="foonArtChip foonArtChipTop">✦</div><div className="foonArtChip foonArtChipBottom">◈</div></div></section>
  <section id="features" className="foonPublicSection"><div className="foonSectionIntro"><span className="foonSectionKicker">01 / PLATFORM</span><h2>{t.features}</h2><p>{t.featuresText}</p></div><div className="foonFeatureGrid">{t.cards.map(([title,body],i)=><article className="foonFeatureCard" key={title}><span className="foonFeatureNumber">0{i+1}</span><span className="foonFeatureIcon" aria-hidden="true">{["◈","✧","◎"][i]}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  {plans.length>0&&<section id="plans" className="foonPublicSection"><div className="foonSectionIntro"><span className="foonSectionKicker">PLANS / FOON</span><h2>{lang==="ar"?"الباقات والأسعار":lang==="en"?"Plans and pricing":"Offres et tarifs"}</h2><p>{lang==="ar"?"الباقات المتاحة حاليًا، والأسعار حسب إعدادات المنصة.":lang==="en"?"Currently enabled plans and their configured prices.":"Offres actives et tarifs configurés."}</p></div><div className="foonFeatureGrid">{plans.map(plan=><article className="foonFeatureCard" key={plan.code}><h3>{lang==="ar"?plan.nameAr:plan.nameEn}</h3>{plan.prices.length?plan.prices.map((price,i)=><p key={i}><strong dir="ltr">{price.price.toFixed(2)} {price.currency}</strong> · {price.cycle==="monthly"?(lang==="ar"?"شهريًا":lang==="en"?"Monthly":"Mensuel"):price.cycle==="yearly"?(lang==="ar"?"سنويًا":lang==="en"?"Yearly":"Annuel"):price.cycle}</p>):<p>{lang==="ar"?"تواصل لمعرفة السعر":lang==="en"?"Contact for pricing":"Prix sur demande"}</p>}<Link className="foonButtonOutline" href="/register">{t.start}</Link></article>)}</div></section>}
  <section id="how" className="foonPublicSection foonHowSection"><div className="foonSectionIntro"><span className="foonSectionKicker">02 / WORKFLOW</span><h2>{t.stepsTitle}</h2></div><div className="foonSteps">{t.steps.map(([title,body],i)=><article key={title}><strong>0{i+1}</strong><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <footer className="foonPublicFooter"><div><strong>FOON</strong><p>{t.footer}</p></div><nav aria-label="Footer"><Link href="/market">{t.market}</Link><Link href="/customer">{t.customer}</Link>{pages.map(p=><Link href={`/p/${encodeURIComponent(p.slug)}`} key={p.slug}>{p.title}</Link>)}</nav><small>© FOON</small></footer>
 </main>
}
