"use client";
import {useEffect,useState,type FormEvent} from "react";
type Page={id?:string;slug:string;title_ar:string;title_en:string;title_fr:string;body_ar:string;body_en:string;body_fr:string;status:"draft"|"published"};
const blank:Page={slug:"",title_ar:"",title_en:"",title_fr:"",body_ar:"",body_en:"",body_fr:"",status:"draft"};
export default function PagesEditor({canEdit}:{canEdit:boolean}){
 const [pages,setPages]=useState<Page[]>([]),[page,setPage]=useState<Page>(blank),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/admin/pages");const j=await r.json();if(!r.ok)throw Error(j.code);setPages(j.pages??[]);}
 useEffect(()=>{let active=true;fetch("/api/admin/pages").then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.code);if(active)setPages(j.pages??[]);}).catch(e=>{if(active)setMessage(String(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/admin/pages",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(page)});const j=await r.json();if(!r.ok)throw Error(j.code);setMessage("تم حفظ الصفحة.");await load();setPage({...page,id:j.id});}catch(e){setMessage("تعذر الحفظ: "+String(e));}finally{setBusy(false);}}
 return <section className="adminPanel adminOperationsPanel"><h2>مكتبة الصفحات</h2>{loading?<p>جارٍ تحميل الصفحات…</p>:<div className="adminOpsGrid">{pages.map(p=><button className="adminOpsCard adminPagePick" type="button" key={p.id} onClick={()=>setPage(p)}><strong>{p.title_ar}</strong><span>/{p.slug}</span><small>{p.status==="published"?"منشورة":"مسودة"}</small></button>)}{canEdit&&<button type="button" className="adminOpsCard adminPagePick" onClick={()=>setPage({...blank})}>+ صفحة جديدة</button>}</div>}
 {canEdit&&<form className="adminOpsForm adminCmsForm" onSubmit={save}><label>رابط الصفحة<input required pattern="[a-z][a-z0-9-]{1,119}" dir="ltr" value={page.slug} onChange={e=>setPage(v=>({...v,slug:e.target.value}))}/></label><label>حالة الصفحة<select value={page.status} onChange={e=>setPage(v=>({...v,status:e.target.value as Page["status"]}))}><option value="draft">مسودة</option><option value="published">منشورة</option></select></label>{(["ar","en","fr"] as const).map(l=><div className="adminCmsLocale" key={l}><h3>{l==="ar"?"العربية":l==="en"?"English":"Français"}</h3><label>عنوان الصفحة<input required minLength={2} maxLength={180} dir={l==="ar"?"rtl":"ltr"} value={page[`title_${l}` as keyof Page]} onChange={e=>setPage(v=>({...v,["title_"+l]:e.target.value}))}/></label><label>محتوى الصفحة<textarea rows={7} dir={l==="ar"?"rtl":"ltr"} value={page[`body_${l}` as keyof Page]} onChange={e=>setPage(v=>({...v,["body_"+l]:e.target.value}))}/></label></div>)}<button className="adminOpsSubmit" disabled={busy}>{busy?"جارٍ الحفظ…":"حفظ الصفحة"}</button></form>}
 {message&&<p className="adminOpsMessage" role="status">{message}</p>}</section>;
}
