"use client";
import {useState} from 'react';
import type {DiningTable,DiningSection} from './menu-services';
export default function DiningPicker({branch,tables,sections=[],booking=false,party=false,language='ar'}:{branch:string;tables:DiningTable[];sections?:DiningSection[];booking?:boolean;party?:boolean;language?:'ar'|'en'|'fr'}){
 const [section,setSection]=useState(''),[table,setTable]=useState('');
 const available=sections.filter(s=>!s.branchId||s.branchId===branch),rows=tables.filter(t=>(!t.branchId||t.branchId===branch)&&(!section||t.sectionId===section)),selected=rows.find(t=>t.id===table);
 const ar=language==='ar',fr=language==='fr';
 return <div className="publicDiningFields">{available.length>0&&<label>{ar?'قسم الصالة':fr?'Espace':'Dining section'}<select name="sectionId" aria-label={ar?'قسم الصالة':'Dining section'} required value={section} onChange={e=>{setSection(e.target.value);setTable('')}}><option value="">{ar?'اختر القسم':fr?'Choisir un espace':'Choose a section'}</option>{available.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label>{ar?'طاولتك':fr?'Votre table':'Your table'}<select name="tableId" aria-label={ar?'طاولتك':'Your table'} required={!booking} value={table} onChange={e=>setTable(e.target.value)}><option value="">{booking?(ar?'يحدد المطعم الطاولة':'Assigned by the restaurant'):(ar?'اختر الطاولة':fr?'Choisir une table':'Choose a table')}</option>{rows.map(t=><option key={t.id} value={t.id}>{t.sectionName?t.sectionName+' · ':''}{t.name}{t.capacity?' · '+t.capacity+(ar?' مقاعد':' seats'):''}</option>)}</select>{!rows.length&&!booking&&<small>{ar?'لا توجد طاولات مضافة لهذا القسم.':'No configured tables in this section.'}</small>}</label>{party&&<label>{ar?'عدد الأشخاص':fr?'Convives':'Party size'}<input aria-label={ar?'عدد الأشخاص':fr?'Convives':'Party size'} name="partySize" type="number" required min={1} max={selected?.capacity??100} defaultValue={booking?2:1}/>{selected?.capacity&&<small>{ar?'السعة القصوى: ':'Maximum capacity: '}{selected.capacity}</small>}</label>}</div>;
}
