"use client";
import {useState,type FormEvent} from "react";
type Lang="ar"|"en"|"fr";
export default function InlineCustomerAuth({slug,language,onSuccess}:{slug:string;language:Lang;onSuccess:()=>void}){
 const [mode,setMode]=useState<"login"|"register"|"recover">("login"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const labels={ar:{title:"أكمل طلبك دون مغادرة المنيو",login:"تسجيل الدخول",register:"إنشاء حساب سريع",recover:"استعادة كلمة المرور",name:"الاسم",email:"البريد الإلكتروني",password:"كلمة المرور",submit:"متابعة الطلب",send:"إرسال رابط الاستعادة",back:"العودة للدخول",error:"تعذر إكمال العملية. راجع بياناتك وحاول مجددًا.",sent:"إذا كان البريد مسجّلًا فستصلك رسالة الاستعادة. يمكنك العودة لإكمال طلبك."},en:{title:"Continue without leaving your cart",login:"Sign in",register:"Quick sign up",recover:"Reset password",name:"Name",email:"Email",password:"Password",submit:"Continue order",send:"Send reset link",back:"Back to sign in",error:"Unable to continue. Check your details and try again.",sent:"If the email is registered, you will receive a reset link. Return here to continue your order."},fr:{title:"Continuez sans quitter votre panier",login:"Connexion",register:"Inscription rapide",recover:"Mot de passe oublié",name:"Nom",email:"E-mail",password:"Mot de passe",submit:"Continuer la commande",send:"Envoyer le lien",back:"Retour à la connexion",error:"Impossible de continuer. Vérifiez vos informations.",sent:"Si l’adresse est enregistrée, un lien sera envoyé. Revenez ici pour continuer votre commande."}}[language];
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setMessage("");const f=new FormData(e.currentTarget);
 try{
  const endpoint=mode==="recover"?"/api/auth/request-password-reset":mode==="register"?"/api/customer/register":"/api/auth/login";
  const body=mode==="recover"?{email:f.get("email")}:mode==="register"?{storeSlug:slug,name:f.get("name"),email:f.get("email"),password:f.get("password")}:{email:f.get("email"),password:f.get("password")};
  const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
  const result=await r.json().catch(()=>({}));
  if(!r.ok){setMessage(labels.error+(result.code?" ("+result.code+")":""));return;}
  if(mode==="recover"){setMessage(labels.sent);return;}
  if(mode==="login"){const join=await fetch("/api/customer/join-store",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({storeSlug:slug})});if(!join.ok){const j=await join.json().catch(()=>({}));setMessage(labels.error+(j.code?" ("+j.code+")":""));return;}}
  onSuccess();
 }catch{setMessage(labels.error)}finally{setBusy(false)}}
 return <section className="publicMenuInlineAuth" aria-label={labels.title}><h3>{labels.title}</h3><div className="publicMenuAuthTabs"><button type="button" aria-pressed={mode==="login"} onClick={()=>{setMode("login");setMessage("")}}>{labels.login}</button><button type="button" aria-pressed={mode==="register"} onClick={()=>{setMode("register");setMessage("")}}>{labels.register}</button></div><form onSubmit={submit}>{mode==="register"&&<label>{labels.name}<input name="name" required minLength={2} maxLength={180} autoComplete="name"/></label>}<label>{labels.email}<input type="email" name="email" required maxLength={254} autoComplete="email" dir="ltr"/></label>{mode!=="recover"&&<label>{labels.password}<input type="password" name="password" required minLength={mode==="register"?9:1} autoComplete={mode==="register"?"new-password":"current-password"} dir="ltr"/></label>}{message&&<p role="status">{message}</p>}<button disabled={busy} type="submit">{busy?"…":mode==="recover"?labels.send:labels.submit}</button></form>{mode==="login"?<button type="button" className="publicMenuAuthTextButton" onClick={()=>{setMode("recover");setMessage("")}}>{labels.recover}</button>:mode==="recover"?<button type="button" className="publicMenuAuthTextButton" onClick={()=>{setMode("login");setMessage("")}}>{labels.back}</button>:null}</section>;
}
