"use client";
import {useEffect,useRef} from 'react';
import Image from 'next/image';
import MenuChoices,{choicePrice,choicesValid} from '../restaurant/menu-choices';
import type {MenuGroup} from '@/lib/restaurant/menu';
export type ProductItem={id:string;name:string;nameEn?:string;nameFr?:string;descriptionEn?:string;descriptionFr?:string;branchId:string|null;categoryId:string|null;price:number;description:string;imageUrl:string|null;allergens:string;oldPrice?:number|null;images?:string[];quantity?:number|null;calories?:number|null;nutrition?:string};
export function ProductPrice({item,groups,selected,language}:{item:ProductItem;groups:MenuGroup[];selected:string[];language:'ar'|'en'|'fr'}){
 const extra=choicePrice(groups,selected),current=item.price+extra,previous=item.oldPrice!=null&&Number.isFinite(item.oldPrice)&&item.oldPrice>item.price?item.oldPrice+extra:null;
 return <div className="publicMenuProductPrice">{previous!==null&&<del aria-label={(language==='ar'?'السعر قبل الخصم':language==='en'?'Before discount':'Avant réduction')+': '+previous.toFixed(2)+' SAR'}>{previous.toFixed(2)} <small>{language==='ar'?'ر.س':'SAR'}</small></del>}<strong aria-label={(language==='ar'?'السعر':language==='en'?'Price':'Prix')+': '+current.toFixed(2)+' SAR'}>{current.toFixed(2)} <small>{language==='ar'?'ر.س':'SAR'}</small></strong></div>;
}
const copy={ar:{close:'إغلاق التفاصيل',details:'تفاصيل الصنف',description:'الوصف',noDescription:'لم يُضف وصف تفصيلي لهذا الصنف.',nutrition:'المعلومات الغذائية',allergens:'مسببات الحساسية',calories:'السعرات الحرارية',quantity:'الكمية المتاحة',options:'خصّص طلبك',choose:'اختر الخيارات المطلوبة لإضافة الصنف.',add:'إضافة إلى السلة',photo:'الصورة',noPhoto:'لم تُضف صورة للصنف بعد.'},en:{close:'Close details',details:'Product details',description:'Description',noDescription:'No detailed description has been added.',nutrition:'Nutrition information',allergens:'Allergens',calories:'Calories',quantity:'Available quantity',options:'Customize your order',choose:'Select the required options to add this item.',add:'Add to cart',photo:'Photo',noPhoto:'No product photo yet.'},fr:{close:'Fermer les détails',details:'Détails du produit',description:'Description',noDescription:'Aucune description détaillée.',nutrition:'Informations nutritionnelles',allergens:'Allergènes',calories:'Calories',quantity:'Quantité disponible',options:'Personnaliser',choose:'Choisissez les options requises.',add:'Ajouter au panier',photo:'Photo',noPhoto:'Aucune photo du produit.'}};
export default function MenuProductDetails({item,groups,selected,onSelection,onAdd,onClose,language,category,activePhoto,onPhoto}:{item:ProductItem|null;groups:MenuGroup[];selected:string[];onSelection:(ids:string[])=>void;onAdd:()=>void;onClose:()=>void;language:'ar'|'en'|'fr';category:string;activePhoto:number;onPhoto:(index:number)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),open=Boolean(item),t=copy[language];
 useEffect(()=>{const el=dialog.current;if(open&&!el?.open)el?.showModal();if(!open&&el?.open)el.close();},[open]);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[open]);
 const name=item?(language==='en'?item.nameEn||item.name:language==='fr'?item.nameFr||item.name:item.name):'',description=item?(language==='en'?item.descriptionEn||item.description:language==='fr'?item.descriptionFr||item.description:item.description):'';
 const photos=item?[...new Set([item.imageUrl,...(item.images??[])].filter((url):url is string=>Boolean(url)))].slice(0,4):[],index=Math.min(activePhoto,Math.max(0,photos.length-1));
 return <dialog ref={dialog} className="publicMenuProductDialog" aria-label={name||t.details} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}>{item&&<><header><div><small>{category||t.details}</small><h2>{name}</h2></div><button type="button" autoFocus aria-label={t.close} onClick={onClose}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button></header><div className="publicMenuProductScroll">{photos.length?<div className="publicMenuProductGallery"><div className="publicMenuProductPhoto"><Image src={photos[index]} alt={name+' · '+t.photo+' '+(index+1)} fill unoptimized sizes="(max-width:700px) 100vw,560px"/><span aria-live="polite">{index+1} / {photos.length}</span></div>{photos.length>1&&<nav aria-label={t.photo}>{photos.map((url,i)=><button key={url} type="button" aria-label={t.photo+' '+(i+1)} aria-pressed={index===i} onClick={()=>onPhoto(i)}><Image src={url} fill unoptimized alt="" sizes="64px"/></button>)}</nav>}</div>:<p className="publicMenuProductNoPhoto">{t.noPhoto}</p>}<section><h3>{t.description}</h3><p>{description||t.noDescription}</p></section>{(item.calories!=null||item.quantity!=null)&&<dl className="publicMenuProductFacts">{item.calories!=null&&<div><dt>{t.calories}</dt><dd>{item.calories} kcal</dd></div>}{item.quantity!=null&&<div><dt>{t.quantity}</dt><dd>{item.quantity}</dd></div>}</dl>}{item.nutrition&&<section><h3>{t.nutrition}</h3><p>{item.nutrition}</p></section>}{item.allergens&&<section className="publicMenuProductAllergens"><h3>{t.allergens}</h3><p>{item.allergens}</p></section>}{groups.length>0&&<section><h3>{t.options}</h3><MenuChoices groups={groups} selected={selected} onChange={onSelection}/>{!choicesValid(groups,selected)&&<p className="publicMenuProductHint">{t.choose}</p>}</section>}</div><footer><ProductPrice item={item} groups={groups} selected={selected} language={language}/><button type="button" disabled={!choicesValid(groups,selected)} onClick={onAdd}>{t.add}<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M3 4h2l3 11h10l3-8H6M10 20h.01M18 20h.01"/></svg></button></footer></>}</dialog>;
}
