"use client";
import "./public-menu.css";
import "./mobile-product-cards.css";
import MenuProductDetails,{ProductPrice,type ProductItem} from "./menu-product-details";
import MenuCover from "./menu-cover";
import DiningPicker from "./dining-picker";
import InlineCustomerAuth from "./inline-customer-auth";
import MenuServiceActions,{MenuIcon,type DiningTable,type DiningSection,type MenuServices} from "./menu-services";
import {useRef,useState,type CSSProperties,type FormEvent} from "react";
import Image from "next/image";
import Link from "next/link";
import {useRouter} from "next/navigation";
import type {MenuGroup} from "@/lib/restaurant/menu";
import {isMenuTemplate,menuTemplates} from "@/lib/restaurant/menu-templates";
import {cartKey,choicePrice,choicesValid,type CartLine} from "../restaurant/menu-choices";
type MenuItem=ProductItem;
export type PublicMenuProps={name:string;slug:string;branding:Record<string,string|number|null>;customerEmail?:string;items:MenuItem[];categories:{id:string;name:string;nameEn?:string;nameFr?:string}[];branches:{id:string;name:string}[];signedIn:boolean;linked:boolean;options:Record<string,MenuGroup[]>;services?:MenuServices;tables?:DiningTable[];sections?:DiningSection[];preview?:boolean};
function contrast(color:string){const parts=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*parts[0]+.7152*parts[1]+.0722*parts[2]>.179?"#111827":"#ffffff";}
export default function PublicMenu({name,slug,branding,customerEmail="",items,categories,branches,signedIn,linked,options,services={waiter:false,reservations:false},tables=[],sections=[],preview=false}:PublicMenuProps){
 const [language,setLanguage]=useState<"ar"|"en"|"fr">("ar");
 const [themeOverride,setThemeOverride]=useState<"dark"|"light"|null>(null);
 const translations={ar:{menu:"القائمة",items:"الأصناف",cart:"السلة",login:"دخول",account:"حساب عميل",orders:"طلباتي",search:"ابحث عن طبقك المفضل…",branch:"الفرع",all:"الكل",add:"إضافة",order:"تسجيل الطلب",type:"نوع الطلب",takeaway:"سفري",dine:"داخل المطعم",delivery:"توصيل",room:"خدمة الغرف",booking:"حجز مع الطلب"},en:{menu:"Menu",items:"Items",cart:"Cart",login:"Login",account:"Customer account",orders:"My orders",search:"Search the menu…",branch:"Branch",all:"All",add:"Add",order:"Place order",type:"Order type",takeaway:"Takeaway",dine:"Dine in",delivery:"Delivery",room:"Room service",booking:"Reservation with order"},fr:{menu:"Menu",items:"Articles",cart:"Panier",login:"Connexion",account:"Compte client",orders:"Mes commandes",search:"Rechercher dans le menu…",branch:"Succursale",all:"Tout",add:"Ajouter",order:"Commander",type:"Type de commande",takeaway:"À emporter",dine:"Sur place",delivery:"Livraison",room:"Service en chambre",booking:"Réservation avec commande"}};
 const t=translations[language];
 const localizedName=(v:{name:string;nameEn?:string;nameFr?:string})=>language==="en"?v.nameEn||v.name:language==="fr"?v.nameFr||v.name:v.name;
 const localizedDescription=(v:MenuItem)=>language==="en"?v.descriptionEn||v.description:language==="fr"?v.descriptionFr||v.description:v.description;
 const router=useRouter(),[category,setCategory]=useState(""),[branch,setBranch]=useState(branches[0]?.id??""),[cart,setCart]=useState<Record<string,CartLine>>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [checkoutAuthenticated,setCheckoutAuthenticated]=useState(false);
 const [orderChannel,setOrderChannel]=useState("takeaway");
 const isLinked=linked||checkoutAuthenticated;
 const categoryDialog=useRef<HTMLDialogElement>(null);
 const qrDialog=useRef<HTMLDialogElement>(null);
 const emptyCartDialog=useRef<HTMLDialogElement>(null);
 const categoryButtons=<>{[{id:"",name:t.all},...categories].map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>{setCategory(c.id);setSearch("");setVisibleLimit(24);categoryDialog.current?.close();document.getElementById('menu-items')?.scrollIntoView({block:'start'});}}><span>{localizedName(c)}</span><small>{items.filter(item=>(!item.branchId||item.branchId===branch)&&(!c.id||item.categoryId===c.id)).length}</small></button>)}</>;
 const requestRef=useRef<{payload:string;key:string}|null>(null);
 const [selectedItem,setSelectedItem]=useState<MenuItem|null>(null);
 const [activePhoto,setActivePhoto]=useState(0);
 const [selectedOptions,setSelectedOptions]=useState<Record<string,string[]>>({});
 const template=isMenuTemplate(branding.menuTheme)?branding.menuTheme:"sufra",templateInfo=menuTemplates.find(t=>t.id===template)!;
 const [search,setSearch]=useState(""),[layout,setLayout]=useState("template"),[visibleLimit,setVisibleLimit]=useState(24);
 const primary=typeof branding.primaryColor==="string"&&/^#[a-f0-9]{6}$/i.test(branding.primaryColor)?branding.primaryColor:templateInfo.accent;
 const style={"--public-brand":primary,"--public-on-brand":contrast(primary),fontFamily:branding.fontPreset==="georgia"?"Georgia,serif":branding.fontPreset==="tahoma"?"Tahoma,sans-serif":"Arial,sans-serif"} as CSSProperties;
 const visible=items.filter(item=>(!item.branchId||item.branchId===branch)&&(!category||item.categoryId===category)&&(localizedName(item)+" "+localizedDescription(item)).toLowerCase().includes(search.toLowerCase().trim())),sum=Object.values(cart).reduce((total,line)=>total+line.quantity*((items.find(item=>item.id===line.itemId)?.price??0)+choicePrice(options[line.itemId]??[],line.options)),0);
 async function join(){if(preview)return;setBusy(true);try{const r=await fetch("/api/customer/stores",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({storeSlug:slug})});if(!r.ok)throw Error();router.refresh();setMessage("تم ربط حسابك بهذا المطعم.");}catch{setMessage("تعذر ربط الحساب بالمتجر.");}finally{setBusy(false);}}
 async function order(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy||preview)return;setBusy(true);setMessage("");const f=new FormData(event.currentTarget);try{const payload={storeSlug:slug,branchId:branch,channel:f.get("channel"),tableId:orderChannel==="dine_in"?f.get("tableId"):null,partySize:orderChannel==="dine_in"?Number(f.get("partySize")):null,customerPhone:f.get("phone"),couponCode:f.get("coupon")||null,items:Object.values(cart).filter(line=>line.quantity>0).map(line=>({id:line.itemId,quantity:line.quantity,options:line.options}))};const encoded=JSON.stringify(payload);if(requestRef.current?.payload!==encoded)requestRef.current={payload:encoded,key:crypto.randomUUID()};const r=await fetch("/api/customer/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,requestKey:requestRef.current.key})});const data=await r.json();if(!r.ok){setMessage(data.code==="STORE_CUSTOMER_REQUIRED"?"اربط حسابك بالمطعم لإكمال الطلب.":data.code==="COUPON_LIMIT_REACHED"||data.code==="COUPON_UNAVAILABLE"?"الكوبون غير متاح حالياً.":"تعذر تسجيل الطلب. راجع الأصناف والكوبون وحاول مجدداً.");return;}requestRef.current=null;setCart({});setMessage("تم تسجيل طلبك. يمكنك متابعة حالته من طلباتي.");}catch{setMessage("تعذر الاتصال بالخادم.");}finally{setBusy(false);}}
 const productImage=(item:MenuItem)=>item.imageUrl||item.images?.[0]||null;
 function openProduct(item:MenuItem){setSelectedItem(item);setActivePhoto(0)}
 function addProduct(item:MenuItem){const selected=selectedOptions[item.id]??[],key=cartKey(item.id,selected);setCart(v=>({...v,[key]:{itemId:item.id,options:selected,quantity:(v[key]?.quantity??0)+1}}))}
 const count=Object.values(cart).reduce((n,line)=>n+line.quantity,0);
 const mode=String(branding.colorMode||"template");
 return <main className={"publicMenu publicMenu-"+template} data-template={template} data-color-mode={themeOverride??mode} data-layout={layout} style={style} dir={language==="ar"?"rtl":"ltr"} lang={language}>
 <header className="publicMenuHeader"><div className="publicMenuHeaderBrand"><button type="button" className="publicMenuCategoryTrigger" aria-label={language==="ar"?"فتح أقسام المنيو":"Open menu categories"} onClick={()=>categoryDialog.current?.showModal()}><MenuIcon kind="menu"/></button><a href="#menu-items" className="publicMenuWordmark">{language==="ar"?"المنيو":"MENU"}</a><h1 className="publicMenuStoreName" title={String(branding.brandName||name)}>{String(branding.brandName||name)}</h1><div className="publicMenuHeaderActions"><MenuServiceActions slug={slug} branch={branch} branches={branches} tables={tables} sections={sections} services={services} authenticated={signedIn||checkoutAuthenticated} linked={isLinked} onAuthenticated={()=>setCheckoutAuthenticated(true)} language={language} mode="waiter" preview={preview}/><button type="button" className="publicMenuThemeToggle" aria-label={language==="ar"?"تبديل الوضع الليلي":"Toggle dark mode"} title={language==="ar"?"الوضع الليلي":"Dark mode"} aria-pressed={(themeOverride??mode)==="dark"||((themeOverride??mode)==="template"&&template==="sufra")} onClick={()=>setThemeOverride(current=>(current??(mode==="template"&&template==="sufra"?"dark":mode))==="dark"?"light":"dark")}>{(themeOverride??mode)==="dark"||((themeOverride??mode)==="template"&&template==="sufra")?"☀":"☾"}</button></div></div><nav aria-label="روابط المطعم"><label><span className="sr-only">{language==="ar"?"اللغة":"Language"}</span><select aria-label="Language / اللغة" value={language} onChange={e=>setLanguage(e.target.value as "ar"|"en"|"fr")}><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option></select></label>{preview?<span className="publicMenuPreviewBadge">معاينة</span>:signedIn?<Link className="publicMenuAccountLink" href="/customer">{t.account}</Link>:<button type="button" className="publicMenuAccountLink" onClick={()=>router.push("/"+slug+"/login")}>{t.account}</button>}{count>0&&<a className="publicMenuCartHeaderLink" href="#menu-cart" aria-label="عرض السلة">{t.cart} <b>{count}</b></a>}</nav></header>
 <MenuCover key={String(branding.coverUrl||"empty-cover")} url={branding.coverUrl?String(branding.coverUrl):null} language={language}/>
 <section className="publicMenuIntro"><div className="publicMenuIntroText"><h2>{language==="ar"?"اختر ما يناسب ذوقك وجهّز طلبك":language==="en"?"Pick your favorites and prepare your order":"Choisissez vos favoris et préparez votre commande"}</h2><p>{language==="ar"?"تصفح الأصناف وأضف ما تحب إلى السلة.":language==="en"?"Explore the menu and add your favorites to the cart.":"Découvrez le menu et ajoutez vos favoris au panier."}</p></div>
 <div className="publicMenuInfoBar"><div className="publicMenuServicePosition"><MenuServiceActions slug={slug} branch={branch} branches={branches} tables={tables} sections={sections} services={services} authenticated={signedIn||checkoutAuthenticated} linked={isLinked} onAuthenticated={()=>setCheckoutAuthenticated(true)} language={language} mode="reservation" customerEmail={customerEmail} preview={preview}/></div><div className="publicMenuBusinessStatus">{["open","closed"].includes(String(branding.openStatus||"").toLowerCase())&&<span className="publicMenuOpenBadge">{String(branding.openStatus||"").toLowerCase()==="open"?(language==="ar"?"مفتوح":language==="en"?"Open":"Ouvert"):String(branding.openStatus||"").toLowerCase()==="closed"?(language==="ar"?"مغلق":language==="en"?"Closed":"Fermé") :""}</span>}<details className="publicMenuBusinessDetails"><summary aria-label={language==="ar"?"أوقات العمل والموقع":language==="en"?"Hours and location":"Horaires et adresse"} title={language==="ar"?"أوقات العمل والموقع":"Hours and location"}><span aria-hidden="true">◷</span></summary><div className="publicMenuBusinessPanel"><h3>{language==="ar"?"معلومات المنشأة":"Business information"}</h3><p><strong>{language==="ar"?"أوقات العمل: ":"Opening hours: "}</strong>{String(branding.openingHours||branding.businessHours||branding.hours|| (language==="ar"?"لم تُحدد بعد":"Not provided"))}</p><p><strong>{language==="ar"?"العنوان: ":"Address: "}</strong>{String(branding.address|| (language==="ar"?"لم يُضف العنوان بعد":"Not provided"))}</p>{branding.phone&&<p><strong>{language==="ar"?"الهاتف: ":"Phone: "}</strong><a href={"tel:"+String(branding.phone)} dir="ltr">{String(branding.phone)}</a></p>}{branding.address&&<a target="_blank" rel="noopener noreferrer" href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(String(branding.address))}>{language==="ar"?"عرض الموقع على الخريطة":"View on map"}</a>}</div></details></div></div></section>
 <div className="publicMenuToolbar"><div className="publicMenuSearch"><span aria-hidden="true">⌕</span><input aria-label="البحث في المنيو" placeholder={t.search} type="search" enterKeyHint="search" value={search} onChange={e=>{setSearch(e.target.value);setVisibleLimit(24)}}/></div>{branches.length>1&&<label className="publicMenuBranch">{t.branch}<select aria-label="فرع المطعم" value={branch} onChange={e=>{setBranch(e.target.value);setVisibleLimit(24);setCart({});}}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}<div className="publicMenuViewToggle" role="group" aria-label="طريقة عرض المنيو"><button aria-pressed={layout==="template"} onClick={()=>setLayout("template")}>القالب</button><button aria-pressed={layout==="grid"} onClick={()=>setLayout("grid")}>شبكة</button><button aria-pressed={layout==="list"} onClick={()=>setLayout("list")}>قائمة</button></div></div>
 <div className="publicMenuCatalog"><div className="publicMenuQuickNav" aria-label={language==="ar"?"انتقال سريع بين الأقسام":"Quick category navigation"}><span>{language==="ar"?"الأقسام":"Categories"} · {categories.length}</span><select aria-label={language==="ar"?"انتقل إلى قسم":"Jump to category"} value={category} onChange={e=>{setCategory(e.target.value);setSearch("");setVisibleLimit(24);document.getElementById("menu-items")?.scrollIntoView({block:"start",behavior:"smooth"})}}><option value="">{t.all} ({items.filter(item=>!item.branchId||item.branchId===branch).length})</option>{categories.map(c=><option key={c.id} value={c.id}>{localizedName(c)} ({items.filter(item=>(!item.branchId||item.branchId===branch)&&item.categoryId===c.id).length})</option>)}</select></div><aside className="publicMenuCategoryRail"><span className="publicMenuEyebrow">{language==="ar"?"اكتشف القائمة":language==="en"?"EXPLORE THE MENU":"EXPLORER LE MENU"}</span><nav className="publicMenuCategories" aria-label="تصنيفات المنيو">{categoryButtons}</nav></aside><div className="publicMenuCatalogContent">
 {message&&<p role="status" className="publicMenuMessage">{message}</p>}
 <div className="publicMenuSectionTitle" id="menu-items"><div><span className="publicMenuEyebrow">EXPLORE / اكتشف</span><h2>{categories.find(c=>c.id===category)?.name||"من قائمة المطعم"}</h2></div><span>{visible.length} صنف متاح</span></div>
 <div className="publicMenuLayout"><section className="publicMenuItems" aria-label="أصناف المنيو">{visible.length?visible.slice(0,visibleLimit).map(item=><article key={item.id} className="publicMenuItem"><div className="publicMenuItemBody"><small className="publicMenuItemCategory">{localizedName(categories.find(c=>c.id===item.categoryId)??{name:''})}</small><h2>{localizedName(item)}</h2><p className="publicMenuItemSummary">{localizedDescription(item)}</p></div><button type="button" className={"publicMenuItemImage"+(!productImage(item)?" publicMenuNoImage":"")} aria-label={"تفاصيل "+localizedName(item)} onClick={()=>openProduct(item)}>{productImage(item)?<Image src={productImage(item)!} fill unoptimized alt={localizedName(item)} sizes="(max-width:700px) 25vw,400px"/>:<svg width="32" height="32" viewBox="0 0 48 48" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M8 30h32M11 30a13 13 0 0 1 26 0M22 12h4M6 35h36"/></svg>}</button><footer className="publicMenuItemFooter"><ProductPrice item={item} groups={options[item.id]??[]} selected={selectedOptions[item.id]??[]} language={language}/><button type="button" className="publicMenuCardCart" aria-label={"إضافة "+localizedName(item)+" إلى السلة"} onClick={()=>{if(!choicesValid(options[item.id]??[],selectedOptions[item.id]??[])){openProduct(item);return}addProduct(item)}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M3 4h2l3 11h10l3-8H6M10 20h.01M18 20h.01"/></svg><span>{t.add}</span></button></footer></article>):<div className="publicMenuEmpty"><span aria-hidden="true">✳</span><h3>{search||category?"لا توجد أصناف مطابقة":"المنيو قيد التجهيز"}</h3><p>{search||category?"جرّب كلمة بحث أو تصنيفًا آخر.":"ستظهر أصناف المطعم هنا بعد نشرها."}</p></div>}{visible.length>visibleLimit&&<div className="publicMenuLoadMore"><button type="button" onClick={()=>setVisibleLimit(n=>n+24)}>{language==="ar"?"عرض المزيد من الأصناف":language==="en"?"Show more items":"Afficher plus d’articles"} ({Math.min(visibleLimit,visible.length)} / {visible.length})</button></div>}</section>
 {count>0&&<aside className="publicMenuCart" id="menu-cart"><header><div><small>YOUR ORDER</small><h2>سلة طلبك</h2></div><b>{count}</b></header>{count===0&&<p className="publicMenuCartEmpty">أضف ما تحب من القائمة لتجهيز طلبك.</p>}{Object.entries(cart).filter(([,line])=>line.quantity>0).map(([key,line])=><label key={key}><span>{items.find(item=>item.id===line.itemId)?.name}{line.options.length>0&&<small>{(options[line.itemId]??[]).flatMap(g=>g.values).filter(v=>line.options.includes(v.id)).map(v=>v.name).join("، ")}</small>}</span><input aria-label={"كمية "+items.find(item=>item.id===line.itemId)?.name} type="number" min={0} max={1000} value={line.quantity} onChange={e=>setCart(v=>({...v,[key]:{...line,quantity:Number(e.target.value)}}))}/></label>)}<div className="publicMenuCartTotal"><span>الإجمالي قبل الخصم</span><strong>{sum.toFixed(2)} ر.س</strong></div>{preview?<p className="publicMenuPreviewBadge">معاينة التصميم فقط</p>:isLinked?<form onSubmit={order}><label>{t.type}<select aria-label={t.type} name="channel" value={orderChannel} onChange={e=>setOrderChannel(e.target.value)}><option value="takeaway">{t.takeaway}</option><option value="dine_in">{t.dine}</option><option value="delivery">{t.delivery}</option></select></label>{orderChannel==="dine_in"&&<DiningPicker key={branch} branch={branch} tables={tables} sections={sections} party language={language}/>}<label>رقم التواصل (من بيانات حسابك، اختياري)<input name="phone" maxLength={40} autoComplete="tel" placeholder="يُستخدم الرقم المحفوظ في حسابك تلقائيًا"/></label><label>كوبون الخصم<input name="coupon" maxLength={40}/></label><button disabled={busy||!Object.values(cart).some(line=>line.quantity>0)}>{busy?"جارٍ التسجيل…":"تسجيل الطلب"}</button><small>تسجيل الطلب لا يخصم مبلغًا إلكترونيًا. اتفق على الدفع مع المطعم.</small></form>:signedIn?<button disabled={busy} onClick={()=>void join()}>متابعة كعميل لهذا المطعم</button>:<InlineCustomerAuth slug={slug} language={language} onSuccess={()=>{setCheckoutAuthenticated(true);setMessage(language==="ar"?"تم تسجيل الدخول. سلتك محفوظة، أكمل طلبك الآن.":language==="en"?"Signed in. Your cart is ready to check out.":"Connexion réussie. Votre panier est conservé.");}}/>}</aside>}</div></div></div><dialog ref={categoryDialog} className="publicMenuCategoryDialog" onClick={e=>{if(e.target===e.currentTarget)categoryDialog.current?.close()}}><header><h2>{language==="ar"?"أقسام المنيو":"Menu categories"}</h2><button type="button" aria-label="إغلاق الأقسام" onClick={()=>categoryDialog.current?.close()}><MenuIcon kind="close"/></button></header><nav className="publicMenuCategories" aria-label="أقسام المنيو المختصرة">{categoryButtons}</nav></dialog>
 <MenuProductDetails item={selectedItem} groups={selectedItem?options[selectedItem.id]??[]:[]} selected={selectedItem?selectedOptions[selectedItem.id]??[]:[]} onSelection={ids=>{if(selectedItem)setSelectedOptions(v=>({...v,[selectedItem.id]:ids}))}} onAdd={()=>{if(selectedItem){addProduct(selectedItem);setSelectedItem(null)}}} onClose={()=>setSelectedItem(null)} language={language} category={selectedItem?localizedName(categories.find(c=>c.id===selectedItem.categoryId)??{name:''}):''} activePhoto={activePhoto} onPhoto={setActivePhoto}/>
 <footer className="publicMenuFooter">{branding.phone&&<p>{String(branding.phone)}</p>}{branding.platformBranding!=="hidden"&&(preview?<span>FOON · منيو يناسب ذوقك</span>:<Link href="/">FOON · منيو يناسب ذوقك</Link>)}</footer>
 <nav className="publicMenuMobileDock" aria-label={language==="ar"?"التنقل في المنيو":language==="en"?"Menu navigation":"Navigation du menu"}><a href="#menu-items"><span aria-hidden="true">⌂</span>{t.menu}</a><button type="button" onClick={()=>categoryDialog.current?.showModal()}><MenuIcon kind="menu"/><span>{language==="ar"?"الأقسام":language==="en"?"Categories":"Catégories"}</span></button><button type="button" onClick={()=>{if(count>0)document.getElementById('menu-cart')?.scrollIntoView({block:'start',behavior:'smooth'});else emptyCartDialog.current?.showModal()}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M3 4h2l3 11h10l3-8H6M10 20h.01M18 20h.01"/></svg><span>{t.cart}</span><b>{count}</b></button><MenuServiceActions slug={slug} branch={branch} branches={branches} tables={tables} sections={sections} services={services} authenticated={signedIn||checkoutAuthenticated} linked={isLinked} onAuthenticated={()=>setCheckoutAuthenticated(true)} language={language} preview={preview} showLabels/>{!preview&&<Link href={"/"+slug+"/login"}><span aria-hidden="true">○</span>{language==="ar"?"حسابي":language==="en"?"Account":"Compte"}</Link>}</nav>
 <dialog ref={emptyCartDialog} className="publicMenuEmptyCartDialog" aria-label={t.cart}><header><h2>{t.cart}</h2><button type="button" aria-label={language==="ar"?"إغلاق":language==="en"?"Close":"Fermer"} onClick={()=>emptyCartDialog.current?.close()}><MenuIcon kind="close"/></button></header><p>{language==="ar"?"سلتك فارغة. اختر ما تحب من القائمة لتجهيز طلبك.":language==="en"?"Your cart is empty. Choose something from the menu to start your order.":"Votre panier est vide. Choisissez un plat pour commencer votre commande."}</p><button type="button" onClick={()=>{emptyCartDialog.current?.close();document.getElementById('menu-items')?.scrollIntoView({block:'start',behavior:'smooth'})}}>{language==="ar"?"تصفح المنيو":language==="en"?"Browse menu":"Voir le menu"}</button></dialog>
 <dialog ref={qrDialog} className="publicMenuQrDialog" aria-label="QR Menu"><div className="publicMenuQrInner"><button type="button" className="publicMenuQrClose" onClick={()=>qrDialog.current?.close()} aria-label="إغلاق">✕</button><h2>{language==="ar"?"امسح الرمز لفتح المنيو":language==="en"?"Scan to open the menu":"Scannez pour ouvrir le menu"}</h2><p>{name}</p><img alt="رمز QR لرابط منيو المطعم" width={270} height={270} src={"https://quickchart.io/qr?size=360&margin=2&text="+encodeURIComponent("https://nfoodz.com/menu/"+slug)} /><p dir="ltr">nfoodz.com/menu/{slug}</p></div></dialog>
 </main>;
}
