"use client";
import {useRef,useState,type CSSProperties,type FormEvent} from "react";
import Image from "next/image";
import Link from "next/link";
import {useRouter} from "next/navigation";
import type {MenuGroup} from "@/lib/restaurant/menu";
import MenuChoices,{cartKey,choicePrice,choicesValid,type CartLine} from "../restaurant/menu-choices";
type MenuItem={id:string;name:string;branchId:string|null;categoryId:string|null;price:number;description:string;imageUrl:string|null;allergens:string};
type Props={name:string;slug:string;branding:Record<string,string|number|null>;items:MenuItem[];categories:{id:string;name:string}[];branches:{id:string;name:string}[];signedIn:boolean;linked:boolean;options:Record<string,MenuGroup[]>};
function contrast(color:string){const parts=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*parts[0]+.7152*parts[1]+.0722*parts[2]>.179?"#111827":"#ffffff";}
export default function PublicMenu({name,slug,branding,items,categories,branches,signedIn,linked,options}:Props){
 const router=useRouter(),[category,setCategory]=useState(""),[branch,setBranch]=useState(branches[0]?.id??""),[cart,setCart]=useState<Record<string,CartLine>>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const requestRef=useRef<{payload:string;key:string}|null>(null);
 const [selectedOptions,setSelectedOptions]=useState<Record<string,string[]>>({});
 const primary=typeof branding.primaryColor==="string"&&/^#[a-f0-9]{6}$/i.test(branding.primaryColor)?branding.primaryColor:"#c84f20";
 const style={"--public-brand":primary,"--public-on-brand":contrast(primary),fontFamily:branding.fontPreset==="georgia"?"Georgia,serif":branding.fontPreset==="tahoma"?"Tahoma,sans-serif":"Arial,sans-serif"} as CSSProperties;
 const visible=items.filter(item=>(!item.branchId||item.branchId===branch)&&(!category||item.categoryId===category)),sum=Object.values(cart).reduce((total,line)=>total+line.quantity*((items.find(item=>item.id===line.itemId)?.price??0)+choicePrice(options[line.itemId]??[],line.options)),0);
 async function join(){setBusy(true);try{const r=await fetch("/api/customer/stores",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({storeSlug:slug})});if(!r.ok)throw Error();router.refresh();setMessage("تم ربط حسابك بهذا المطعم.");}catch{setMessage("تعذر ربط الحساب بالمتجر.");}finally{setBusy(false);}}
 async function order(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setMessage("");const f=new FormData(event.currentTarget);try{const payload={storeSlug:slug,branchId:branch,channel:f.get("channel"),customerPhone:f.get("phone"),couponCode:f.get("coupon")||null,items:Object.values(cart).filter(line=>line.quantity>0).map(line=>({id:line.itemId,quantity:line.quantity,options:line.options}))};const encoded=JSON.stringify(payload);if(requestRef.current?.payload!==encoded)requestRef.current={payload:encoded,key:crypto.randomUUID()};const r=await fetch("/api/customer/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,requestKey:requestRef.current.key})});const data=await r.json();if(!r.ok){setMessage(data.code==="STORE_CUSTOMER_REQUIRED"?"اربط حسابك بالمطعم لإكمال الطلب.":data.code==="COUPON_LIMIT_REACHED"||data.code==="COUPON_UNAVAILABLE"?"الكوبون غير متاح حالياً.":"تعذر تسجيل الطلب. راجع الأصناف والكوبون وحاول مجدداً.");return;}requestRef.current=null;setCart({});setMessage("تم تسجيل طلبك. يمكنك متابعة حالته من طلباتي.");}catch{setMessage("تعذر الاتصال بالخادم.");}finally{setBusy(false);}}
 return <main className={"publicMenu "+(branding.menuTheme==="dark"?"publicMenuDark":"")} style={style} dir="rtl"><header className="publicMenuHeader"><div className="publicMenuIdentity">{branding.logoUrl&&<Image src={String(branding.logoUrl)} width={64} height={64} unoptimized alt={"شعار "+name}/>}<div><h1>{String(branding.brandName||name)}</h1>{branding.description&&<p>{String(branding.description)}</p>}</div></div><nav>{signedIn?<Link href="/customer">طلباتي</Link>:<Link href={"/"+slug+"/register"}>إنشاء حساب عميل</Link>}<Link href={"/"+slug+"/login"}>تسجيل الدخول</Link></nav></header>{branding.coverUrl&&<div className="publicMenuCover"><Image src={String(branding.coverUrl)} fill unoptimized alt={"غلاف "+name} sizes="100vw"/></div>}
 <div className="publicMenuToolbar"><label>الفرع<select value={branch} onChange={e=>{setBranch(e.target.value);setCart({});}}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><nav aria-label="تصنيفات المنيو"><button aria-pressed={!category} onClick={()=>setCategory("")}>الكل</button>{categories.map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</nav></div>
 {message&&<p role="status" className="publicMenuMessage">{message}</p>}
 <div className="publicMenuLayout"><section className="publicMenuItems">{visible.length?visible.map(item=><article key={item.id}>{item.imageUrl&&<div className="publicMenuItemImage"><Image src={item.imageUrl} fill unoptimized alt={item.name} sizes="(max-width:700px) 100vw,300px"/></div>}<div><h2>{item.name}</h2>{item.description&&<p>{item.description}</p>}{item.allergens&&<small>الحساسية: {item.allergens}</small>}<MenuChoices groups={options[item.id]??[]} selected={selectedOptions[item.id]??[]} onChange={ids=>setSelectedOptions(values=>({...values,[item.id]:ids}))}/><footer><strong>{item.price.toFixed(2)} ر.س</strong><button disabled={!choicesValid(options[item.id]??[],selectedOptions[item.id]??[])} onClick={()=>{const selected=selectedOptions[item.id]??[],key=cartKey(item.id,selected);setCart(v=>({...v,[key]:{itemId:item.id,options:selected,quantity:(v[key]?.quantity??0)+1}}));}}>إضافة +</button></footer></div></article>):<p className="publicMenuEmpty">لا توجد أصناف متاحة في هذا الفرع حالياً.</p>}</section><aside className="publicMenuCart"><h2>طلبك</h2>{Object.entries(cart).filter(([,line])=>line.quantity>0).map(([key,line])=><label key={key}>{items.find(item=>item.id===line.itemId)?.name}<input type="number" min={0} max={1000} value={line.quantity} onChange={e=>setCart(v=>({...v,[key]:{...line,quantity:Number(e.target.value)}}))}/></label>)}<strong>الإجمالي قبل الخصم: {sum.toFixed(2)} ر.س</strong>{linked?<form onSubmit={order}><label>نوع الطلب<select name="channel"><option value="takeaway">سفري</option><option value="dine_in">داخل المطعم</option><option value="delivery">توصيل</option></select></label><label>رقم التواصل<input name="phone" maxLength={40}/></label><label>كوبون الخصم<input name="coupon" maxLength={40}/></label><button disabled={busy||!Object.values(cart).some(line=>line.quantity>0)}>{busy?"جارٍ التسجيل…":"تسجيل الطلب"}</button><small>تسجيل الطلب لا يخصم مبلغاً إلكترونياً. اتفق على الدفع مع المطعم.</small></form>:signedIn?<button disabled={busy} onClick={()=>void join()}>متابعة كعميل لهذا المطعم</button>:<Link href={"/"+slug+"/register"}>سجّل حساب عميل لإكمال الطلب</Link>}</aside></div>
 <footer className="publicMenuFooter">{branding.address&&<p>{String(branding.address)}</p>}{branding.phone&&<p>{String(branding.phone)}</p>}{branding.platformBranding!=="hidden"&&<Link href="/">Powered by FOON</Link>}</footer></main>;
}
