import InlineCustomerAuth from "./inline-customer-auth";
"use client";
import {useRef,useState,type CSSProperties,type FormEvent} from "react";
import Image from "next/image";
import Link from "next/link";
import {useRouter} from "next/navigation";
import type {MenuGroup} from "@/lib/restaurant/menu";
import {isMenuTemplate,menuTemplates} from "@/lib/restaurant/menu-templates";
import MenuChoices,{cartKey,choicePrice,choicesValid,type CartLine} from "../restaurant/menu-choices";
type MenuItem={id:string;name:string;branchId:string|null;categoryId:string|null;price:number;description:string;imageUrl:string|null;allergens:string;oldPrice?:number|null;images?:string[];quantity?:number|null;calories?:number|null;nutrition?:string};
export type PublicMenuProps={name:string;slug:string;branding:Record<string,string|number|null>;items:MenuItem[];categories:{id:string;name:string}[];branches:{id:string;name:string}[];signedIn:boolean;linked:boolean;options:Record<string,MenuGroup[]>;preview?:boolean};
function contrast(color:string){const parts=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*parts[0]+.7152*parts[1]+.0722*parts[2]>.179?"#111827":"#ffffff";}
export default function PublicMenu({name,slug,branding,items,categories,branches,signedIn,linked,options,preview=false}:PublicMenuProps){
 const [language,setLanguage]=useState<"ar"|"en"|"fr">("ar");
 const translations={ar:{menu:"القائمة",items:"الأصناف",cart:"السلة",login:"دخول",account:"حساب عميل",orders:"طلباتي",search:"ابحث عن طبقك المفضل…",branch:"الفرع",all:"الكل",add:"إضافة",order:"تسجيل الطلب",type:"نوع الطلب",takeaway:"سفري",dine:"داخل المطعم",delivery:"توصيل",room:"خدمة الغرف",booking:"حجز مع الطلب"},en:{menu:"Menu",items:"Items",cart:"Cart",login:"Login",account:"Customer account",orders:"My orders",search:"Search the menu…",branch:"Branch",all:"All",add:"Add",order:"Place order",type:"Order type",takeaway:"Takeaway",dine:"Dine in",delivery:"Delivery",room:"Room service",booking:"Reservation with order"},fr:{menu:"Menu",items:"Articles",cart:"Panier",login:"Connexion",account:"Compte client",orders:"Mes commandes",search:"Rechercher dans le menu…",branch:"Succursale",all:"Tout",add:"Ajouter",order:"Commander",type:"Type de commande",takeaway:"À emporter",dine:"Sur place",delivery:"Livraison",room:"Service en chambre",booking:"Réservation avec commande"}};
 const t=translations[language];
 const router=useRouter(),[category,setCategory]=useState(""),[branch,setBranch]=useState(branches[0]?.id??""),[cart,setCart]=useState<Record<string,CartLine>>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [checkoutAuthenticated,setCheckoutAuthenticated]=useState(false);
 const isLinked=linked||checkoutAuthenticated;
 const requestRef=useRef<{payload:string;key:string}|null>(null);
 const [selectedItem,setSelectedItem]=useState<MenuItem|null>(null);
 const [activePhoto,setActivePhoto]=useState(0);
 const [selectedOptions,setSelectedOptions]=useState<Record<string,string[]>>({});
 const template=isMenuTemplate(branding.menuTheme)?branding.menuTheme:"sufra",templateInfo=menuTemplates.find(t=>t.id===template)!;
 const [search,setSearch]=useState(""),[layout,setLayout]=useState("template");
 const primary=typeof branding.primaryColor==="string"&&/^#[a-f0-9]{6}$/i.test(branding.primaryColor)?branding.primaryColor:templateInfo.accent;
 const style={"--public-brand":primary,"--public-on-brand":contrast(primary),fontFamily:branding.fontPreset==="georgia"?"Georgia,serif":branding.fontPreset==="tahoma"?"Tahoma,sans-serif":"Arial,sans-serif"} as CSSProperties;
 const visible=items.filter(item=>(!item.branchId||item.branchId===branch)&&(!category||item.categoryId===category)&&(item.name+" "+item.description).toLowerCase().includes(search.toLowerCase().trim())),sum=Object.values(cart).reduce((total,line)=>total+line.quantity*((items.find(item=>item.id===line.itemId)?.price??0)+choicePrice(options[line.itemId]??[],line.options)),0);
 async function join(){if(preview)return;setBusy(true);try{const r=await fetch("/api/customer/stores",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({storeSlug:slug})});if(!r.ok)throw Error();router.refresh();setMessage("تم ربط حسابك بهذا المطعم.");}catch{setMessage("تعذر ربط الحساب بالمتجر.");}finally{setBusy(false);}}
 async function order(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy||preview)return;setBusy(true);setMessage("");const f=new FormData(event.currentTarget);try{const payload={storeSlug:slug,branchId:branch,channel:f.get("channel"),customerPhone:f.get("phone"),couponCode:f.get("coupon")||null,items:Object.values(cart).filter(line=>line.quantity>0).map(line=>({id:line.itemId,quantity:line.quantity,options:line.options}))};const encoded=JSON.stringify(payload);if(requestRef.current?.payload!==encoded)requestRef.current={payload:encoded,key:crypto.randomUUID()};const r=await fetch("/api/customer/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,requestKey:requestRef.current.key})});const data=await r.json();if(!r.ok){setMessage(data.code==="STORE_CUSTOMER_REQUIRED"?"اربط حسابك بالمطعم لإكمال الطلب.":data.code==="COUPON_LIMIT_REACHED"||data.code==="COUPON_UNAVAILABLE"?"الكوبون غير متاح حالياً.":"تعذر تسجيل الطلب. راجع الأصناف والكوبون وحاول مجدداً.");return;}requestRef.current=null;setCart({});setMessage("تم تسجيل طلبك. يمكنك متابعة حالته من طلباتي.");}catch{setMessage("تعذر الاتصال بالخادم.");}finally{setBusy(false);}}
 const count=Object.values(cart).reduce((n,line)=>n+line.quantity,0);
 const mode=String(branding.colorMode||"template");
 return <main className={"publicMenu publicMenu-"+template} data-template={template} data-color-mode={mode} data-layout={layout} style={style} dir={language==="ar"?"rtl":"ltr"} lang={language}>
 <header className="publicMenuHeader"><a href="#menu-items" className="publicMenuWordmark">{String(branding.brandName||name)}</a><nav aria-label="روابط المطعم"><label><span className="sr-only">Language</span><select aria-label="Language / اللغة" value={language} onChange={e=>setLanguage(e.target.value as "ar"|"en"|"fr")}><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option></select></label>{preview?<span className="publicMenuPreviewBadge">معاينة · لا يُسجّل طلب فعلي</span>:<>{signedIn?<Link href="/customer">{t.orders}</Link>:<Link href={"/"+slug+"/register"}>{t.account}</Link>}<Link href={"/"+slug+"/login"}>{t.login}</Link></>}<a href="#menu-cart" aria-label="عرض السلة">{t.cart} <b>{count}</b></a></nav></header>
 <section className="publicMenuHero">{branding.coverUrl&&<Image className="publicMenuHeroImage" src={String(branding.coverUrl)} fill unoptimized alt="" sizes="100vw"/>}<div className="publicMenuHeroContent"><span className="publicMenuEyebrow">MENU / منيو المطعم</span><div className="publicMenuIdentity">{branding.logoUrl&&<Image src={String(branding.logoUrl)} width={76} height={76} unoptimized alt={"شعار "+name}/>}<div><h1>{String(branding.brandName||name)}</h1><p>{String(branding.description||"اختر ما يناسب ذوقك، وجهّز طلبك بكل سهولة.")}</p></div></div><div className="publicMenuHeroMeta"><span>{items.length} صنف</span><span>{categories.length} تصنيف</span>{branding.address&&<span>{String(branding.address)}</span>}</div></div><div className="publicMenuHeroMark" aria-hidden="true"><span>FOON</span><i>✳</i></div></section>
 <div className="publicMenuToolbar"><div className="publicMenuSearch"><span aria-hidden="true">⌕</span><input aria-label="البحث في المنيو" placeholder={t.search} type="search" value={search} onChange={e=>setSearch(e.target.value)}/></div><label className="publicMenuBranch">{t.branch}<select aria-label="فرع المطعم" value={branch} onChange={e=>{setBranch(e.target.value);setCart({});}}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div className="publicMenuViewToggle" role="group" aria-label="طريقة عرض المنيو"><button aria-pressed={layout==="template"} onClick={()=>setLayout("template")}>القالب</button><button aria-pressed={layout==="grid"} onClick={()=>setLayout("grid")}>شبكة</button><button aria-pressed={layout==="list"} onClick={()=>setLayout("list")}>قائمة</button></div></div>
 <nav className="publicMenuCategories" aria-label="تصنيفات المنيو"><button aria-pressed={!category} onClick={()=>setCategory("")}><span className="publicCategorySymbol" aria-hidden="true">✳</span><span>{t.all}</span><small>{items.length}</small></button>{categories.map((c,i)=><button key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}><span className="publicCategorySymbol" aria-hidden="true">{["◈","☕","✦","◉"][i%4]}</span><span>{c.name}</span><small>{items.filter(item=>item.categoryId===c.id).length}</small></button>)}</nav>
 {message&&<p role="status" className="publicMenuMessage">{message}</p>}
 <div className="publicMenuSectionTitle" id="menu-items"><div><span className="publicMenuEyebrow">EXPLORE / اكتشف</span><h2>{categories.find(c=>c.id===category)?.name||"من قائمة المطعم"}</h2></div><span>{visible.length} صنف متاح</span></div>
 <div className="publicMenuLayout"><section className="publicMenuItems" aria-label="أصناف المنيو">{visible.length?visible.map(item=><article key={item.id} className="publicMenuItem" role="button" tabIndex={0} aria-label={"تفاصيل "+item.name} onClick={()=>{setSelectedItem(item);setActivePhoto(0)}} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==="Enter"||e.key===" ")){e.preventDefault();setSelectedItem(item);setActivePhoto(0)}}}>{item.imageUrl?<div className="publicMenuItemImage"><Image src={item.imageUrl} fill unoptimized alt={item.name} sizes="(max-width:700px) 100vw,400px"/></div>:<div className="publicMenuItemImage publicMenuNoImage" aria-hidden="true"><span>✳</span></div>}<div className="publicMenuItemBody"><small className="publicMenuItemCategory">{categories.find(c=>c.id===item.categoryId)?.name}</small><h2>{item.name}</h2>{item.description&&<p>{item.description}</p>}{item.allergens&&<small>الحساسية: {item.allergens}</small>}{(options[item.id]?.length??0)>0&&<details className="publicMenuItemChoices" onClick={e=>e.stopPropagation()}><summary>خيارات الصنف</summary><MenuChoices groups={options[item.id]??[]} selected={selectedOptions[item.id]??[]} onChange={ids=>setSelectedOptions(values=>({...values,[item.id]:ids}))}/></details>}<footer><strong>{item.oldPrice!=null&&item.oldPrice>item.price&&<del style={{fontSize:".8em",opacity:.7,marginInlineEnd:8}}>{item.oldPrice.toFixed(2)}</del>}{(item.price+choicePrice(options[item.id]??[],selectedOptions[item.id]??[])).toFixed(2)} <small>ر.س</small></strong><button aria-label={"إضافة "+item.name+" إلى السلة"} disabled={!choicesValid(options[item.id]??[],selectedOptions[item.id]??[])} onClick={e=>{e.stopPropagation();const selected=selectedOptions[item.id]??[],key=cartKey(item.id,selected);setCart(v=>({...v,[key]:{itemId:item.id,options:selected,quantity:(v[key]?.quantity??0)+1}}));}}><span aria-hidden="true">＋</span><span>{t.add}</span></button></footer></div></article>):<div className="publicMenuEmpty"><span aria-hidden="true">✳</span><h3>{search||category?"لا توجد أصناف مطابقة":"المنيو قيد التجهيز"}</h3><p>{search||category?"جرّب كلمة بحث أو تصنيفًا آخر.":"ستظهر أصناف المطعم هنا بعد نشرها."}</p></div>}</section>
 <aside className="publicMenuCart" id="menu-cart"><header><div><small>YOUR ORDER</small><h2>سلة طلبك</h2></div><b>{count}</b></header>{count===0&&<p className="publicMenuCartEmpty">أضف ما تحب من القائمة لتجهيز طلبك.</p>}{Object.entries(cart).filter(([,line])=>line.quantity>0).map(([key,line])=><label key={key}><span>{items.find(item=>item.id===line.itemId)?.name}{line.options.length>0&&<small>{(options[line.itemId]??[]).flatMap(g=>g.values).filter(v=>line.options.includes(v.id)).map(v=>v.name).join("، ")}</small>}</span><input aria-label={"كمية "+items.find(item=>item.id===line.itemId)?.name} type="number" min={0} max={1000} value={line.quantity} onChange={e=>setCart(v=>({...v,[key]:{...line,quantity:Number(e.target.value)}}))}/></label>)}<div className="publicMenuCartTotal"><span>الإجمالي قبل الخصم</span><strong>{sum.toFixed(2)} ر.س</strong></div>{preview?<p className="publicMenuPreviewBadge">معاينة التصميم فقط</p>:linked?<form onSubmit={order}><label>{t.type}<select name="channel"><option value="takeaway">{t.takeaway}</option><option value="dine_in">{t.dine}</option><option value="delivery">{t.delivery}</option><option value="room_service" disabled>{t.room} — قريبًا</option><option value="reservation_order" disabled>{t.booking} — قريبًا</option></select></label><label>رقم التواصل<input name="phone" maxLength={40}/></label><label>كوبون الخصم<input name="coupon" maxLength={40}/></label><button disabled={busy||!Object.values(cart).some(line=>line.quantity>0)}>{busy?"جارٍ التسجيل…":"تسجيل الطلب"}</button><small>تسجيل الطلب لا يخصم مبلغًا إلكترونيًا. اتفق على الدفع مع المطعم.</small></form>:signedIn?<button disabled={busy} onClick={()=>void join()}>متابعة كعميل لهذا المطعم</button>:<InlineCustomerAuth slug={slug} language={language} onSuccess={()=>{setCheckoutAuthenticated(true);setMessage(language==="ar"?"تم تسجيل الدخول. سلتك محفوظة، أكمل طلبك الآن.":language==="en"?"Signed in. Your cart is ready to check out.":"Connexion réussie. Votre panier est conservé.");}}/>}</aside></div>
 {selectedItem&&<div role="presentation" onClick={()=>setSelectedItem(null)} style={{position:"fixed",inset:0,zIndex:1000,background:"#000b",display:"grid",placeItems:"center",padding:12}}><section role="dialog" aria-modal="true" aria-label={selectedItem.name} onClick={e=>e.stopPropagation()} style={{background:"#24221e",color:"#f8f3e9",borderRadius:16,width:"min(100%,560px)",maxHeight:"90dvh",overflowY:"auto",padding:20,boxSizing:"border-box"}}><button type="button" onClick={()=>setSelectedItem(null)} aria-label="إغلاق التفاصيل" style={{float:language==="ar"?"left":"right"}}>✕</button><h2>{selectedItem.name}</h2>{(()=>{const photos=[selectedItem.imageUrl,...(selectedItem.images??[])].filter((url):url is string=>Boolean(url)).slice(0,4);return photos.length?<div><div style={{position:"relative",width:"100%",height:260,marginBlock:10}}><Image src={photos[Math.min(activePhoto,photos.length-1)]} alt={selectedItem.name+" "+(activePhoto+1)} fill unoptimized style={{objectFit:"contain"}}/></div><div style={{display:"flex",gap:8,overflowX:"auto"}}>{photos.map((url,i)=><button key={i} type="button" onClick={()=>setActivePhoto(i)} aria-label={"الصورة "+(i+1)} aria-pressed={activePhoto===i} style={{position:"relative",width:70,height:70,flexShrink:0,border:activePhoto===i?"2px solid #e2a93b":"1px solid #777",borderRadius:8,overflow:"hidden"}}><Image src={url} fill unoptimized alt="" style={{objectFit:"cover"}}/></button>)}</div></div>:null})()}<p style={{whiteSpace:"pre-wrap"}}>{selectedItem.description||"لا يوجد وصف إضافي."}</p>{selectedItem.calories!=null&&<p>السعرات الحرارية: {selectedItem.calories} kcal</p>}{selectedItem.nutrition&&<p style={{whiteSpace:"pre-wrap"}}><strong>المعلومات الغذائية:</strong> {selectedItem.nutrition}</p>}{selectedItem.allergens&&<p><strong>مسببات الحساسية:</strong> {selectedItem.allergens}</p>}<p>{selectedItem.oldPrice!=null&&selectedItem.oldPrice>selectedItem.price&&<del style={{marginInlineEnd:10}}>{selectedItem.oldPrice.toFixed(2)}</del>}<strong>{selectedItem.price.toFixed(2)} SAR</strong></p>{selectedItem.quantity!=null&&<p>الكمية المتاحة: {selectedItem.quantity}</p>}{(options[selectedItem.id]?.length??0)>0&&<MenuChoices groups={options[selectedItem.id]??[]} selected={selectedOptions[selectedItem.id]??[]} onChange={ids=>setSelectedOptions(v=>({...v,[selectedItem.id]:ids}))}/>}<button type="button" disabled={!choicesValid(options[selectedItem.id]??[],selectedOptions[selectedItem.id]??[])} onClick={()=>{const selected=selectedOptions[selectedItem.id]??[],key=cartKey(selectedItem.id,selected);setCart(v=>({...v,[key]:{itemId:selectedItem.id,options:selected,quantity:(v[key]?.quantity??0)+1}}));setSelectedItem(null)}}>إضافة إلى السلة</button></section></div>}
 <footer className="publicMenuFooter">{branding.phone&&<p>{String(branding.phone)}</p>}{branding.platformBranding!=="hidden"&&(preview?<span>FOON · منيو يناسب ذوقك</span>:<Link href="/">FOON · منيو يناسب ذوقك</Link>)}</footer>
 <nav className="publicMenuMobileDock" aria-label="التنقل في المنيو"><a href="#menu-items"><span aria-hidden="true">⌂</span>القائمة</a><a href="#menu-items"><span aria-hidden="true">◈</span>الأصناف</a><a href="#menu-cart"><span aria-hidden="true">＋</span>{t.cart} <b>{count}</b></a>{!preview&&<Link href={"/"+slug+"/login"}><span aria-hidden="true">○</span>حسابي</Link>}</nav>
 </main>;
}
