"use client";
import {useSavedPreference} from "@/lib/ui/saved-preference";
import {type FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
type Lang="ar"|"en"|"fr";
type Theme="light"|"dark";
const activities=[{id:"restaurant",group:"restaurant",ar:"مطعم",en:"Restaurant",fr:"Restaurant"},{id:"cafe",group:"restaurant",ar:"مقهى",en:"Café",fr:"Café"},{id:"sweets",group:"restaurant",ar:"حلويات ومخبوزات",en:"Sweets & bakery",fr:"Pâtisserie"},{id:"grocery",group:"retail",ar:"بقالة وسوبرماركت",en:"Grocery & supermarket",fr:"Épicerie"},{id:"clothing",group:"retail",ar:"ملابس وأزياء",en:"Clothing & fashion",fr:"Vêtements"},{id:"perfume",group:"retail",ar:"عطور وتجميل",en:"Perfume & beauty",fr:"Parfumerie"},{id:"accessories",group:"retail",ar:"إكسسوارات وساعات",en:"Accessories & watches",fr:"Accessoires et montres"},{id:"gifts",group:"retail",ar:"هدايا وتغليف",en:"Gifts & wrapping",fr:"Cadeaux"},{id:"ecommerce",group:"retail",ar:"تجارة إلكترونية",en:"E-commerce",fr:"Commerce électronique"},{id:"carwash",group:"service",ar:"غسيل سيارات",en:"Car wash",fr:"Lavage auto"},{id:"laundry",group:"service",ar:"مغسلة ملابس",en:"Laundry",fr:"Blanchisserie"},{id:"automotive",group:"service",ar:"خدمات سيارات",en:"Automotive services",fr:"Services automobiles"},{id:"salon",group:"service",ar:"صالون وتجميل",en:"Salon & beauty",fr:"Salon de beauté"},{id:"publicworks",group:"service",ar:"مقاولات وخدمات عامة",en:"Public works & services",fr:"Travaux et services"}] as const;
const countries=[{code:"SA",ar:"السعودية",en:"Saudi Arabia",fr:"Arabie saoudite",currency:"SAR",tax:15},{code:"AE",ar:"الإمارات",en:"United Arab Emirates",fr:"Émirats arabes unis",currency:"AED",tax:5},{code:"BH",ar:"البحرين",en:"Bahrain",fr:"Bahreïn",currency:"BHD",tax:10},{code:"KW",ar:"الكويت",en:"Kuwait",fr:"Koweït",currency:"KWD",tax:0},{code:"OM",ar:"عُمان",en:"Oman",fr:"Oman",currency:"OMR",tax:5},{code:"QA",ar:"قطر",en:"Qatar",fr:"Qatar",currency:"QAR",tax:0},{code:"EG",ar:"مصر",en:"Egypt",fr:"Égypte",currency:"EGP",tax:14},{code:"JO",ar:"الأردن",en:"Jordan",fr:"Jordanie",currency:"JOD",tax:16},{code:"FR",ar:"فرنسا",en:"France",fr:"France",currency:"EUR",tax:20},{code:"US",ar:"الولايات المتحدة",en:"United States",fr:"États-Unis",currency:"USD",tax:0}] as const;
const copy={
 ar:{tag:"ابدأ مجانًا",title:"إنشاء حساب ومتجر",intro:"متجرك وباقتك المجانية يُفعّلان فور التسجيل، ويمكنك بدء العمل مباشرة.",name:"الاسم",store:"اسم النشاط",kind:"نوع النشاط",retail:"متجر",restaurant:"مطعم",slug:"رابط المتجر",email:"البريد الإلكتروني",password:"كلمة المرور",hint:"9 أحرف على الأقل",submit:"إنشاء الحساب",busy:"جارٍ الإنشاء…",hasAccount:"لديك حساب؟",login:"تسجيل الدخول",language:"اللغة",theme:"تبديل المظهر",exists:"هذا البريد مسجل مسبقًا.",slugExists:"رابط المتجر مستخدم، اختر رابطًا آخر.",failure:"تعذر إنشاء الحساب والمتجر. تحقق من البيانات وحاول مجددًا.",network:"تعذر الاتصال بالخادم. حاول مجددًا."},
 en:{tag:"Get started free",title:"Create your account and store",intro:"Your store and free plan activate on signup, so you can get started right away.",name:"Your name",store:"Business name",kind:"Business type",retail:"Store",restaurant:"Restaurant",slug:"Store URL",email:"Email address",password:"Password",hint:"At least 9 characters",submit:"Create account",busy:"Creating account…",hasAccount:"Already have an account?",login:"Sign in",language:"Language",theme:"Toggle appearance",exists:"This email is already registered.",slugExists:"This store URL is taken. Choose another.",failure:"Unable to create your account and store. Check your details and try again.",network:"Unable to connect to the server. Please try again."},
 fr:{tag:"Commencer gratuitement",title:"Créer un compte et une boutique",intro:"Votre boutique et votre formule gratuite sont activées dès l'inscription.",name:"Votre nom",store:"Nom de l'activité",kind:"Type d'activité",retail:"Boutique",restaurant:"Restaurant",slug:"Adresse de la boutique",email:"Adresse e-mail",password:"Mot de passe",hint:"Au moins 9 caractères",submit:"Créer un compte",busy:"Création en cours…",hasAccount:"Vous avez déjà un compte ?",login:"Se connecter",language:"Langue",theme:"Changer l'apparence",exists:"Cette adresse e-mail est déjà utilisée.",slugExists:"Cette adresse de boutique est déjà utilisée.",failure:"Impossible de créer le compte et la boutique. Vérifiez vos informations.",network:"Connexion au serveur impossible. Réessayez."}
} as const;
export default function RegisterPage(){
 const router=useRouter();const [error,setError]=useState("");const [step,setStep]=useState(1);const [country,setCountry]=useState("SA");const [taxRate,setTaxRate]=useState(15);const [busy,setBusy]=useState(false);const [lang]=useSavedPreference<Lang>("foon-public-lang",["ar","en","fr"],"ar");const [theme]=useSavedPreference<Theme>("foon-public-theme",["light","dark"],"light",true);
 const t=copy[lang];
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError("");const data=new FormData(e.currentTarget);
  try{
   const res=await fetch("/api/auth/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:data.get("name"),email:data.get("email"),password:data.get("password"),storeName:data.get("storeName"),slug:data.get("slug"),kind:data.get("kind"),activity:data.get("activity"),countryCode:country,currency:countries.find(c=>c.code===country)?.currency,taxRate})});const body=await res.json().catch(()=>({}));
   if(!res.ok){setError(body.code==="EMAIL_EXISTS"?t.exists:body.code==="SLUG_EXISTS"?t.slugExists:t.failure);return;}
   router.replace("/restaurant");router.refresh();
  }catch{setError(t.network)}finally{setBusy(false)}
 }
 return <main className="auth-shell foonAuthPage" data-theme={theme} dir={lang==="ar"?"rtl":"ltr"} lang={lang}><section className="auth-card"><div className="auth-heading"><Link href="/" className="auth-brand">FOON</Link><span className="foonAuthTag">✦ {t.tag}</span></div><h1>{t.title}</h1><p>{t.intro}</p>
 <form onSubmit={submit} className="auth-form"><p role="status">{lang==="ar"?`الخطوة ${step} من 2`:lang==="en"?`Step ${step} of 2`:`Étape ${step} sur 2`}</p><div style={{display:step===1?"contents":"none"}}><label>{t.name}<input name="name" autoComplete="name" required maxLength={180}/></label><label>{t.store}<input name="storeName" required minLength={2} maxLength={180}/></label><label>{t.kind}<select name="activity" required defaultValue=""><option value="" disabled>{lang==="ar"?"اختر نشاطك":lang==="en"?"Choose your activity":"Choisissez votre activité"}</option>{activities.map(a=><option key={a.id} value={a.id}>{a[lang]}</option>)}</select></label><label>{lang==="ar"?"الدولة":lang==="en"?"Country":"Pays"}<select value={country} onChange={e=>{const c=countries.find(x=>x.code===e.target.value);if(c){setCountry(c.code);setTaxRate(c.tax)}}}>{countries.map(c=><option key={c.code} value={c.code}>{c[lang]}</option>)}</select></label><label>{lang==="ar"?"العملة":lang==="en"?"Currency":"Devise"}<input readOnly dir="ltr" value={countries.find(c=>c.code===country)?.currency??"SAR"}/></label><label>{lang==="ar"?"نسبة الضريبة الافتراضية %":lang==="en"?"Default tax rate %":"Taux de taxe par défaut %"}<input type="number" dir="ltr" min="0" max="100" step=".01" value={taxRate} onChange={e=>setTaxRate(Number(e.target.value))}/><small>{lang==="ar"?"قيمة مبدئية قابلة للتعديل حسب النشاط والأنظمة المحلية.":lang==="en"?"Editable default; confirm local tax requirements.":"Valeur modifiable selon les règles locales."}</small></label><button type="button" onClick={e=>{const fields=e.currentTarget.parentElement?.querySelectorAll("input[required],select[required]");if(fields&&Array.from(fields).every(el=>(el as HTMLInputElement).reportValidity()))setStep(2)}}>{lang==="ar"?"التالي: بيانات الحساب":lang==="en"?"Next: Account details":"Suivant : Compte"}</button></div><div style={{display:step===2?"contents":"none"}}><label>{t.slug}<input name="slug" required minLength={3} maxLength={120} pattern="[a-z0-9][a-z0-9-]{1,118}[a-z0-9]" dir="ltr" placeholder="my-store"/></label><label>{t.email}<input name="email" type="email" autoComplete="email" required dir="ltr"/></label><label>{t.password}<input name="password" type="password" autoComplete="new-password" required minLength={9} maxLength={128} dir="ltr"/><small>{t.hint}</small></label>{error&&<div className="form-error" role="alert">{error}</div>}<button type="button" onClick={()=>setStep(1)}>{lang==="ar"?"السابق":lang==="en"?"Back":"Retour"}</button><button disabled={busy} aria-busy={busy}>{busy?t.busy:t.submit}</button></div></form><p className="auth-switch">{t.hasAccount} <Link href="/login">{t.login}</Link></p></section></main>
}
