"use client";
import {useSavedPreference} from "@/lib/ui/saved-preference";
import {type FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
type Lang="ar"|"en"|"fr";
type Theme="light"|"dark";
const copy={
 ar:{tag:"ابدأ مجانًا",title:"إنشاء حساب ومتجر",intro:"متجرك وباقتك المجانية يُفعّلان فور التسجيل، ويمكنك بدء العمل مباشرة.",name:"الاسم",store:"اسم النشاط",kind:"نوع النشاط",retail:"متجر",restaurant:"مطعم",slug:"رابط المتجر",email:"البريد الإلكتروني",password:"كلمة المرور",hint:"9 أحرف على الأقل",submit:"إنشاء الحساب",busy:"جارٍ الإنشاء…",hasAccount:"لديك حساب؟",login:"تسجيل الدخول",language:"اللغة",theme:"تبديل المظهر",exists:"هذا البريد مسجل مسبقًا.",slugExists:"رابط المتجر مستخدم، اختر رابطًا آخر.",failure:"تعذر إنشاء الحساب والمتجر. تحقق من البيانات وحاول مجددًا.",network:"تعذر الاتصال بالخادم. حاول مجددًا."},
 en:{tag:"Get started free",title:"Create your account and store",intro:"Your store and free plan activate on signup, so you can get started right away.",name:"Your name",store:"Business name",kind:"Business type",retail:"Store",restaurant:"Restaurant",slug:"Store URL",email:"Email address",password:"Password",hint:"At least 9 characters",submit:"Create account",busy:"Creating account…",hasAccount:"Already have an account?",login:"Sign in",language:"Language",theme:"Toggle appearance",exists:"This email is already registered.",slugExists:"This store URL is taken. Choose another.",failure:"Unable to create your account and store. Check your details and try again.",network:"Unable to connect to the server. Please try again."},
 fr:{tag:"Commencer gratuitement",title:"Créer un compte et une boutique",intro:"Votre boutique et votre formule gratuite sont activées dès l'inscription.",name:"Votre nom",store:"Nom de l'activité",kind:"Type d'activité",retail:"Boutique",restaurant:"Restaurant",slug:"Adresse de la boutique",email:"Adresse e-mail",password:"Mot de passe",hint:"Au moins 9 caractères",submit:"Créer un compte",busy:"Création en cours…",hasAccount:"Vous avez déjà un compte ?",login:"Se connecter",language:"Langue",theme:"Changer l'apparence",exists:"Cette adresse e-mail est déjà utilisée.",slugExists:"Cette adresse de boutique est déjà utilisée.",failure:"Impossible de créer le compte et la boutique. Vérifiez vos informations.",network:"Connexion au serveur impossible. Réessayez."}
} as const;
export default function RegisterPage(){
 const router=useRouter();const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [lang,setLang]=useSavedPreference<Lang>("foon-public-lang",["ar","en","fr"],"ar");const [theme,setTheme]=useSavedPreference<Theme>("foon-public-theme",["light","dark"],"light",true);
 const t=copy[lang];
 function changeLang(next:Lang){setLang(next);localStorage.setItem("foon-public-lang",next);setError("")}
 function toggleTheme(){const next=theme==="light"?"dark":"light";setTheme(next);localStorage.setItem("foon-public-theme",next)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError("");const data=new FormData(e.currentTarget);
  try{
   const res=await fetch("/api/auth/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:data.get("name"),email:data.get("email"),password:data.get("password"),storeName:data.get("storeName"),slug:data.get("slug"),kind:data.get("kind")})});const body=await res.json().catch(()=>({}));
   if(!res.ok){setError(body.code==="EMAIL_EXISTS"?t.exists:body.code==="SLUG_EXISTS"?t.slugExists:t.failure);return;}
   router.replace("/restaurant");router.refresh();
  }catch{setError(t.network)}finally{setBusy(false)}
 }
 return <main className="auth-shell foonAuthPage" data-theme={theme} dir={lang==="ar"?"rtl":"ltr"} lang={lang}><section className="auth-card"><div className="auth-heading"><Link href="/" className="auth-brand">FOON</Link><div className="foonAuthTopControls"><span className="foonAuthTag">✦ {t.tag}</span><button type="button" className="foonAuthThemeToggle" onClick={toggleTheme} aria-label={t.theme} aria-pressed={theme==="dark"}>{theme==="dark"?"☀":"☾"}</button><select className="foonAuthLanguage" aria-label={t.language} value={lang} onChange={e=>changeLang(e.target.value as Lang)}><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option></select></div></div><h1>{t.title}</h1><p>{t.intro}</p>
 <form onSubmit={submit} className="auth-form"><label>{t.name}<input name="name" autoComplete="name" required maxLength={180}/></label><label>{t.store}<input name="storeName" required minLength={2} maxLength={180}/></label><label>{t.kind}<select name="kind" defaultValue="store"><option value="store">{t.retail}</option><option value="restaurant">{t.restaurant}</option></select></label><label>{t.slug}<input name="slug" required minLength={3} maxLength={120} pattern="[a-z0-9][a-z0-9-]{1,118}[a-z0-9]" dir="ltr" placeholder="my-store"/></label><label>{t.email}<input name="email" type="email" autoComplete="email" required dir="ltr"/></label><label>{t.password}<input name="password" type="password" autoComplete="new-password" required minLength={9} maxLength={128} dir="ltr"/><small>{t.hint}</small></label>{error&&<div className="form-error" role="alert">{error}</div>}<button disabled={busy} aria-busy={busy}>{busy?t.busy:t.submit}</button></form><p className="auth-switch">{t.hasAccount} <Link href="/login">{t.login}</Link></p></section></main>
}
