"use client";
import {useSavedPreference} from "@/lib/ui/saved-preference";
import {Suspense,type FormEvent,useState} from "react";
import {useSearchParams} from "next/navigation";
import Link from "next/link";
type Lang="ar"|"en"|"fr";type Theme="light"|"dark";
const copy={
 ar:{title:"تعيين كلمة مرور جديدة",intro:"اختر كلمة مرور جديدة لحسابك.",password:"كلمة المرور الجديدة",confirm:"تأكيد كلمة المرور",submit:"حفظ كلمة المرور",busy:"جارٍ الحفظ…",success:"تم تغيير كلمة المرور. يمكنك تسجيل الدخول الآن.",mismatch:"كلمتا المرور غير متطابقتين.",invalid:"الرابط غير صالح أو انتهت صلاحيته. اطلب رابطًا جديدًا.",error:"تعذر تغيير كلمة المرور. حاول مجددًا.",login:"تسجيل الدخول",forgot:"طلب رابط جديد"},
 en:{title:"Set a new password",intro:"Choose a new password for your account.",password:"New password",confirm:"Confirm password",submit:"Save password",busy:"Saving…",success:"Your password has been changed. You can sign in now.",mismatch:"Passwords do not match.",invalid:"This link is invalid or has expired. Request a new link.",error:"Unable to change your password. Please try again.",login:"Sign in",forgot:"Request another link"},
 fr:{title:"Définir un nouveau mot de passe",intro:"Choisissez un nouveau mot de passe pour votre compte.",password:"Nouveau mot de passe",confirm:"Confirmer le mot de passe",submit:"Enregistrer",busy:"Enregistrement…",success:"Votre mot de passe a été modifié. Vous pouvez vous connecter.",mismatch:"Les mots de passe ne correspondent pas.",invalid:"Ce lien est invalide ou expiré. Demandez un nouveau lien.",error:"Impossible de modifier le mot de passe. Réessayez.",login:"Se connecter",forgot:"Demander un autre lien"}
} as const;
function ResetForm(){
 const params=useSearchParams();const token=params.get("token")||"";const [lang,setLang]=useSavedPreference<Lang>("foon-public-lang",["ar","en","fr"],"ar");const [theme,setTheme]=useSavedPreference<Theme>("foon-public-theme",["light","dark"],"light",true);const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState("");
 const t=copy[lang];const valid=/^[A-Za-z0-9_-]{43}$/.test(token);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy||!valid)return;const form=new FormData(event.currentTarget);const password=String(form.get("password")||"");if(password!==form.get("confirm")){setError(t.mismatch);return}setBusy(true);setError("");
  try{const response=await fetch("/api/auth/reset-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,password})});if(!response.ok){const data=await response.json().catch(()=>({}));setError(data.code==="RESET_TOKEN_INVALID"?t.invalid:t.error);return}setDone(true)}catch{setError(t.error)}finally{setBusy(false)}
 }
 return <main className="auth-shell foonAuthPage" data-theme={theme} dir={lang==="ar"?"rtl":"ltr"} lang={lang}><section className="auth-card"><div className="auth-heading"><Link href="/" className="auth-brand">FOON</Link><div className="foonAuthTopControls"><button type="button" className="foonAuthThemeToggle" onClick={()=>{const next=theme==="light"?"dark":"light";setTheme(next);localStorage.setItem("foon-public-theme",next)}} aria-label="Theme">{theme==="dark"?"☀":"☾"}</button><select className="foonAuthLanguage" value={lang} aria-label="Language" onChange={e=>{const next=e.target.value as Lang;setLang(next);localStorage.setItem("foon-public-lang",next)}}><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option></select></div></div><h1>{t.title}</h1><p>{t.intro}</p>
 {!valid?<div className="form-error" role="alert">{t.invalid}</div>:done?<div className="form-note" role="status">{t.success}</div>:<form className="auth-form" onSubmit={submit}><label>{t.password}<input type="password" name="password" required minLength={9} maxLength={128} autoComplete="new-password" dir="ltr"/></label><label>{t.confirm}<input type="password" name="confirm" required minLength={9} maxLength={128} autoComplete="new-password" dir="ltr"/></label>{error&&<div className="form-error" role="alert">{error}</div>}<button disabled={busy}>{busy?t.busy:t.submit}</button></form>}
 <p className="auth-switch"><Link href={done?"/login":"/forgot-password"}>{done?t.login:t.forgot}</Link></p></section></main>
}
export default function ResetPasswordPage(){return <Suspense fallback={<main className="auth-shell"/>}><ResetForm/></Suspense>}
