"use client";
import {useEffect,useState} from "react";
type Payment={id:string;tenant_name:string;plan_name:string;amount:string;currency:string;billing_cycle:string;transfer_reference:string;status:string;review_note:string|null;created_at:string};
export default function BillingManager({canEdit}:{canEdit:boolean}){
 const [payments,setPayments]=useState<Payment[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[notes,setNotes]=useState<Record<string,string>>({});
 async function refresh(){const r=await fetch("/api/admin/billing");const j=await r.json();if(!r.ok)throw Error(j.code);setPayments(j.requests??[]);}
 useEffect(()=>{let live=true;fetch("/api/admin/billing").then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.code);if(live)setPayments(j.requests??[]);}).catch(e=>{if(live)setMessage("تعذر التحميل: "+String(e));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 async function review(id:string,status:"approved"|"rejected"){const note=(notes[id]??"").trim();if(status==="rejected"&&!note){setMessage("اكتب سبب الرفض أولًا.");return;}setBusy(id);setMessage("");try{const r=await fetch("/api/admin/billing",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status,note})});const j=await r.json();if(!r.ok)throw Error(j.code);await refresh();setMessage("تم تسجيل القرار وتحديث الاشتراك عند الاعتماد.");}catch(e){setMessage("تعذرت المراجعة: "+String(e));}finally{setBusy("");}}
 return <section className="adminPanel adminOperationsPanel"><div className="adminPanelHead"><div><h2>طلبات الدفع</h2><p>الاعتماد يفعّل اشتراك المنشأة لمدة شهر أو سنة وفق الطلب. تحقق من وصول التحويل فعليًا قبل الاعتماد؛ لا يوجد تحقق بنكي آلي.</p></div></div>{loading?<p>جارٍ التحميل…</p>:payments.length===0?<div className="adminBillingEmpty">لا توجد طلبات دفع مسجلة.</div>:<div className="adminBillingGrid">{payments.map(p=><article className="adminBillingCard" key={p.id}><div><strong>{p.tenant_name}</strong><span>{p.plan_name}</span></div><b>{p.amount} {p.currency}</b><small>{p.billing_cycle==="yearly"?"سنوي":"شهري"} · {p.status==="pending"?"بانتظار المراجعة":p.status==="approved"?"معتمد":"مرفوض"}</small><p>مرجع التحويل: <span dir="ltr">{p.transfer_reference}</span></p>{p.review_note&&<p>ملاحظة: {p.review_note}</p>}{canEdit&&p.status==="pending"&&<div className="adminBillingReview"><label>ملاحظة المراجعة<input maxLength={500} value={notes[p.id]??""} onChange={e=>setNotes(v=>({...v,[p.id]:e.target.value}))}/></label><div><button disabled={!!busy} onClick={()=>review(p.id,"approved")}>اعتماد المراجعة</button><button disabled={!!busy} onClick={()=>review(p.id,"rejected")}>رفض مع السبب</button></div></div>}</article>)}</div>}{message&&<p role="status">{message}</p>}</section>;
}
