import {test,expect} from "@playwright/test";
import {spawn} from "node:child_process";
import mysql from "mysql2/promise";
import {randomUUID} from "node:crypto";
let server;
const origin="http://localhost:3102";
test.beforeAll(async()=>{
 const url=new URL(process.env.DATABASE_URL||"");expect(url.hostname).toBe("127.0.0.1");expect(url.pathname).toBe("/foon_migration_test");
 server=spawn(process.execPath,["node_modules/next/dist/bin/next","start","-p","3102"],{env:{...process.env,APP_URL:origin},stdio:"ignore"});
 for(let i=0;i<60;i++){try{await fetch(origin+"/login");return;}catch{await new Promise(resolve=>setTimeout(resolve,500));}}
 throw Error("Test server did not start");
});
test.afterAll(()=>server?.kill());
test("reference dashboard: authenticated tenant data, responsive layout and working navigation",async({page,browser})=>{
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(origin+"/register");
 await page.getByLabel("الاسم",{exact:true}).fill("مالك المعاينة");
 await page.getByLabel("اسم النشاط",{exact:true}).fill("مطعم المعاينة");
 await page.locator('select[name="activity"]').selectOption("restaurant");
 await page.getByRole("button",{name:"التالي: بيانات الحساب",exact:true}).click();
 await page.getByLabel("رابط المتجر",{exact:true}).fill("visual-dashboard");
 await page.getByLabel("البريد الإلكتروني",{exact:true}).fill("visual-dashboard@test.example");
 await page.getByLabel("كلمة المرور",{exact:false}).fill("a-strong-test-password");
 await page.getByRole("button",{name:"إنشاء الحساب",exact:true}).click();
 await expect(page.getByRole("heading",{name:"نظرة عامة",exact:true})).toBeVisible();
 await expect(page.getByRole("heading",{name:"مرحباً بفريق مطعم المعاينة",exact:true})).toBeVisible();
 await expect(page.locator(".restaurantBranchList").getByText("مطعم المعاينة",{exact:true})).toBeVisible();
 await expect(page.getByText("لا توجد طلبات محفوظة بعد",{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:"work/merchant-desktop.png",fullPage:true});
 await page.getByRole("navigation",{name:"أقسام المطعم"}).getByRole("button",{name:"الباقة والمميزات",exact:true}).click();
 await expect(page.getByRole("heading",{name:"اشتراك المطعم",exact:true})).toBeVisible();
 await page.keyboard.press("Control+k");
 await expect(page.getByRole("dialog",{name:"بحث في أقسام المطعم"})).toBeVisible();
 await page.getByRole("textbox",{name:"ابحث عن قسم",exact:true}).fill("الفروع");
 await page.getByRole("dialog").getByRole("button",{name:"الفروع والإعدادات",exact:true}).click();
 await expect(page.getByRole("heading",{name:"فروع المطعم",exact:true})).toBeVisible();
 await expect(page.getByRole("button",{name:"إضافة الفرع",exact:true})).toBeDisabled();
 const database=await mysql.createConnection(process.env.DATABASE_URL);
 await database.execute("UPDATE tenant_subscriptions s JOIN tenants t ON t.id=s.tenant_id SET s.plan_id='operations-enterprise' WHERE t.slug='visual-dashboard'");
 const [[visualTenant]]=await database.execute("SELECT t.id AS tenant,b.id AS branch FROM tenants t JOIN branches b ON b.tenant_id=t.id WHERE t.slug='visual-dashboard' LIMIT 1");
 await database.end();
 await page.reload();
 await page.getByRole("navigation",{name:"أقسام المطعم"}).getByRole("button",{name:"المنيو والأصناف",exact:true}).click();
 await page.getByRole("button",{name:"التصنيفات",exact:true}).click();
 await page.getByRole("button",{name:"إضافة قسم جديد",exact:true}).click();
 await page.getByLabel("اسم القسم",{exact:true}).fill("مشروبات المعاينة");
 await page.getByRole("button",{name:"حفظ البيانات",exact:true}).click();
 await expect(page.getByText("تم حفظ التغييرات بنجاح، ويمكنك مراجعتها في القائمة أدناه.",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"الأصناف",exact:true}).click();
 await page.getByRole("button",{name:"إضافة صنف جديد",exact:true}).click();
 await page.getByLabel("اسم الصنف",{exact:true}).fill("قهوة المعاينة");
 await page.getByLabel("السعر",{exact:true}).fill("10");
 await page.getByLabel("التصنيف",{exact:true}).selectOption({label:"مشروبات المعاينة"});
 await page.getByRole("button",{name:"حفظ البيانات",exact:true}).click();
 await expect(page.getByText("تم حفظ التغييرات بنجاح، ويمكنك مراجعتها في القائمة أدناه.",{exact:true})).toBeVisible();
 await page.getByRole("navigation",{name:"أقسام المطعم"}).getByRole("button",{name:"نقطة البيع",exact:true}).click();
 await page.locator(".restaurantPosMenu article").filter({hasText:"قهوة المعاينة"}).getByRole("button").click();
 await page.getByRole("button",{name:"إنشاء الطلب",exact:true}).click();
 await expect(page.getByText(/تم إنشاء الطلب/)).toBeVisible();
 await page.getByRole("button",{name:"تسجيل دفع يدوي",exact:true}).click();
 await expect(page.locator(".restaurantOrderCards").getByText("مدفوع",{exact:true})).toBeVisible();
 await page.getByRole("navigation",{name:"أقسام المطعم"}).getByRole("button",{name:"نظرة عامة",exact:true}).click();
 await expect(page.locator(".restaurantMetrics article").first().getByText("10.00 ر.س",{exact:true})).toBeVisible();
 await page.screenshot({path:"work/merchant-desktop.png",fullPage:true});
 await page.getByRole("navigation",{name:"أقسام المطعم"}).getByRole("button",{name:"المنيو والأصناف",exact:true}).click();
 await page.getByRole("button",{name:"القوالب والمظهر",exact:true}).click();
 const menuResponse=await page.request.get(origin+"/api/restaurant/operations/menu",{headers:{"x-foon-tenant":visualTenant.tenant}});
 const menuData=await menuResponse.json();const fixtureCategory=menuData.references.categories[0].id;
 for(const [name,price,description] of [["لاتيه الشوفان",18,"إسبريسو وحليب الشوفان بقوام ناعم."],["شاي بالنعناع",12,"شاي دافئ مع أوراق النعناع الطازجة."],["كيكة التمر",22,"كيكة تمر ناعمة، تُقدّم مع صوص الكراميل."]]){const saved=await page.request.post(origin+"/api/restaurant/operations/menu",{headers:{origin,"x-foon-tenant":visualTenant.tenant},data:{name,status:"active",branchId:visualTenant.branch,data:{categoryId:fixtureCategory,price,description}}});expect(saved.status()).toBe(201);}
 const imageUrls=[];const tinyPng=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=','base64');
 for(let i=0;i<4;i++){const uploaded=await page.request.post(origin+'/api/restaurant/assets',{headers:{origin,'x-foon-tenant':visualTenant.tenant},multipart:{file:{name:'fixture-'+i+'.png',mimeType:'image/png',buffer:tinyPng}}});expect(uploaded.status()).toBe(201);imageUrls.push((await uploaded.json()).url);}
 const coffee=menuData.resources.find(r=>r.name==='قهوة المعاينة'),fullDescription='قهوة محمصة طازجة تُحضّر بعناية، مع نكهات متوازنة وقوام غني. '.repeat(12)+'تفاصيل التحضير الكاملة محفوظة هنا.';
 const coffeeUpdated=await page.request.patch(origin+'/api/restaurant/operations/menu',{headers:{origin,'x-foon-tenant':visualTenant.tenant},data:{id:coffee.id,version:coffee.version,name:coffee.name,status:'active',branchId:visualTenant.branch,data:{categoryId:fixtureCategory,price:10,oldPrice:14,description:fullDescription,nameEn:'Preview coffee',descriptionEn:'Complete English description, including roasting and preparation.',imageUrl:imageUrls[0],calories:120,nutrition:'بروتين 3 غرام · كربوهيدرات 10 غرام',allergens:'الحليب',quantity:18}}});expect(coffeeUpdated.status()).toBe(200);
 for(let i=1;i<4;i++){const imageSaved=await page.request.post(origin+'/api/restaurant/operations/menuImages',{headers:{origin,'x-foon-tenant':visualTenant.tenant},data:{name:'صورة القهوة '+i,status:'active',branchId:visualTenant.branch,data:{itemId:coffee.id,imageUrl:imageUrls[i]}}});expect(imageSaved.status()).toBe(201);}
 const allProducts=await page.request.get(origin+'/api/restaurant/operations/menu',{headers:{'x-foon-tenant':visualTenant.tenant}});const latte=(await allProducts.json()).resources.find(r=>r.name==='لاتيه الشوفان');
 const groupSaved=await page.request.post(origin+'/api/restaurant/operations/menuGroups',{headers:{origin,'x-foon-tenant':visualTenant.tenant},data:{name:'الحجم',status:'active',branchId:visualTenant.branch,data:{itemId:latte.id,selectionType:'single',requiredFlag:'yes',minSelect:1,maxSelect:1}}});expect(groupSaved.status()).toBe(201);const optionGroup=(await groupSaved.json()).id;
 const optionSaved=await page.request.post(origin+'/api/restaurant/operations/menuValues',{headers:{origin,'x-foon-tenant':visualTenant.tenant},data:{name:'كبير',status:'active',branchId:visualTenant.branch,data:{groupId:optionGroup,priceDelta:2}}});expect(optionSaved.status()).toBe(201);const largeOption=(await optionSaved.json()).id;
 const publicContext=await browser.newContext();
 const publicPage=await publicContext.newPage();
 for(const [template,name] of [["classic","المعرض"],["minimal","القائمة"],["modern","السريع"],["sufra","السفرة"]]){
  await page.getByRole("radio",{name,exact:true}).check();
  await page.getByRole("combobox",{name:"مظهر المنيو",exact:true}).selectOption("template");
  await page.getByRole("button",{name:"حفظ القالب",exact:true}).click();
  await expect(page.getByText("تم حفظ القالب والمظهر. يظهر التغيير في منيو مطعمك مباشرة.",{exact:true})).toBeVisible();
  await publicPage.setViewportSize({width:1440,height:1000});
  await publicPage.goto(origin+"/visual-dashboard");
  await expect(publicPage.getByRole("heading",{name:"مطعم المعاينة",exact:true})).toHaveCount(1);
  await expect(publicPage.locator(".publicMenu")).toHaveAttribute("data-template",template);
  await expect(publicPage.getByRole("heading",{name:"قهوة المعاينة",exact:true})).toBeVisible();
  await publicPage.getByRole("searchbox",{name:"البحث في المنيو"}).fill("لا يوجد صنف بهذا الاسم");
  await expect(publicPage.getByRole("heading",{name:"لا توجد أصناف مطابقة",exact:true})).toBeVisible();
  await publicPage.getByRole("searchbox",{name:"البحث في المنيو"}).fill("");
  await publicPage.setViewportSize({width:390,height:844});
  const mobileDock=publicPage.getByRole('navigation',{name:'التنقل في المنيو',exact:true});
  await expect(mobileDock).toBeVisible();
  await mobileDock.getByRole('button',{name:'السلة',exact:false}).click();
  const emptyCart=publicPage.getByRole('dialog',{name:'السلة',exact:true});await expect(emptyCart).toContainText('سلتك فارغة');await emptyCart.press('Escape');
  await mobileDock.getByRole('button',{name:'الأقسام',exact:true}).click();await expect(publicPage.getByRole('dialog').getByRole('heading',{name:'أقسام المنيو',exact:true})).toBeVisible();await publicPage.getByRole('dialog').press('Escape');
  await publicPage.setViewportSize({width:1440,height:1000});
  await publicPage.getByRole("button",{name:"إضافة قهوة المعاينة إلى السلة",exact:true}).click();
  await expect(publicPage.getByLabel("كمية قهوة المعاينة",{exact:true})).toHaveValue("1");
  await publicPage.evaluate(()=>window.scrollTo(0,0));
  await publicPage.screenshot({path:"work/menu-"+template+"-desktop.png",fullPage:true});
  expect(await publicPage.locator('.publicMenuItem').evaluateAll(nodes=>nodes.every(n=>{const c=n.getBoundingClientRect(),p=n.querySelector('.publicMenuProductPrice strong').getBoundingClientRect(),b=n.querySelector('.publicMenuCardCart').getBoundingClientRect();return p.left>=c.left-1&&p.right<=c.right+1&&!(p.left<b.right&&p.right>b.left&&p.top<b.bottom&&p.bottom>b.top)}))).toBeTruthy();
  await publicPage.setViewportSize({width:390,height:844});
  await mobileDock.getByRole('button',{name:/السلة/}).click();await expect(publicPage.getByLabel('كمية قهوة المعاينة',{exact:true})).toBeInViewport();
  expect(await mobileDock.evaluate(n=>{const r=n.getBoundingClientRect();return r.bottom<=innerHeight+1&&r.top>=0&&r.left>=0&&r.right<=innerWidth})).toBeTruthy();
  await mobileDock.getByRole('link',{name:'القائمة',exact:true}).click();
  expect(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await publicPage.screenshot({path:"work/menu-"+template+"-mobile.png",fullPage:true});
  const gridBounds=await publicPage.locator('.publicMenuItem').evaluateAll(nodes=>nodes.slice(0,4).map(n=>{const r=n.getBoundingClientRect();return {top:r.top,width:r.width}}));expect(gridBounds.length).toBe(4);expect(Math.max(...gridBounds.map(r=>r.top))-Math.min(...gridBounds.map(r=>r.top)),JSON.stringify(gridBounds)).toBeLessThan(2);expect(gridBounds.every(r=>r.width>55&&r.width<100)).toBeTruthy();
  const coffeeCard=publicPage.locator('.publicMenuItem').filter({has:publicPage.getByRole('heading',{name:'قهوة المعاينة',exact:true})});await expect(coffeeCard.getByRole('img',{name:'قهوة المعاينة',exact:true})).toHaveJSProperty('naturalWidth',1);await expect(coffeeCard.locator('del')).toContainText('14.00');await expect(coffeeCard.locator('.publicMenuProductPrice strong')).toContainText('10.00');expect(await coffeeCard.locator('p').evaluate(n=>n.scrollHeight>n.clientHeight)).toBeTruthy();
  await publicPage.screenshot({path:"work/menu-"+template+"-mobile.png",fullPage:true});
 }
 await publicPage.setViewportSize({width:320,height:740});expect(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();expect(await publicPage.locator('.publicMenuItem').evaluateAll(nodes=>Math.max(...nodes.slice(0,4).map(n=>n.getBoundingClientRect().top))-Math.min(...nodes.slice(0,4).map(n=>n.getBoundingClientRect().top)))).toBeLessThan(2);
 expect(await publicPage.locator('.publicMenuMobileDock').evaluate(n=>{const r=n.getBoundingClientRect();return r.bottom<=innerHeight+1&&r.top>=0&&r.left>=0&&r.right<=innerWidth})).toBeTruthy();
 await publicPage.setViewportSize({width:390,height:844});
 await publicPage.getByRole('button',{name:'تفاصيل قهوة المعاينة',exact:true}).click();const details=publicPage.getByRole('dialog',{name:'قهوة المعاينة',exact:true});await expect(details).toBeVisible();await expect(details.getByText(fullDescription,{exact:true})).toBeVisible();await expect(details.getByText('مسببات الحساسية',{exact:true})).toBeVisible();await expect(details.getByText('بروتين 3 غرام · كربوهيدرات 10 غرام',{exact:true})).toBeVisible();await expect(details.getByText('120 kcal',{exact:true})).toBeVisible();await expect(details.locator('del')).toContainText('14.00');
 await details.getByRole('button',{name:'الصورة 4',exact:true}).click();await expect(details.getByRole('button',{name:'الصورة 4',exact:true})).toHaveAttribute('aria-pressed','true');await expect(details.locator('.publicMenuProductPhoto img')).not.toHaveAttribute('src',imageUrls[0]);await details.screenshot({path:'work/menu-product-details-mobile.png'});
 await details.press('Escape');await expect(details).toHaveCount(0);await expect(publicPage.getByRole('button',{name:'تفاصيل قهوة المعاينة',exact:true})).toBeFocused();
 await publicPage.getByRole('button',{name:'إضافة لاتيه الشوفان إلى السلة',exact:true}).click();const latteDetails=publicPage.getByRole('dialog',{name:'لاتيه الشوفان',exact:true});await expect(latteDetails.getByRole('button',{name:'إضافة إلى السلة',exact:true})).toBeDisabled();await latteDetails.getByLabel('خيارات الحجم',{exact:true}).selectOption(largeOption);await expect(latteDetails.locator('.publicMenuProductPrice strong')).toContainText('20.00');await latteDetails.getByRole('button',{name:'إضافة إلى السلة',exact:true}).click();await expect(latteDetails).toHaveCount(0);await expect(publicPage.getByLabel('كمية لاتيه الشوفان',{exact:true})).toHaveValue('1');
 await publicPage.locator('.publicMenuCategoryTrigger').click();
 await expect(publicPage.getByRole('dialog').getByRole('heading',{name:'أقسام المنيو',exact:true})).toBeVisible();
 await publicPage.getByRole('dialog').getByRole('button',{name:'مشروبات المعاينة',exact:false}).click();
 await expect(publicPage.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('navigation',{name:'أقسام المطعم'}).getByRole('button',{name:'الطاولات',exact:true}).click();
 await page.getByRole('button',{name:'الإضافة الجماعية',exact:true}).click();
 await page.getByLabel('اسم القسم',{exact:true}).fill('صالة العائلات');
 await page.getByLabel('عدد الطاولات',{exact:true}).fill('3');
 await page.getByRole('button',{name:'إنشاء الدفعة',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('تم إنشاء 3 طاولة');
 const floors=await page.request.get(origin+'/api/restaurant/operations/sections',{headers:{'x-foon-tenant':visualTenant.tenant}});const familySection=(await floors.json()).resources.find(r=>r.name==='صالة العائلات').id;
 await page.screenshot({path:'work/merchant-dining-batch-desktop.png',fullPage:true});
 const dining=await page.request.post(origin+'/api/restaurant/operations/tables',{headers:{origin,'x-foon-tenant':visualTenant.tenant},data:{name:'طاولة 7',branchId:visualTenant.branch,status:'available',data:{sectionId:familySection,number:7,capacity:4}}});expect(dining.status()).toBe(201);
 const tableId=(await dining.json()).id;
 await publicPage.reload();
 await publicPage.getByRole('navigation',{name:'التنقل في المنيو',exact:true}).getByRole('button',{name:'نداء النادل',exact:true}).click();
 await publicPage.getByRole('dialog').getByRole('button',{name:'إنشاء حساب سريع',exact:true}).click();
 await publicPage.getByRole('dialog').getByLabel('الاسم',{exact:true}).fill('ضيف المعاينة');
 await publicPage.getByRole('dialog').getByLabel('البريد الإلكتروني',{exact:true}).fill('visual-guest@test.example');
 await publicPage.getByRole('dialog').getByLabel('كلمة المرور',{exact:true}).fill('a-strong-test-password');
 await publicPage.getByRole('dialog').getByRole('button',{name:'متابعة الطلب',exact:true}).click();
 await expect(publicPage.getByRole('dialog').getByLabel('طاولتك',{exact:true})).toBeVisible();
 await publicPage.getByRole('dialog').screenshot({path:'work/menu-waiter-mobile.png'});
 await publicPage.getByRole('dialog').getByLabel('قسم الصالة',{exact:true}).selectOption(familySection);
 await publicPage.getByRole('dialog').getByLabel('طاولتك',{exact:true}).selectOption(tableId);
 await publicPage.getByRole('dialog').getByRole('button',{name:'إرسال الطلب',exact:true}).click();
 await expect(publicPage.getByRole('dialog').getByRole('status')).toContainText('وصل النداء');
 await publicPage.getByRole('dialog').getByRole('button',{name:'تم',exact:true}).click();
 await publicPage.getByRole('navigation',{name:'التنقل في المنيو',exact:true}).getByRole('button',{name:'حجز طاولة',exact:true}).click();
 await publicPage.getByRole('dialog').getByLabel('قسم الصالة',{exact:true}).selectOption(familySection);
 const nextDay=new Date(Date.now()+86400000);const localDate=new Date(nextDay.getTime()-nextDay.getTimezoneOffset()*60000).toISOString().slice(0,16);
 await publicPage.getByRole('dialog').getByLabel('موعد الحجز',{exact:true}).fill(localDate);
 await publicPage.getByRole('dialog').getByLabel('رقم التواصل',{exact:true}).fill('0500000000');
 await publicPage.getByRole('dialog').getByRole('button',{name:'إرسال الطلب',exact:true}).click();
 await expect(publicPage.getByRole('dialog').getByRole('status')).toContainText('ينتظر التأكيد');
 await publicPage.getByRole('dialog').screenshot({path:'work/menu-booking-mobile.png'});
 await publicPage.getByRole('dialog').getByRole('button',{name:'تم',exact:true}).click();
 const calls=await page.request.get(origin+'/api/restaurant/operations/waiterCalls',{headers:{'x-foon-tenant':visualTenant.tenant}});expect((await calls.json()).resources.some(row=>row.data.tableId===tableId&&row.status==='pending')).toBeTruthy();
 await page.getByRole('navigation',{name:'أقسام المطعم'}).getByRole('button',{name:'الطاولات',exact:true}).click();
 await page.getByRole('button',{name:'نداءات النادل',exact:true}).click();
 await expect(page.getByText('ضيف المعاينة',{exact:true})).toBeVisible();
 await publicPage.getByRole('button',{name:'إضافة قهوة المعاينة إلى السلة',exact:true}).click();
 await publicPage.getByLabel('نوع الطلب',{exact:true}).selectOption('dine_in');
 await publicPage.locator('#menu-cart').getByLabel('قسم الصالة',{exact:true}).selectOption(familySection);
 await publicPage.locator('#menu-cart').getByLabel('طاولتك',{exact:true}).selectOption(tableId);
 await publicPage.locator('#menu-cart').getByLabel('عدد الأشخاص',{exact:true}).fill('3');
 await publicPage.getByRole('button',{name:'تسجيل الطلب',exact:true}).click();
 await expect(publicPage.getByRole('status')).toContainText('تم تسجيل طلبك');
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('navigation',{name:'أقسام المطعم'}).getByRole('button',{name:'الحجوزات والانتظار',exact:true}).click();
 await expect(page.getByRole('heading',{name:'تقويم الحجوزات',exact:true})).toBeVisible();
 await expect(page.locator('.calendarEvent').filter({hasText:'ضيف المعاينة'})).toBeVisible();
 await page.screenshot({path:'work/merchant-reservations-calendar-desktop.png',fullPage:true});
 await page.locator('.calendarEvent').filter({hasText:'ضيف المعاينة'}).click();
 await expect(page.getByRole('dialog',{name:'تفاصيل الحجز'}).getByLabel('اسم الضيف',{exact:true})).toHaveValue('ضيف المعاينة');
 await page.getByRole('dialog',{name:'تفاصيل الحجز'}).getByLabel('الحالة',{exact:true}).selectOption('confirmed');
 await page.getByRole('dialog',{name:'تفاصيل الحجز'}).getByRole('button',{name:'حفظ البيانات',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'تفاصيل الحجز'})).toHaveCount(0);
 await expect(page.locator('.calendarEvent').filter({hasText:'ضيف المعاينة'})).toHaveAttribute('data-status','confirmed');
 const bookingDay=new Date(nextDay.getTime()+3*3600000).toISOString().slice(0,10);await page.getByRole('button',{name:'عرض حجوزات '+bookingDay,exact:true}).click();
 await page.getByRole('button',{name:'أسبوع',exact:true}).click();await expect(page.locator('.calendarGrid-week')).toBeVisible();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.screenshot({path:'work/merchant-reservations-calendar-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'يوم',exact:true}).click();await expect(page.locator('.calendarGrid-day')).toBeVisible();
 await page.setViewportSize({width:1440,height:1000});
 await publicPage.close();
 await publicContext.close();
 await page.getByRole('navigation',{name:'أقسام المطعم'}).getByRole('button',{name:'المنيو والأصناف',exact:true}).click();
 await page.getByRole('button',{name:'القوالب والمظهر',exact:true}).click();
 await page.getByRole("button",{name:"معاينة القالب",exact:true}).click();
 await expect(page.locator(".menuPreviewViewport .publicMenu")).toHaveAttribute("data-template","sufra");
 await expect(page.locator(".menuPreviewViewport").getByText("معاينة",{exact:true})).toBeVisible();
 await page.getByRole("combobox",{name:"مظهر المنيو",exact:true}).selectOption("light");
 await expect(page.locator(".menuPreviewViewport .publicMenu")).toHaveAttribute("data-color-mode","light");
 const unchanged=await page.request.get(origin+"/api/restaurant/menu/appearance",{headers:{"x-foon-tenant":visualTenant.tenant}});expect((await unchanged.json()).colorMode).toBe("template");
 await page.getByRole("combobox",{name:"مظهر المنيو",exact:true}).selectOption("template");
 await page.locator(".menuTemplateEditor").screenshot({path:"work/menu-studio-preview.png"});
 await page.getByRole("button",{name:"إغلاق المعاينة",exact:true}).click();
 await page.getByRole("navigation",{name:"أقسام المطعم"}).getByRole("button",{name:"نظرة عامة",exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await expect(page.getByRole("button",{name:"فتح قائمة المطعم",exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.screenshot({path:"work/merchant-mobile.png",fullPage:true});
 await page.getByRole("button",{name:"فتح قائمة المطعم",exact:true}).click();
 await page.locator(".restaurantDrawer").getByRole("button",{name:"الفروع والإعدادات",exact:true}).click();
 await expect(page.getByRole("heading",{name:"فروع المطعم",exact:true})).toBeVisible();
 await page.getByRole("combobox",{name:"اختيار الفرع",exact:true}).selectOption({label:"مطعم المعاينة"});
 await expect(page.locator(".restaurantBranchList").getByText("مطعم المعاينة",{exact:true})).toBeVisible();
 // A foreign tenant address must not expose its workspace.
 const db=await mysql.createConnection(process.env.DATABASE_URL);
 const foreignId=randomUUID();
 await db.execute("INSERT INTO tenants(id,slug,name,status) VALUES (?,'visual-foreign','Private foreign tenant','active')",[foreignId]);
 await db.end();
 await page.goto(origin+"/restaurant?tenant="+foreignId);
 await expect(page.getByText("Private foreign tenant",{exact:true})).toHaveCount(0);
});
test.setTimeout(180000);
