import test from "node:test";
import assert from "node:assert/strict";
import {spawn} from "node:child_process";
import mysql from "mysql2/promise";
import {resourceModules} from "./restaurant-resource-schema.mjs";
import {randomUUID} from "node:crypto";
const origin="http://localhost:3103";
test("restaurant operations preserve tenant, role, plan, pricing and transactional integrity",async()=>{
 const url=new URL(process.env.DATABASE_URL||"");assert.equal(url.hostname,"127.0.0.1");assert.equal(url.pathname,"/foon_migration_test");
 const db=await mysql.createConnection(url.href);
 const server=spawn(process.execPath,["node_modules/next/dist/bin/next","start","-p","3103"],{env:{...process.env,APP_URL:origin},stdio:"ignore"});
 const password="a-strong-test-password";
 const call=async(path,method,body,cookie,tenant)=>{
  const r=await fetch(origin+path,{method,headers:{origin,"content-type":"application/json",...(cookie?{cookie}:{}),...(tenant?{"x-foon-tenant":tenant}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
  return{status:r.status,body:await r.json(),cookie:r.headers.get("set-cookie")?.split(";")[0]};
 };
 const register=async(name)=>{const r=await call("/api/auth/register","POST",{name,storeName:name,slug:name,email:name+"@test.example",password,kind:"restaurant",activity:"restaurant",countryCode:"SA",currency:"SAR",region:"الرياض"});assert.equal(r.status,201,JSON.stringify(r.body));return{tenant:r.body.tenant.id,branch:r.body.branch.id,user:r.body.user.id,cookie:r.cookie,email:name+"@test.example"};};
 const resource=async(owner,module,body,method="POST")=>call("/api/restaurant/operations/"+module,method,body,owner.cookie,owner.tenant);
 const save=async(owner,module,name,data,status="active")=>{const r=await resource(owner,module,{name,status,data,branchId:owner.branch});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.id;};
 try{
  let ready=false;for(let i=0;i<60;i++){try{await fetch(origin+"/login");ready=true;break;}catch{await new Promise(resolve=>setTimeout(resolve,500));}}assert.ok(ready);
  const a=await register("operations-owner-a"),b=await register("operations-owner-b"),staff=await register("operations-kitchen");
  assert.equal((await resource(b,"pos",undefined,"GET")).status,403);
  await db.query("INSERT INTO package_plans(id,code,name_ar,name_en,name_fr) VALUES ('operations-enterprise','operations-enterprise','أعمال','Enterprise','Entreprise')");
  const keys=new Set([...Object.values(resourceModules).map(m=>m.feature).filter(Boolean),"orders","pos","kds","customers","multi_branch","analytics","branding.logo","branding.menu_theme","branding.dark_mode","branding.custom_font","branding.white_label"]);
  for(const key of keys){await db.execute("INSERT IGNORE INTO package_features(feature_key,name_ar,name_en,category) VALUES (?,?,?,'test')",[key,key,key]);await db.execute("INSERT INTO package_plan_features(plan_id,feature_key,enabled) VALUES ('operations-enterprise',?,TRUE)",[key]);}
  await db.execute("UPDATE tenant_subscriptions SET plan_id='operations-enterprise' WHERE tenant_id=?",[a.tenant]);
  // An active label must not hide an expired term or grant menu writes.
  await db.execute("UPDATE tenant_subscriptions SET ends_at=NOW()-INTERVAL 1 SECOND WHERE tenant_id=?",[a.tenant]);
  assert.equal((await resource(a,"menu",{name:"Expired item",status:"active",data:{price:10,categoryId:randomUUID()}})).body.code,"PLAN_FEATURE_REQUIRED");
  const expiredDashboard=await (await fetch(origin+"/restaurant?tenant="+a.tenant,{headers:{cookie:a.cookie}})).text();
  assert.ok(expiredDashboard.includes('منتهي'));
  assert.ok(!expiredDashboard.includes('الاشتراك نشط'));
  await db.execute("UPDATE tenant_subscriptions SET ends_at=NULL WHERE tenant_id=?",[a.tenant]);
  assert.equal((await resource(a,"menu",undefined,"GET")).status,200);
  const activeDashboard=await (await fetch(origin+"/restaurant?tenant="+a.tenant,{headers:{cookie:a.cookie}})).text();
  assert.ok(activeDashboard.includes('الاشتراك نشط'));
  const categoryA=await save(a,"categories","Drinks",{}),categoryB=await save(b,"categories","Private category",{});
  assert.equal((await resource(a,"menu",{name:"Invalid",status:"active",data:{price:10,categoryId:categoryB}})).status,404);
  assert.equal((await resource(a,"menu",{name:"Invalid branch",status:"active",branchId:b.branch,data:{price:10,categoryId:categoryA}})).status,404);
  const item=await save(a,"menu","Coffee",{price:10,oldPrice:15,calories:120,nutrition:"Protein 3g",allergens:"Milk",quantity:18,categoryId:categoryA});
  const persistedMenu=await resource(a,"menu",undefined,"GET"),persistedCoffee=persistedMenu.body.resources.find(r=>r.id===item);assert.equal(persistedCoffee.data.oldPrice,15);assert.equal(persistedCoffee.data.calories,120);assert.equal(persistedCoffee.data.quantity,18);assert.equal(persistedCoffee.data.nutrition,"Protein 3g");
  const editedCoffee=await resource(a,"menu",{id:item,version:persistedCoffee.version,name:"Coffee",status:"active",branchId:a.branch,data:{price:10,categoryId:categoryA,description:"Updated description"}},"PATCH");assert.equal(editedCoffee.status,200);const preservedCoffee=(await resource(a,"menu",undefined,"GET")).body.resources.find(r=>r.id===item);assert.equal(preservedCoffee.data.oldPrice,15);assert.equal(preservedCoffee.data.nutrition,"Protein 3g");
  const table=await save(a,"tables","Table 1",{capacity:4},"available");
  const family=await save(a,"sections","Families",{}),terrace=await save(a,"sections","Terrace",{});
  const batch=await resource(a,"sections",{branchId:a.branch,sections:[{id:family,name:"Families",start:1,count:2,capacity:4},{id:terrace,name:"Terrace",start:1,count:2,capacity:6}]});assert.equal(batch.status,201,JSON.stringify(batch.body));assert.equal(batch.body.count,4);
  const diningTable=batch.body.ids[0];
  const beforeBatch=(await resource(a,"tables",undefined,"GET")).body.resources.length;
  const badBatch=await resource(a,"sections",{branchId:a.branch,sections:[{id:family,name:"Families",start:3,count:1,capacity:4},{id:family,name:"Families",start:1,count:1,capacity:4}]});assert.equal(badBatch.body.code,"TABLE_NUMBER_EXISTS");assert.equal((await resource(a,"tables",undefined,"GET")).body.resources.length,beforeBatch);
  const concurrent=await Promise.all([1,2].map(()=>resource(a,"tables",{name:"طاولة 9",branchId:a.branch,status:"available",data:{sectionId:family,number:9,capacity:4}})));assert.equal(concurrent.filter(r=>r.status===201).length,1);assert.equal(concurrent.filter(r=>r.body.code==="TABLE_NUMBER_EXISTS").length,1);
  assert.equal((await resource(a,"sections",{id:family,version:1},"DELETE")).body.code,"SECTION_IN_USE");
  assert.equal((await resource(a,"sections",{name:"Foreign staff",branchId:a.branch,status:"active",data:{waiterId:randomUUID()}})).status,404);
  const stock=await save(a,"inventory","Coffee beans",{quantity:0,minimum:1,unit:"kg"});
  const supplier=await save(a,"suppliers","Supplier",{email:"supplier@test.example"});
  const purchase=await save(a,"purchases","Receipt",{inventoryId:stock,supplierId:supplier,quantity:3,unitCost:15},"received");
  let inventory=await resource(a,"inventory",undefined,"GET");assert.equal(inventory.body.resources[0].data.quantity,3);
  const repeated=await resource(a,"purchases",{id:purchase,version:1,name:"Receipt",status:"received",branchId:a.branch,data:{inventoryId:stock,quantity:3,unitCost:15}},"PATCH");assert.equal(repeated.status,400);
  inventory=await resource(a,"inventory",undefined,"GET");assert.equal(inventory.body.resources[0].data.quantity,3);
  const coupon=await save(a,"coupons","Save",{code:"SAVE10",discountType:"percent",value:10,usageLimit:1});
  assert.ok(coupon);
  const requestKey=randomUUID(),orderPayload={branchId:a.branch,channel:"dine_in",tableId:table,partySize:2,couponCode:"SAVE10",requestKey,total:0,items:[{id:item,quantity:2,price:0}]};
  const order=await resource(a,"pos",orderPayload);
  assert.equal(order.status,201,JSON.stringify(order.body));assert.equal(order.body.total,18);
  const replay=await resource(a,"pos",orderPayload);assert.equal(replay.status,201);assert.equal(replay.body.id,order.body.id);
  assert.equal((await resource(a,"pos",{branchId:a.branch,channel:"dine_in",couponCode:"SAVE10",items:[{id:item,quantity:1}]})).status,400);
  assert.equal((await call("/api/restaurant/operations/menu","GET",undefined,a.cookie,b.tenant)).status,403);
  assert.equal((await resource(a,"categories",{id:categoryB,version:1},"DELETE")).status,404);
  await save(a,"team","Kitchen employee",{email:staff.email,role:"kitchen"});
  assert.equal((await call("/api/restaurant/operations/menu","GET",undefined,staff.cookie,a.tenant)).status,403);
  assert.equal((await call("/api/restaurant/operations/pos","POST",{branchId:a.branch,channel:"takeaway",items:[{id:item,quantity:1}]},staff.cookie,a.tenant)).status,403);
  const kitchen=await call("/api/restaurant/operations/kds","GET",undefined,staff.cookie,a.tenant);assert.equal(kitchen.status,200);assert.equal(kitchen.body.orders[0].total,null);assert.equal(kitchen.body.orders[0].customer_phone,null);
  assert.equal((await resource(a,"orders",{id:order.body.id,version:1,paymentStatus:"paid"},"PATCH")).status,200);
  assert.equal((await resource(a,"orders",{id:order.body.id,version:2,status:"cancelled"},"PATCH")).body.code,"REFUND_REQUIRED");
  assert.equal((await call("/api/restaurant/operations/kds","PATCH",{id:order.body.id,version:2,status:"preparing"},staff.cookie,a.tenant)).status,200);
  assert.equal((await call("/api/restaurant/operations/kds","PATCH",{id:order.body.id,version:3,paymentStatus:"refunded"},staff.cookie,a.tenant)).status,403);
  assert.equal((await call("/api/restaurant/operations/kds","PATCH",{id:order.body.id,version:3,status:"ready"},staff.cookie,a.tenant)).status,200);
  assert.equal((await resource(a,"orders",{id:order.body.id,version:4,status:"completed"},"PATCH")).status,200);
  const branchList=await call("/api/restaurant/branches","GET",undefined,a.cookie,a.tenant);
  const mainBranch=branchList.body.branches.find(x=>x.id===a.branch);
  assert.equal((await call("/api/restaurant/branches","PATCH",{id:a.branch,version:mainBranch.version,name:"Renamed main"},a.cookie,a.tenant)).status,200);
  assert.equal((await call("/api/restaurant/branches","PATCH",{id:a.branch,version:mainBranch.version,name:"Stale change"},a.cookie,a.tenant)).status,409);
  const itemVersion=(await resource(a,"menu",undefined,"GET")).body.resources.find(r=>r.id===item).version;
  assert.equal((await resource(a,"menu",{id:item,version:itemVersion,name:"Coffee",status:"active",branchId:a.branch,data:{price:20,categoryId:categoryA}},"PATCH")).status,200);
  assert.equal((await resource(a,"menu",{id:item,version:itemVersion,name:"Coffee",status:"active",data:{price:30,categoryId:categoryA}},"PATCH")).status,409);
  const orders=await resource(a,"orders",undefined,"GET");assert.equal(orders.body.orders[0].total,18);assert.equal(orders.body.orders[0].items[0].price,10);
  const summary=await resource(a,"overview",undefined,"GET");assert.equal(summary.body.summary.sales,18);assert.equal(summary.body.summary.orders,1);
  const today=new Date(Date.now()+3*3600000).toISOString().slice(0,10);
  const report=await call("/api/restaurant/operations/reports?from="+today+"&to="+today,"GET",undefined,a.cookie,a.tenant);assert.equal(report.status,200);assert.equal(report.body.daily[0].sales,18);
  const employeeRows=await resource(a,"team",undefined,"GET"),employeeId=employeeRows.body.resources[0].id;
  const remoteTask=await save(a,"remote","Assigned task",{description:"Review menu",employeeId,budget:100},"assigned");
  await save(a,"remoteWorkers","Worker",{employeeId,skills:"Menu review"},"active");
  await save(a,"remoteMessages","Task message",{taskId:remoteTask,message:"Please review the menu."},"posted");
  await save(a,"remoteDeliveries","Delivery",{taskId:remoteTask,notes:"Review complete."},"submitted");
  for(const [module,name,data,status] of [
   ["attendance","Attendance",{employeeId,date:"2026-10-09"},"present"],
   ["reservations","Guest",{partySize:2,scheduledAt:"2026-10-09T18:00:00Z",tableId:table},"confirmed"],
   ["waitlist","Waiting guest",{partySize:2},"waiting"],
   ["remote","Remote task",{description:"Review menu",employeeId,budget:100},"assigned"],
   ["marketing","Campaign",{message:"Test draft only",channel:"email"},"draft"],
   ["settings","Branch settings",{openingTime:"08:00",closingTime:"23:00"},"active"],
   ["storefront","Brand",{primaryColor:"#224466",brandName:"Published brand",menuTheme:"modern",platformBranding:"hidden"},"active"]
  ])await save(a,module,name,data,status);
  const appearancePath="/api/restaurant/menu/appearance";
  assert.equal((await call(appearancePath,"PUT",{template:"classic",colorMode:"light"},a.cookie,b.tenant)).status,403);
  assert.equal((await call(appearancePath,"PUT",{template:"not-a-template"},a.cookie,a.tenant)).status,400);
  assert.equal((await call(appearancePath,"PUT",{template:"classic",colorMode:"invalid"},a.cookie,a.tenant)).status,400);
  for(const template of ["classic","minimal","modern","sufra"]){assert.equal((await call(appearancePath,"PUT",{template,colorMode:"dark"},a.cookie,a.tenant)).status,200);const saved=await call(appearancePath,"GET",undefined,a.cookie,a.tenant);assert.equal(saved.body.template,template);assert.equal(saved.body.colorMode,"dark");assert.equal(saved.body.preview.name,"operations-owner-a");const page=await fetch(origin+"/operations-owner-a");assert.equal(page.status,200);const html=await page.text();assert.ok(html.includes('data-template="'+template+'"'));assert.ok(html.includes('data-color-mode="dark"'));}
  assert.equal((await call(appearancePath,"GET",undefined,b.cookie,b.tenant)).body.template,"sufra");
  const publicMenu=await fetch(origin+"/operations-owner-a/order");assert.equal(publicMenu.status,200);assert.match(await publicMenu.text(),/Published brand/);
  const group=await save(a,"menuGroups","Size",{itemId:item,selectionType:"single",requiredFlag:"yes",minSelect:1,maxSelect:1});
  const option=await save(a,"menuValues","Large",{groupId:group,priceDelta:2});
  assert.equal((await resource(a,"pos",{branchId:a.branch,channel:"takeaway",items:[{id:item,quantity:1}]})).status,400);
  assert.equal((await resource(a,"pos",{branchId:a.branch,channel:"takeaway",items:[{id:item,quantity:1,options:[categoryB]}]})).status,400);
  const customer=await call("/api/customer/register","POST",{email:"operations-customer@test.example",name:"Customer",password,storeSlug:"operations-owner-a"});assert.equal(customer.status,201);
  const waiterPayload={storeSlug:"operations-owner-a",branchId:a.branch,action:"waiter",tableId:table,notes:"Water please",requestKey:randomUUID()};
  assert.equal((await call("/api/customer/services","POST",waiterPayload)).status,401);
  assert.equal((await call("/api/customer/services","POST",{...waiterPayload,storeSlug:"operations-owner-b",branchId:b.branch},customer.cookie)).status,403);
  assert.equal((await call("/api/customer/services","POST",{...waiterPayload,branchId:b.branch},customer.cookie)).status,404);
  const waiterCall=await call("/api/customer/services","POST",waiterPayload,customer.cookie);assert.equal(waiterCall.status,201,JSON.stringify(waiterCall.body));
  const replayCall=await call("/api/customer/services","POST",waiterPayload,customer.cookie);assert.equal(replayCall.status,200);assert.equal(replayCall.body.id,waiterCall.body.id);
  assert.equal((await call("/api/customer/services","POST",{...waiterPayload,requestKey:randomUUID()},customer.cookie)).status,429);
  const calls=await resource(a,"waiterCalls",undefined,"GET");assert.equal(calls.body.resources[0].status,"pending");assert.equal(calls.body.resources[0].data.tableId,table);
  assert.equal((await call("/api/restaurant/operations/waiterCalls","GET",undefined,customer.cookie,a.tenant)).status,403);
  const bookingPayload={storeSlug:"operations-owner-a",branchId:a.branch,action:"reservation",sectionId:family,partySize:3,phone:"0500000000",scheduledAt:new Date(Date.now()+86400000).toISOString(),requestKey:randomUUID()};
  assert.equal((await call("/api/customer/services","POST",{...bookingPayload,scheduledAt:new Date(Date.now()-60000).toISOString()},customer.cookie)).status,400);
  const booking=await call("/api/customer/services","POST",bookingPayload,customer.cookie);assert.equal(booking.status,201,JSON.stringify(booking.body));
  const savedBookings=await resource(a,"reservations",undefined,"GET");assert.equal(savedBookings.body.resources.find(row=>row.id===booking.body.id).status,"pending");
  const serviceOverview=await resource(a,"overview",undefined,"GET");assert.equal(serviceOverview.body.summary.waiterCalls,1);assert.equal(serviceOverview.body.summary.reservations,1);
  const bookingTime=new Date(Date.now()+2*86400000).toISOString();
  const allocated=await save(a,"reservations","Allocated guest",{partySize:2,scheduledAt:bookingTime,durationMinutes:90,sectionId:family,tableId:diningTable},"confirmed");assert.ok(allocated);
  assert.equal((await resource(a,"reservations",{name:"Overlap",status:"confirmed",branchId:a.branch,data:{partySize:2,scheduledAt:new Date(Date.parse(bookingTime)+60000).toISOString(),sectionId:family,tableId:diningTable}})).body.code,"BOOKING_CONFLICT");
  assert.equal((await resource(a,"reservations",{name:"Wrong section",status:"confirmed",branchId:a.branch,data:{partySize:2,scheduledAt:bookingTime,sectionId:terrace,tableId:diningTable}})).body.code,"SECTION_TABLE_MISMATCH");
  await save(a,"reservations","Next guest",{partySize:2,scheduledAt:new Date(Date.parse(bookingTime)+90*60000).toISOString(),tableId:diningTable},"confirmed");
  const ranged=await call("/api/restaurant/operations/reservations?from="+encodeURIComponent(bookingTime)+"&to="+encodeURIComponent(new Date(Date.parse(bookingTime)+86400000).toISOString()),"GET",undefined,a.cookie,a.tenant);assert.equal(ranged.status,200);assert.equal(ranged.body.resources.length,2);
  const waiterAccount=await register("operations-floor-waiter"),supervisorAccount=await register("operations-floor-supervisor");
  const waiterEmployee=await save(a,"team","Floor waiter",{email:waiterAccount.email,role:"waiter"}),supervisorEmployee=await save(a,"team","Floor supervisor",{email:supervisorAccount.email,role:"manager"});
  const assignment=await resource(a,"sections",{id:family,version:1,name:"Families",status:"active",branchId:a.branch,data:{waiterId:waiterEmployee,supervisorId:supervisorEmployee}},"PATCH");assert.equal(assignment.status,200,JSON.stringify(assignment.body));
  assert.equal((await resource(a,"sections",{name:"Wrong role",status:"active",branchId:a.branch,data:{waiterId:supervisorEmployee}})).body.code,"INVALID_SECTION_STAFF");
  assert.equal((await call("/api/restaurant/operations/sections","POST",{branchId:a.branch,sections:[{name:"Unauthorised",start:1,count:1,capacity:4}]},waiterAccount.cookie,a.tenant)).status,403);
  const dinePayload={storeSlug:"operations-owner-a",branchId:a.branch,channel:"dine_in",items:[{id:item,quantity:1,options:[option]}]};
  assert.equal((await call("/api/customer/orders","POST",dinePayload,customer.cookie)).body.code,"DINING_DETAILS_REQUIRED");
  assert.equal((await call("/api/customer/orders","POST",{...dinePayload,tableId:diningTable,partySize:5},customer.cookie)).body.code,"TABLE_CAPACITY_EXCEEDED");
  assert.equal((await call("/api/customer/orders","POST",{...dinePayload,tableId:randomUUID(),partySize:2},customer.cookie)).body.code,"TABLE_NOT_FOUND");
  const diningOrder=await call("/api/customer/orders","POST",{...dinePayload,tableId:diningTable,partySize:3},customer.cookie);assert.equal(diningOrder.status,201,JSON.stringify(diningOrder.body));
  const [[diningContext]]=await db.execute("SELECT dining_section_id,party_size,dining_snapshot FROM restaurant_orders WHERE id=?",[diningOrder.body.id]);assert.equal(diningContext.dining_section_id,family);assert.equal(diningContext.party_size,3);assert.match(JSON.stringify(diningContext.dining_snapshot),/Families/);
  const privateOverview=await call("/api/restaurant/operations/overview","GET",undefined,staff.cookie,a.tenant);assert.equal(privateOverview.body.summary.waiterCalls,0);
  const [[noStaff]]=await db.execute("SELECT COUNT(*) AS n FROM memberships WHERE user_id=? AND tenant_id=?",[customer.body.user.id,a.tenant]);assert.equal(noStaff.n,0);
  assert.equal((await call("/api/customer/orders","POST",{storeSlug:"operations-owner-b",branchId:b.branch,channel:"takeaway",items:[{id:item,quantity:1}]},customer.cookie)).status,403);
  const placed=await call("/api/customer/orders","POST",{storeSlug:"operations-owner-a",branchId:a.branch,channel:"takeaway",total:0,items:[{id:item,quantity:1,options:[option]}]},customer.cookie);assert.equal(placed.status,201);assert.equal(placed.body.total,22);
  const [[customerOrder]]=await db.execute("SELECT customer_user_id FROM restaurant_orders WHERE id=?",[placed.body.id]);assert.equal(customerOrder.customer_user_id,customer.body.user.id);
  const [[savedOptions]]=await db.execute("SELECT options_snapshot FROM restaurant_order_items WHERE order_id=?",[placed.body.id]);assert.match(JSON.stringify(savedOptions.options_snapshot),/Large/);
  const sessions=await resource(a,"security",undefined,"GET");assert.equal(sessions.status,200);
  const current=sessions.body.sessions.find(s=>s.current);assert.ok(current);
  assert.equal((await resource(a,"security",{id:current.id},"DELETE")).status,400);
  const foreignSessions=await resource(b,"security",undefined,"GET");assert.equal((await resource(a,"security",{id:foreignSessions.body.sessions[0].id},"DELETE")).status,404);
  assert.equal((await resource(a,"health",undefined,"GET")).body.database,"connected");
  const admin=await register("operations-platform-admin");
  await db.execute("INSERT INTO platform_admins(user_id,role,enabled) VALUES (?,'super_admin',TRUE)",[admin.user]);
  assert.equal((await call("/api/restaurant/operations/menu","GET",undefined,admin.cookie,b.tenant)).status,200);
  await db.execute("UPDATE auth_sessions SET last_seen_at=DATE_SUB(NOW(),INTERVAL 61 MINUTE) WHERE user_id=?",[admin.user]);
  assert.equal((await call("/api/restaurant/operations/menu","GET",undefined,admin.cookie,b.tenant)).status,403);
 }finally{server.kill();await db.end();}
});
