"use client";
import {useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
export default function CustomerProfileEditor({name,phone}:{name:string;phone:string}){
 const router=useRouter();const [displayName,setDisplayName]=useState(name),[phoneValue,setPhoneValue]=useState(phone),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/account/profile",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:displayName,phone:phoneValue})});if(!r.ok)throw Error();setMessage("تم حفظ بيانات حسابك بنجاح.");router.refresh();}catch{setMessage("لم يتم حفظ التغييرات. راجع الاسم ورقم الهاتف وحاول مجددًا.");}finally{setBusy(false);}}
 async function upload(type:string,file?:File){if(!file)return;setBusy(true);setMessage("");try{const form=new FormData();form.set("type",type);form.set("file",file);const r=await fetch("/api/account/media",{method:"POST",body:form});if(!r.ok)throw Error();setVersion(v=>v+1);setMessage("تم حفظ الصورة بنجاح.");router.refresh();}catch{setMessage("تعذر رفع الصورة. استخدم PNG أو JPEG أو WebP بحجم لا يتجاوز 2 ميجابايت.");}finally{setBusy(false);}}
 return <section className="customerProfileEditor" aria-label="إعدادات حسابي"><h2>إعدادات حسابي</h2><p>عدّل بياناتك وصور حسابك في أي وقت. هذا الحساب يتيح لك التسوق من متاجر مختلفة.</p><div className="customerProfileMedia">{(["avatar","logo","cover"] as const).map(type=><div key={type}><strong>{type==="avatar"?"الصورة الشخصية":type==="logo"?"الشعار أو الأيقونة":"صورة الغلاف"}</strong><img key={type+version} src={`/api/account/media?type=${type}&v=${version}`} alt={type==="avatar"?"الصورة الشخصية":type==="logo"?"الشعار":"الغلاف"} width={type==="cover"?220:88} height={88} onError={e=>{e.currentTarget.style.visibility="hidden"}}/><label className="customerUploadLabel">اختيار صورة<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>void upload(type,e.target.files?.[0])}/></label></div>)}</div><form onSubmit={save} className="customerProfileForm"><label>الاسم الكامل<input required minLength={2} maxLength={180} value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label><label>رقم الهاتف (اختياري)<input dir="ltr" inputMode="tel" maxLength={32} value={phoneValue} onChange={e=>setPhoneValue(e.target.value)}/></label><button disabled={busy}>{busy?"جارٍ الحفظ…":"حفظ التغييرات"}</button></form>{message&&<p role="status">{message}</p>}<form action="/api/auth/logout" method="post"><button className="customerLogout" type="submit">تسجيل الخروج من الحساب</button></form></section>;
}
